### ISSUE TITLE
[Bug]: Chrome autofill suggesting a password in the service field

### ISSUE THREAD

**Issue by AskAlice** [jaegertracing/jaeger-ui#1009]
### What happened?

While visiting jaeger-ui running locally via docker (jaegertracing/all-in-one:latest), The service text input somehow suggests that chrome generates a new strong password.

### Steps to reproduce

1. run the following
```
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 9411:9411 \
  jaegertracing/all-in-one:latest
  ```

  2. open http://localhost:16686 on 
`Google Chrome | 106.0.5249.119 (Official Build) (64-bit) (cohort: Stable)` in Windows 11 with chrome password manager/autofill enabled.
  
  3. click on the service text input and watch the browser pop up with a suggestion to generate a strong password.	

### Expected behavior

This is a text input, more often than that, it is used as a dropdown. It shouldn't block the legibility of the dropdown with some irrelevant suggestion.

### Screenshot

<img src="https://i.imgur.com/rSflKBj.gif" height="300px" />

### Deployment configs

```shell
jaegertracing/all-in-one                          latest    ca79bc1145d0   41 hours ago    61.4MB
```

**Comment by yurishkuro** [comment]
I don't see anything in the field's HTML attributes that would allow chrome to interpret this field as a password. Looks like a bug in Chrome, as they recently came out with more aggressive password autofill suggestions.

**Comment by yurishkuro** [comment]
Cannot reproduce
