### ISSUE TITLE
Log event text is not wrapped

### ISSUE THREAD

**Issue by jkrappa** [jaegertracing/jaeger-ui#101]
![image](https://user-images.githubusercontent.com/2537920/31900045-d874811c-b7e2-11e7-9538-4da3d71d4ba8.png)

**Description**
Contextual span logs currently get cut off from the view in the UI. Possible browser rendering issue.

**Steps to reproduce the issue:**
1. Create span
2. Add a long log message to the span
3. Open Jaeger UI and see logs are not wrapped

**Describe the results you received:**
Logs get cut off in the UI.

**Describe the results you expected:**
It would be nice if these longer messages could be wrapped or had scrolling functionality to view the whole message.

**Additional environment details (Browser, etc.):**
Occurs in both firefox and chrome.

**Comment by tiffon** [comment]
@jkrappa Thanks for filing this.

Are you using the all-in-one-build? It's currently fairly far behind jaeger-ui/master, and that's most likely the cause for the view not scrolling.

We're going to release a UI update in the all-in-one build, which should resolve this.

**Comment by freelinuxer** [comment]
@tiffon Thanks for quick reponse. Yes. we are using all-in-one for now to prototype tracing in our app. Would you kindly let us know about the release schedule on all-in-one build ? 
Thank you.

**Comment by freelinuxer** [comment]
@tiffon built and confirmed that the lastest UI resolves this issue. Still the update in all-in-one image would be useful since we use it often to test locally. Thanks !

**Comment by jkrappa** [comment]
Closing this issue since latest jaeger-ui has scrolling for logs
