### ISSUE TITLE
[Bug]: yarn start no longer works

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1052]
### What happened?

When developing UI features I should be able to start a dev version of the UI with `yarn start`

### Steps to reproduce

1. `rm -rf node_modules packages/jaeger-ui/node_modules packages/plexus/node_modules`
2. `yarn install --frozen-lockfile`
3. `yarn start`

### Expected behavior

dev build of the UI should start

### Relevant log output

```shell
$ yarn start
yarn run v1.22.18
$ cd packages/jaeger-ui && yarn start
$ react-app-rewired start
(node:24462) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
proxy is not a function
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional context

The `yarn start` worked at ce10d33.  However, it does't seem to work anymore since 7896ab50b544dab360133ec439a51d81012c3dc6, which contains an upgrade of many dependencies (PR #1001).

@mmorel-35 do you have any ideas what might have broken in the upgrade?

**Comment by mmorel-35** [comment]
Hi @yurishkuro,
Is it the only logs you have ?
What if you rollback react-app-rewired update ?
Otherwise, the whole upgrade will have to be completely rolled-back

**Comment by yurishkuro** [comment]
Those are all the logs from start command. If there's a debug mode I can try that. Are you saying that start works for you?

Ideally I would prefer to fix the issue than rollback so many updates.

**Comment by yurishkuro** [comment]
Found the issue
