### ISSUE TITLE
[Bug]: "Deep Dependency Graph" is not drawn.

### ISSUE THREAD

**Issue by Myeongseok-Kim** [jaegertracing/jaeger-ui#1077]
### What happened?

After finding Trace
When I click the "Deep Dependency Graph" button, no graph is drawn.

### Steps to reproduce

1. Find Traces
2. Deep Dependency Graph

### Expected behavior

graph is drawn

### Screenshot

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/54100684/203776562-9cb625ca-3aea-4fcc-9ee7-112b95a0b22f.png">

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/54100684/203776893-dcff62b3-b50f-4dc8-a998-7d245b4a7181.png">

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/54100684/203777162-68badd21-056a-4b51-adad-14ae11d395b5.png">

### Jaeger backend version

v.1.39.0

### Stogage backend

Elasticsearch 7.x

### Operating system

Linux

### Deployment model

Kubernetes

**Comment by yurishkuro** [comment]
May be related to fixes I had to add in #994

**Comment by yurishkuro** [comment]
update: I verified that the issue started after #1001

**Comment by stevenkitter** [comment]
I have the same problem, in 1.39.0 the graph is not drawn.

**Comment by stevenkitter** [comment]
When I use 1.40 version of query image, it's fine.
