### ISSUE TITLE
Document allowed operators on tag search

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-ui#11]
![image](https://cloud.githubusercontent.com/assets/833009/25640635/48239b1e-2f5e-11e7-9250-7ef78922e789.png)

The tag search prefilled text shows that a `|` is allowed, but there is no documentation about operators.

**Comment by pavolloffay** [comment]
A text message with an explanation of operators would be great. This text should be also possible to find and see when there is already some text in the input. This text could be shown when hovering on "Tags" title.
