### ISSUE TITLE
[Bug]: jaeger-ui/packages/jaeger-ui/src/components/App/TopNav.tsx，Cannot invoke an expression whose type lacks a call signature

### ISSUE THREAD

**Issue by ggjjlldd** [jaegertracing/jaeger-ui#1106]
### What happened?

```
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Failed to compile.

/root/jaeger/jaeger-ui/packages/jaeger-ui/src/components/App/TopNav.tsx
Type error: Cannot invoke an expression whose type lacks a call signature. Type 'never' has no compatible call signatures.  TS2349

    137 |         </Menu.Item>
    138 |         {NAV_LINKS.map(({ matches, to, text }) => {
  > 139 |           const url = typeof to === 'string' ? to : to(props);
        |                                                     ^
    140 |           const key = matches(pathname) ? pathname : url;
    141 |           return (
    142 |             <Menu.Item key={key}>


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce

1.cd jaeger-ui/packages/jaeger-ui
2. yarn install && yarn build && cd ../jaeger-ui/ && yarn install && yarn build
3. problem happend

### Expected behavior

work fine.

### Additional context

git log:
commit 217baa10b2260762bed592accb02cc6d2993f262
Author: Yuri Shkuro <yurishkuro@users.noreply.github.com>
Date:   Mon May 30 14:57:41 2022 -0400

    Prepare release v1.24.0 (#955)

**Comment by yurishkuro** [comment]
We don't patch old versions. Also, if this was an issue, our CI would've failed, so it's likely you have messed up deps in your install, so try deleting all node_modules and a clean `yarn install`
