### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#112]
Add a code of conduct that refers to [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md), e.g something like [Jaeger's COC](https://github.com/jaegertracing/jaeger/blob/master/CODE_OF_CONDUCT.md).

**Comment by yurishkuro** [comment]
not sure it's work repeating this in all Jaeger repositories

**Comment by tiffon** [comment]
Makes sense. Although, the approach taken by CNCF projects varies.
