### ISSUE TITLE
[Bug]: trace statistics and trace span table are using different look & feel

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1181]
### What happened?

When switching between views of a single trace I expect the UI to use similar visual design. Instead, these two views seem to use different table widgets. Obvious differences:
  * span table rows are much taller, for no reason
  * sorting indicators are different
  * statistics table can be sorted by any column, not so for spans table

### Steps to reproduce

open any trace (e.g. from HotROD) and flip between Trace Statistics and Spans Table views

### Expected behavior

look & feel should be similar

**Comment by prabin-acharya** [comment]
Hey, I will work on this. This will be my first.
