### ISSUE TITLE
[Feature]: Monitor Tab - use a different step for each time range

### ISSUE THREAD

**Issue by nofar9792** [jaegertracing/jaeger-ui#1213]
### Requirement

we have performance issues when we have a service with a lot of operations and we fetch for a long time range.
the latency request of the lower graphs takes 60 seconds

### Problem

we have a hard-coded step value: 60000 ms (1 min).
it means that if we fetch for 5 mins, we will get 6 metrics.
and when we fetch 2 days, we will get up to 2880 (!)

### Proposal

I suggest using a different step for each time range and I'd like to do it.
this is how it's going to affect the graphs:

for 2 days time range, the graphs look like this:
![image](https://user-images.githubusercontent.com/11076023/221422597-1f646c3e-a8ff-4afb-b55c-b8de3f97b36b.png)

and after the change (we lose a little bit from the accuracy):
![image](https://user-images.githubusercontent.com/11076023/221422613-5797fee5-1216-4163-a83f-5c7d808fae4f.png)

for 5 mins time range:
before:
![image](https://user-images.githubusercontent.com/11076023/221422750-8287695d-efba-4e4a-84f5-cee5c1214a20.png)

after:
![image](https://user-images.githubusercontent.com/11076023/221422763-5755c9ac-0a3f-4541-bb43-7a5531263b62.png)

from performance view, the latency request with group-by (the lower graphs) was improved from 60 seconds to 11 seconds.

**Comment by yurishkuro** [comment]
The basic math could be based on the resolution of the chart area: if it's N pixels wide, it doesn't make sense to query with higher resolution, ie we should have N <= timeRange/step <= 2N
