### ISSUE TITLE
[Feature]: Can I login in Query UI before use Query-UI?

### ISSUE THREAD

**Issue by zjzjzjzj1874** [jaegertracing/jaeger-ui#1214]
### Requirement

As we all known,ES can add user && password before we use;
so I wonder is there any way or config can set user && password before we use Jaeger-Query?

### Problem

There is not exist any way or config can set user && password before we use Jaeger-Query.

### Proposal

As we all known,ES can add user && password before we use;
so I wonder is there any way or config can set user && password before we use Jaeger-Query?

**Comment by DebasishBlockchain** [comment]
To add user and password authentication for Jaeger-Query, you can follow these steps:

**Step 1: Configure Authentication in Elasticsearch:**

1.1. Ensure that Elasticsearch (ES) is configured with user and password authentication. This typically involves setting up a secure Elasticsearch cluster with authentication enabled.

1.2. Create a user and assign the necessary roles and privileges for accessing the data you need in Jaeger-Query.

**Step 2: Modify Jaeger-Query Configuration:**

2.1. Locate the configuration file for Jaeger-Query. This file is often named `jaeger-query.yml` or similar.

2.2. Open the configuration file for editing.

2.3. Look for the Elasticsearch section of the configuration file, where you specify the Elasticsearch server's URL. It may look something like this:

```yaml
es:
  # URL for accessing Elasticsearch
  url: http://elasticsearch:9200
```

**Step 3: Add Authentication Details:**

3.1. Add the user and password credentials to the Elasticsearch URL in the configuration file. Include the credentials in the URL using the following format:

```yaml
es:
  # URL for accessing Elasticsearch with user and password
  url: http://username:password@elasticsearch:9200
```

Replace `username` and `password` with the actual Elasticsearch username and password you've configured in Step 1.

**Step 4: Save and Restart Jaeger-Query:**

4.1. Save the changes to the configuration file.

4.2. Restart the Jaeger-Query service to apply the updated configuration.

**Step 5: Test Authentication:**

5.1. After restarting Jaeger-Query, test the authentication by accessing Jaeger-Query's web interface or API. Ensure that it connects to Elasticsearch with the provided credentials.

5.2. Verify that you can access the Jaeger data securely, and that the user and password authentication is working as expected.

By following these steps, you should be able to configure user and password authentication for Jaeger-Query when it interacts with Elasticsearch. This helps secure your Jaeger installation and ensures that only authorized users can access the data.

**Comment by yurishkuro** [comment]
We do not plan to implement authentication in the UI. It can be handled with 3rd party reverse proxies, e.g. https://medium.com/jaegertracing/protecting-jaeger-ui-with-an-oauth-sidecar-proxy-34205cca4bb1
