### ISSUE TITLE
[Feature]: Adding Config for TotalMemory in LayoutManager for TraceGraph

### ISSUE THREAD

**Issue by ChenX1993** [jaegertracing/jaeger-ui#1249]
### Requirement

As a Jaeger operator,
I want to have `TotalMemory` option in config so that we have the flexibility to tune it for trace graph with large trace (15K+ spans).

### Problem

Today, we face the issue that the trace graph doesn't show up for large traces (with ~15K+ spans).

![Screenshot 2023-03-10 at 12 14 25 AM](https://user-images.githubusercontent.com/22260860/224260681-147f0939-613d-42a5-abd1-c634cf7d6446.png)

Error message:
```
Coordinator.js:115 Viz worker onerror 
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0  
```

I think the reason is the allocated memory for viz is not enough.
So when I provided a larger number for memory like below in code [here](https://github.com/jaegertracing/jaeger-ui/blob/main/packages/jaeger-ui/src/components/TracePage/TraceGraph/TraceGraph.tsx#L132), then the trace graph can show up successfully. 
```
// default 16MB
// 32MB: 33554432
this.layoutManager = new LayoutManager({ totalMemory: 33554432, useDotEdges: true, splines: 'polyline' });
```

### Proposal

I can fix by provide a large `totalMemory` when initializing `LayoutManager` for trace graph, but I don't think hardcode the value in the code (TraceGraph.tsx) is a good way, and default value is good enough for most use cases.

So I would like to have `totalMemory` exposed in the [config](https://github.com/jaegertracing/jaeger-ui/blob/main/packages/jaeger-ui/src/types/config.tsx), so that anyone has the flexibility to tune the `totalMemory` themselves if needed.

Like:
```
export type Config = {
  ....
  traceGraph?: {
     layoutManager?: {
        totalMemory?: number; 
     };
  };
  ...
};
```

If this proposal is ok with you, I can implement it and submit a PR.

**Comment by yurishkuro** [comment]
+1
