### ISSUE TITLE
[Enhancement]: Self time Calculation to be unified across multiple screens

### ISSUE THREAD

**Issue by RashmiRam** [jaegertracing/jaeger-ui#1263]
### Requirement

Enhancements to Trace statistics view 

- Similar Self Time as Trace Graph page. 
- Page to load faster for trace containing > 10K spans

### Problem

Trace Statistics View is unresponsive for traces > 10K spans if second Group By with high cardinality like tag.db@statement are selected.

Currently, there are 2 views in which self time is computed. 
- Trace Graph
- Trace Statistics

Both of them follow different logic. 
Key difference being Trace Graph [ignores](https://github.com/jaegertracing/jaeger-ui/blob/v1.27.4/packages/jaeger-ui/src/components/TracePage/TraceGraph/calculateTraceDagEV.tsx#L59) the follows-from relationship since the producer span doesn't have any control over when will the consumer span start whereas the Trace Statistics view computes the self time factoring in the [time spent between the start of the producer span and start of the consumer span](https://github.com/jaegertracing/jaeger-ui/blob/v1.27.4/packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.tsx#L214-L220). 

Moreover the logic used in trace graph is much simpler and easier to understand whereas the trace statistics view logic is very complex and page is unresponsive when computing self time for traces containing > 10K spans.

### Proposal

Use the similar logic in both Trace Graph & Trace Statistics views to compute the self time. If it's alright, I can raise a PR for the same.

**Comment by yurishkuro** [comment]
+1, PR is welcome

**Comment by GLVSKiriti** [comment]
Hey @yurishkuro I have a small doubt here.
In Trace Graph it ignores only Follows-from spans but not it descendants.
I think we should improve the code at this point and also can we implement the same logic in Trace Statistics view too?
https://github.com/jaegertracing/jaeger-ui/blob/15017d5570a508e1ef9368618e2cd8f0abacd16a/packages/jaeger-ui/src/components/TracePage/TraceGraph/calculateTraceDagEV.tsx#L57-L63

**Comment by yurishkuro** [comment]
> I think we should improve the code at this point and also can we implement the same logic in Trace Statistics view too?

Isn't this precisely what this ticket is asking to do?

**Comment by GLVSKiriti** [comment]
Yes, My idea is we already implemented the same in criticalPath PR.
https://github.com/jaegertracing/jaeger-ui/blob/97d8eefe243fcdba1250dabd5bbb60b9cb410c68/packages/jaeger-ui/src/components/TracePage/CriticalPath/utils/getChildOfSpans.tsx#L17-L53
So the usage of function is multiple. Can we keep this function in utils and proceed to implement further logic?

**Comment by yurishkuro** [comment]
I just replied on #1700 - I think there is a big difference in what CP needs and what self-time calculation needs. A FollowsFrom span can have its own ChildOf children and have a well defined self-time, despite not being on the global critical path. As I mentioned previously, a critical path is always defined at a specific subtree.

**Comment by GLVSKiriti** [comment]
Yes you are right!! I think my logic missed an important point. Will work on it!
