### ISSUE TITLE
[Feature]: Visualize Critical Path of a trace

### ISSUE THREAD

**Issue by ramumanam** [jaegertracing/jaeger-ui#1288]
This is filed as an intern project for the LFX Mentorship. Please refer to  https://github.com/jaegertracing/jaeger/issues/4453. [Apply here](https://mentorship.lfx.linuxfoundation.org/project/0fc6c44b-5ddf-467f-8016-72cc35b4e3ff).

### Requirement

Have an ability to view critical path for a given trace.

### Problem

A call graph can have multiple spans, but not all spans really contribute to the latency computation. Critical path is the longest chain of dependent tasks in a microservice dependency graph( i.e.,specific sequence of spans from the root to a leaf) . Reducing the critical path length is necessary to reduce the end-to-end latency of a request. Hence, a latency optimization effort benefits by prioritizing the services that are on the critical path. A tool to help identify the critical path of any trace I choose to investigate is  beneficial for developers.

Tools like "Lightstep observability" are already having this feature. This effort will be a feature parity for jaeger with other tools.

### Proposal

Jaeger already supports a bunch of different analysis views of a trace. It would be useful if Jaeger UI would allow a developer to view the critical path of the trace in the same context. 

We propose adding a new option under that dropdown labeled “Critical path”. A critical path is a specific sequence of spans from the root to a leaf. The [algorithm](https://github.com/uber-research/CRISP) to compute the critical path can be run in real-time even in the browser. Once the critical path is computed, it needs to be presented to the developer. 

The critical path could be rendered in either (or both) of the formats - tabular and flamegraph.
For efficiency, we may want to re-use the tabular and flame graph trace analysis views already available in Jaeger.

**Comment by yurishkuro** [comment]
do you have a design suggestion how to display it?

**Comment by yurishkuro** [comment]
Changing this particular view will be more difficult since we use a 3rd party library (pyroscope) for drawing flamegraphs. I am also not sure this is the best representation of the critical path. Your description said "A critical path is a specific sequence of spans from the root to a leaf", but it's not correct because critical path may descend into different sub-trees of the call graph. I thought you wanted a display similar to Lightstep where CP is shown on top of the Gantt chart view.

**Comment by ramumanam** [comment]
Hi @yurishkuro, I am attaching the following screenshots which gives an overview on what we are planning to do.
step1: Display an option "Trace Critical Path" on the dropdown as shown
<img width="1788" alt="Screenshot 2023-04-03 at 3 27 59 PM" src="https://user-images.githubusercontent.com/69380130/229485298-e86ee89e-fa1a-4d34-8f61-9e0439926950.png">

step2: On clicking "Trace Critical Path", computed critical path for the given trace should be rendered as follows
<img width="1788" alt="Screenshot 2023-04-03 at 3 31 40 PM" src="https://user-images.githubusercontent.com/69380130/229485510-f9534581-717a-44d8-9a45-795d2bdb0a7c.png">

**Comment by money8203** [comment]
Hey @ramumanam  I'd love to work on this project under LFX mentorship term 2. As I am learning go, I believe this project will be a great opportunity for me to apply my skills and gain hands-on experience. Looking forward to contributing to the project's success.

Could you provide me with some resources to get started with initially so that I can get myself familiarized with the project and its needs!

**Comment by haanhvu** [comment]
> Hey @ramumanam I'd love to work on this project under LFX mentorship term 2. As I am learning go, I believe this project will be a great opportunity for me to apply my skills and gain hands-on experience. Looking forward to contributing to the project's success.
> 
> Could you provide me with some resources to get started with initially so that I can get myself familiarized with the project and its needs!

I don't participate in this project. But I think you can start with learning Critical Path Analysis. For example this blog from Uber might be a good resource: https://www.uber.com/en-VN/blog/crisp-critical-path-analysis-for-microservice-architectures/

**Comment by ramumanam** [comment]
> Hey @ramumanam I'd love to work on this project under LFX mentorship term 2. As I am learning go, I believe this project will be a great opportunity for me to apply my skills and gain hands-on experience. Looking forward to contributing to the project's success.
> 
> Could you provide me with some resources to get started with initially so that I can get myself familiarized with the project and its needs!

FYI this project needs to get implemented using javascript React library

**Comment by money8203** [comment]
Okay, in the description it mentions 3 languages go, Js and Ts. So I've basic understanding of Js and currently exploring go, will that work ?

**Comment by money8203** [comment]
> > Hey @ramumanam I'd love to work on this project under LFX mentorship term 2. As I am learning go, I believe this project will be a great opportunity for me to apply my skills and gain hands-on experience. Looking forward to contributing to the project's success.
> > Could you provide me with some resources to get started with initially so that I can get myself familiarized with the project and its needs!
> 
> FYI this project needs to get implemented using javascript React library

Okay, in the description it mentions 3 languages go, Js and Ts. So I've basic understanding of Js and currently exploring go, will that work ?

**Comment by mugishasam123** [comment]
Hey @ramumanam , I am very interested in working on this project as a part of the LFX Mentorship program. I have prior experience working with Javascript, and Typescript and I believe this project would provide an excellent opportunity for me to enhance my skills and gain more practical experience in this field.

I am excited to learn more about the project and would appreciate any information or resources you can provide to help me prepare for the mentorship. Thank you for considering my application.

**Comment by yurishkuro** [comment]
Applicants interested in this project: please see https://github.com/jaegertracing/jaeger/issues/4453

**Comment by GLVSKiriti** [comment]
Hey @yurishkuro can you tell me what exactly we should do here
Whether to add another option trace critical path in drop down menu (or)
We should directly show the critical path of the trace above the Gantt chart in Trace timeline view

**Comment by yurishkuro** [comment]
Overlay critical path directly on the Gantt chart.

**Comment by GLVSKiriti** [comment]
issue resolved by referring to https://github.com/uber-research/CRISP/issues/1

**Comment by yurishkuro** [comment]
Whether to do CP in the backend or directly in the UI is one of the design decisions to be made as part of the project, but listing pros and cons of each.

**Comment by bhavukkalra** [comment]
Good Day everyone, My name is Bhavuk Kalra. I am full stack developer with experience in React, Redux, NodeJS and MongoDB. I have past experience with Jaeger as a consumer. 

One of the use cases that I really like about jaeger is that you can see distinctively what API's calls are going on amongst different microservices deployed on the cloud. Alongside of adding custom profile configuration which makes the debugging process really easy (This becomes a real helping hand in case of PROD scenarios) and also assists in removing any redundant API calls from the architecture as well!

 I believe this project would provide an excellent opportunity for me to enhance my skills and gain more practical experience in this field.

**Comment by yurishkuro** [comment]
@bhavukkalra feel free to apply to LFX mentorship (see https://github.com/jaegertracing/jaeger/issues/4453)

**Comment by bhavukkalra** [comment]
Hey @yurishkuro I just did actually. Really glad to see an Open Source project which gets used in the real Industry getting so much love from the community. It Helps take the project even further!

**Comment by yurishkuro** [comment]
as far as I know  https://slack.cncf.io/  is the way to get invite.

**Comment by bhavukkalra** [comment]
Got it. I tried with another Email as well, but didn't got the invite there as well. It seems the invite might not be working!
but thanks for looking into it @yurishkuro

**Comment by yurishkuro** [comment]
@GLVSKiriti will be working on this as part of LFX Mentorship

**Comment by ramumanam** [comment]
Hi @GLVSKiriti , here is some progress I made on the implementation. Feel free to use these changes and proceed further.
https://github.com/jaegertracing/jaeger-ui/pull/1470
