### ISSUE TITLE
¯\_(ツ)_/¯ is not very clear

### ISSUE THREAD

**Issue by Dieterbe** [jaegertracing/jaeger-ui#129]
![hut-waeuaoeuaoeue](https://user-images.githubusercontent.com/20774/33380895-7e9f7456-d4ea-11e7-84e6-b5bd25d17e67.png)

this is kindof neat (I know i have a problem with character encoding not rendering the shrugging person very well), but it would be nice if this could also somehow indicate why it's showing the shruggy thing, i'm probably missing a field in my traces, maybe it could explain me what's missing, via a little popup, or link to a faq entry or something

**Comment by yurishkuro** [comment]
Is that a tooltip? I have no idea what it means.

**Comment by Dieterbe** [comment]
it's a tooltip when you hover over traces in the timeline visualisation on top of the search results

**Comment by tiffon** [comment]
#117 should do away with it.

It indicates, sometimes erroneously, that the root trace is unknown and therefore the name of the trace is TBD.

**Comment by yurishkuro** [comment]
regardless of #117, if the UI cannot determine the "name" of the trace, it should show a better string than the shrug emoticon, like "cannot find trace name".

**Comment by Dieterbe** [comment]
FWIW I run into this despite having an all-jaeger stack, which doesn't seem to jive with #117 
also don't know if relevant here but I sometimes notice that my search results have "roots" that are actually supposed to be leaves. eg some operations halfway through processing. as if somehow some of the spans got lost. is that possible? I guess most likely some of the spans didn't make it through the pipeline correctly (maybe timeouts between agents and collector?)

**Comment by yurishkuro** [comment]
it's also possible that due to timing the query is picking up incomplete traces.

**Comment by tiffon** [comment]
Fixed by #134.
