### ISSUE TITLE
[Feature]: Support Google Analytics 4 properties

### ISSUE THREAD

**Issue by mehta-ankit** [jaegertracing/jaeger-ui#1332]
### Requirement

Starting July 1, 2023 Google will be transitioning to GA 4 properties.
The exact message on GA home page: 
```
On July 1, 2023, this property will stop processing data. Starting in March 2023, for continued website measurement, migrate your original property settings to a Google Analytics 4 (GA4) property, or they'll be copied for you to an existing GA4 property, reusing existing site tags.
```

### Problem

I created a GA4 version of my original Jaeger UI property and tried to use it but no luck. Looks like the react-ga package that is used in this repo does not support GA tags (Vs UA ones).
Found an issue in that repo: https://github.com/react-ga/react-ga/issues/541

### Proposal

I have not researched it enough, but looks like react-ga4 package might work for GA tags.
https://github.com/codler/react-ga4

**Comment by mehta-ankit** [comment]
any update on this ?

**Comment by yurishkuro** [comment]
Just did a bit of looking around. First, I don't quite understand what the point of `react-ga` library is, looks like a convenience wrapper around Google's code, but not clear what the value-add is. 

There are articles that explain how to do GA4 analytics without any 3rd party libraries, e.g. https://javascript.plainenglish.io/the-ultimate-guide-to-google-analytics-ua-ga4-on-react-or-anything-else-ec9dc84c0211

PRs are welcome.

**Comment by sambhavgupta0705** [comment]
@mehta-ankit are you still working on this issue?
If not then I would like to resolve this issue

**Comment by mehta-ankit** [comment]
> @mehta-ankit are you still working on this issue? If not then I would like to resolve this issue

Please go ahead and work on this @sambhavgupta0705 . I dnt think i have time to work it right now. Thanks a lot
