### ISSUE TITLE
Cannot find operations if there is '/' char in serviceName

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#138]
Re-booking https://github.com/jaegertracing/jaeger/issues/586

The UI must url-encode service name when calling the API to retrieve operation names:  `/api/services/{service}/operations`. It does _some_ encoding, but not correctly, e.g.
  * one of our internal services is emitting a bad service name `${artifactId}`, and the API request looked like this `/api/services/$%7BartifactId%7D/operations`, which is ok
  * however, when the service name contains a slash like `hotrod/customer`, the slash is not encoded correctly: `http://localhost:16686/api/services/hotrod/customer/operations`

Incidentally, the API supports an alternative endpoint `/api/operations?service={service}`, we should decide which one we want to keep.

**Comment by acehko** [comment]
Has this been fixed in the docker images?
I just tested with `1.2.0` and `latest` and the issue still exists.

**Comment by tiffon** [comment]
Very strange. Thank you for reporting. I will check it out.

**Comment by tiffon** [comment]
@yurishkuro after merging #140, I think this surfaced an issue in jaeger-query.

When running the hotrod demo with the service names to have `jaeger/` prepended now results in the following GET HTTP call to the query service for service `jaeger/customer`:

http://localhost:16686/api/services/jaeger%2Fcustomer/operations

The query service responds with the index.html.

I'll add details to and re-open jaegertracing/jaeger#586.

**Comment by tiffon** [comment]
Actually, I'm going to close this ticket so it's clear there isn't any outstanding UI work to resolve this.
