### ISSUE TITLE
Anyone konw how to open 16686 port?

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/jaeger-ui#139]
When I use npm start web-ui,but the port is 3000. In  README.md ,use commond
ssh -fN -L 16686:$BACKEND_HOST:$BACKEND_PORT $BACKEND_PORT.
But i got an error  in jaeger-ui under npm。
Error：Proxy error: Could not proxy request /api/traces?end=1513594957800000&limit=20&lookback=1h&maxDuration&minDuration&service=Elven_Trace&start=1513591357798000 from localhost:16686 to http://localhost:16686.
Commond：ssh -fN -L 16686:localhost:3000 myhostname@localhost

**Comment by saminzadeh** [comment]
The UI is hosted on Port 3000 in development which points to the jaeger query service (running independently) on port 16686 (if you are running the default configuration from https://github.com/jaegertracing/jaeger.)

Refer to the Getting Started page. Might be easier to use the docker all in package:
http://jaeger.readthedocs.io/en/latest/getting_started/

**Comment by wolfelven** [comment]
Sorry, I don't use docker to run jaeger Components, runned by theirself's main.go. the jaeger query service on port 16686, but UI's port is port 3000? So I can't understand how to use commond ssh?

**Comment by yurishkuro** [comment]
There is no port 3000 anymore. The query service runs on 16686. The UI in dev mode also goes to that port
```
./package.json:6:  "proxy": "http://localhost:16686",
```

If you run Jaeger all-in-one locally, you don't need to do an ssh tunnel, only if you're testing against remote query service.

**Comment by wolfelven** [comment]
I know proxy port is 16686, But I use npm start UI according to README.md, the port is 3000. so how to change?? And I use Cassandra storage

**Comment by yurishkuro** [comment]
1. run jaeger backend, e.g. from all-in-one image, or from source `go run ./cmd/standalone/main.go --span-storage.type=memory`. The query service will be running on 16668
1. run UI `npm start`. It will open the browser to localhost:3000 where UI webserver will be running.
1. the webserver will proxy all /api calls to :16686

You don't need any additional configuration, changes, tunnels.

**Comment by wolfelven** [comment]
So for example, When i click view trace json, the router path is http://localhost:3000/api/traces/1d44c3f7add2a818, and html got 404 error. If i change port 3000 to 16686, like http://localhost:16686/api/traces/1d44c3f7add2a818, the html is correct. 
And the package.json proxy is 16686.

**Comment by yurishkuro** [comment]
ah, that's true. Although that's probably the only view that doesn't work.

@tiffon any idea why? When I look in the inspector, then the trace view page sends the API request to the same :3000 port and works fine, but if I open that link in a new browser then I don't get the JSON, I get redirected to /search.

**Comment by tiffon** [comment]
@yurishkuro Yes, it's a result of this code block:

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/WebpackDevServerUtils.js#L319

```js

        // For single page apps, we generally want to fallback to /index.html.
        // However we also want to respect `proxy` for API calls.
        // So if `proxy` is specified as a string, we need to decide which fallback to use.
        // We use a heuristic: if request `accept`s text/html, we pick /index.html.
        // Modern browsers include text/html into `accept` header when navigating.
        // However API calls like `fetch()` won’t generally accept text/html.
        // If this heuristic doesn’t work well for you, use a custom `proxy` object.
        context: function(pathname, req) {
          return (
            mayProxy(pathname) &&
            req.headers.accept &&
            req.headers.accept.indexOf('text/html') === -1
          );
        },
```

I created PR #141 to resolve this. (It's pretty inconvenient.)

**Comment by worldsayshi** [comment]
I'm baffled by this. I'm just trying to test jaeger for the first time and nothing seems to work. I run:
```
$ docker run -d -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp   -p5778:5778 -p16686:16686 -p14268:14268 -p9411:9411 jaegertracing/all-in-one:latest
```
As written here: https://jaeger.readthedocs.io/en/latest/getting_started/#all-in-one-docker-image

But there is nothing on port 16686.
```
$ curl http://localhost:16686/
curl: (52) Empty reply from server
```

**Comment by worldsayshi** [comment]
Ok, so I restarted my machine and now it works perfectly. *X-files soundtrack playing*
