### ISSUE TITLE
[Feature]: log json folding

### ISSUE THREAD

**Issue by neopaf** [jaegertracing/jaeger-ui#1415]
### Requirement

As a user of Jaeger UI 
I want ability to fold long json blocks in span log entries
so that simplify search of particular value.

### Problem

Current JSON view only highlights keys, giving long hard-to find stuff view, example:
![Снимок экрана 2023-05-12 в 13 26 44](https://github.com/jaegertracing/jaeger-ui/assets/4362564/7156ac00-27e7-49ba-86f8-58c69928ba92)

Currently we use long log messages of hundreds of lines, very hard to quickly navigate to important parts.

### Proposal

Add folding interactions to JSON view, like in many JSON editors:
![Снимок экрана 2023-05-12 в 13 30 29](https://github.com/jaegertracing/jaeger-ui/assets/4362564/691324f6-fcef-4d47-b4b7-abde8fdb7d41)

Possible options:
* fold by default to 1st level of nesting
* expand/collapse all
* fold to 2/3/4 level 

See more possible ideas here:
https://www.jetbrains.com/help/rider/Code_Folding.html

But the basic: just ability to fold not-interesting region -- we absolutely need it.

**Comment by yurishkuro** [comment]
What if instead we provide an ability to open this JSON in a separate tab? There are tons of browser extensions for displaying JSON, with folding capabilities, etc., which we wouldn't need to support in Jaeger UI.

**Comment by BenzeneAlcohol** [comment]
Hey @yurishkuro , I would like to work on this. What method do you suggest, display JSON in a seperate tab or find out a way to do the minimisation within the UI?

**Comment by GLVSKiriti** [comment]
Hey @yurishkuro , Is this type of json view is still there now??, I tested it in hotrod app but I cant find this type of json view in span log entries in jaeger ui
