### ISSUE TITLE
[Feature]: Adapt SPM to use OTEL Span Metrics Connector instead Span Metrics Processor

### ISSUE THREAD

**Issue by ChristoPedro** [jaegertracing/jaeger-ui#1461]
### Requirement

OTEL is deprecating the Span Metrics Processor to use Span Metrics Connector.

### Problem

The operation metric attribute was renamed to span.name.
The latency histogram metric name was changed to duration.
The _total metric prefix was dropped from generated metrics names.
The Prometheus-specific metrics labels sanitization was dropped.

### Proposal

Update SPM query to Prometheus to collect the new atributes generated by Span Metrics Connector.

**Comment by yurishkuro** [comment]
I believe this is already addressed by https://github.com/jaegertracing/jaeger/pull/4452
