### ISSUE TITLE
[bug] Flaky test causing spurious drops in code coverage

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1489]
The test coverage keeps changing from run to run, indicating that there is some non-determinism in the test that's causing different code paths to be exercised. Ideally we should have tests that exercise both code paths.

![image](https://github.com/jaegertracing/jaeger-ui/assets/3523016/c7683448-044b-4d3b-acc9-b6a368933983)

**Comment by aroramrinaal** [comment]
Hello @yurishkuro ,
I would like to work on this good-first-issue.

**Comment by yurishkuro** [comment]
You're welcome to submit a PR.

**Comment by aroramrinaal** [comment]
hey @yurishkuro,
I have thought of the following changes in the [SpanBarRow.test.js](https://github.com/jaegertracing/jaeger-ui/blob/main/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanBarRow.test.js) file for addressing this issue.

1. Modify the isDetailExpanded prop to true in the props object: 
`const props = {
  // ...
  isDetailExpanded: true,
  // ...
};
`
2. Modify the isChildrenExpanded prop to false in the props object:
`const props = {
  // ...
  isChildrenExpanded: false,
  // ...
};
`

1. Modify the showErrorIcon prop to true in the props object:

`const props = {
  // ...
  showErrorIcon: true,
  // ...
};
`

4. Modify the span object to include multiple references in the references array:

`const span = Object.assign(
  {
    references: [
      {
        refType: 'CHILD_OF',
        traceID: 'trace1',
        spanID: 'span0',
        span: {
          spanID: 'span0',
        },
      },
      {
        refType: 'CHILD_OF',
        traceID: 'otherTrace',
        spanID: 'span1',
        span: {
          spanID: 'span1',
        },
      },
    ],
  },
  props.span
);
`

5. Update the it block for the references button test case to expect the presence of the button and its tooltip text:
`it('renders the references button', () => {
  const spanRow = shallow(<SpanBarRow {...props} span={span} />);
  const refButton = spanRow.find(ReferencesButton);
  expect(refButton.length).toEqual(1);
  expect(refButton.prop('tooltipText')).toEqual('Contains multiple references');
});
`

**Comment by yurishkuro** [comment]
@aroramrinaal I am not sure what these changes are aiming to achieve. The point is that the test is currently non-deterministically going into different code-paths from run to run, causing code coverage differences being flagged. The objective is to either make it deterministic and always exercise the same path, or exercise both code paths between which  it's currently alternating.
