### ISSUE TITLE
HotROD traces display without trace name

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#149]
@tiffon I just tried the latest UI and saw this

![image](https://user-images.githubusercontent.com/3523016/34313548-ea39d8f8-e739-11e7-9c96-b1947187900e.png)

**Comment by yurishkuro** [comment]
This could be a server-side issue, the root span doesn't look right, span reference with traceID=0 is invalid
```
        {
          "traceID": "3fb3f396b13217b",
          "spanID": "3fb3f396b13217b",
          "flags": 1,
          "operationName": "HTTP GET /dispatch",
          "references": [
            {
              "refType": "CHILD_OF",
              "traceID": "0",
              "spanID": "0"
            }
          ],
```

**Comment by tiffon** [comment]
I've been running the latest UI with a prior all-in-one and haven't noticed the issue. I'll confirm, though.

**Comment by yurishkuro** [comment]
I'm pretty sure it's an issue on the server, when I use memory store I see it getting spans with above reference (traceID==0, invalid). I'm still looking where exactly it's being added, by the client or the server enrichment.

**Comment by yurishkuro** [comment]
Confirmed that the issue is in the Go client (https://github.com/jaegertracing/jaeger-client-go/issues/242) that sends a bad reference `{"refType":"CHILD_OF","traceIdLow":0,"traceIdHigh":0,"spanId":0}` when baggage is provided externally to the root span.

**Comment by tiffon** [comment]
Is there a change necessary in the UI?

**Comment by yurishkuro** [comment]
no, just the backend - https://github.com/jaegertracing/jaeger/pull/614
