### ISSUE TITLE
[Feature]: copy log entry VALUE as is

### ISSUE THREAD

**Issue by neopaf** [jaegertracing/jaeger-ui#1503]
### Requirement

As a Jaeger UI user I want to be able to copy information from a log entry, from one of keys. Just value, nothing else.

### Problem

Currently we have `Copy JSON` button that copies one key from log entry like this:
```json
{
  "key": "key1",
  "type": "string",
  "value": "{\n  \"eventItem\": [{\n    \"UsageEventItem\": {\n      \"itemTime\": \"2023-05-31T10:22:58Z\",\n      \"usage\": {\n        ..."
```

While we need the content of value only.
Value is long and to just select and copy -> inconvenient.

### Proposal

Please add `Copy value` somewhere icon next to `Copy JSON` that would copy only value, in my case:
```json
{
  "eventItem": [{
    "UsageEventItem": {
      "itemTime": "2023-05-31T10:22:58Z",
      "usage": {
```

**Comment by yurishkuro** [comment]
Original Copy JSON was added in #292 / #312.

**Comment by neopaf** [comment]
@yurishkuro Yuri, my deep respect for this. 
Karma += 1E9!
