### ISSUE TITLE
[Feature]: Replace Copy icons with text buttons

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1506]
In #1505 we added a second copy icon to allow copying tag value, not always full JSON.

<img width="128" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/3523016/30dbf3f6-7421-49c7-9e86-ea4cb452742d">

It would increase usability if instead of the icons we used plain text buttons "Copy" and "JSON".

**Comment by eKeiran** [comment]
I can help with this if you'd like!

**Comment by yurishkuro** [comment]
PRs are welcome

**Comment by ArchitGajjar** [comment]
@yurishkuro can you please assign this to me, I would like to work on this. Thank you!

**Comment by eKeiran** [comment]
> @yurishkuro can you please assign this to me, I would like to work on this. Thank you!

hii I'm already working on this, you can find another issue. thanks!

**Comment by kirtanchandak** [comment]
Hey @eKeiran are you still working, can I take this issue?

**Comment by kirtanchandak** [comment]
@yurishkuro how can I start working on this issue?

**Comment by Player256** [comment]
![Jaeger UI - Brave 03-07-2023 20_09_10](https://github.com/jaegertracing/jaeger-ui/assets/92082372/b28ad3b3-7e81-463c-b6a7-55ff36e11f36)
@yurishkuro like this?

**Comment by Player256** [comment]
![Jaeger UI - Brave 03-07-2023 20_11_37](https://github.com/jaegertracing/jaeger-ui/assets/92082372/ccaf0b04-4895-4411-b37d-decbbc553045)
@yurishkuro like this?
