### ISSUE TITLE
Explain time zone of the lookback parameter

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#154]
Moved from https://github.com/jaegertracing/jaeger/issues/372

When "Custom Time Range" is specified, it would be good to show in which time zone the entered values are interpreted, either via `(?)` icon or explicitly "Start Time (TZ=New York [UTC-0500])".

![image](https://user-images.githubusercontent.com/3523016/34322144-83d71b34-e7ed-11e7-9eab-9225803d5e84.png)

**Comment by tiffon** [comment]
Sounds good.

Is `UTC-0500` always the relevant time-zone?

Also, as a bit of an aside, I'll add a note to the "Tags" info tooltip noting only exact matches are supported.

**Comment by black-adder** [comment]
Can you identify the timezone from the browser so that's it's always relevant to the user?

**Comment by tiffon** [comment]
Yes, we can get the timezone the browser is using, but, what timezone does the query-service generally interpret the date/time as?

**Comment by yurishkuro** [comment]
query-service doesn't interpret it, because UI is passing a Unix timestamp, which is relative to an absolute point in time, midnight of Jan 1 1970 in UTC time.

**Comment by tiffon** [comment]
Got it. Yes, I can add a note stating the time-values being entered are in local timezone of the browser and will be converted to UTC when sent to the server.

**Comment by yurishkuro** [comment]
"local" is good, but actually showing what it is is even better.

**Comment by tiffon** [comment]
@yurishkuro I agree, 100%.
