### ISSUE TITLE
[Bug]: Negative Self time in Trace Statistics view

### ISSUE THREAD

**Issue by TheOxFromOutOfTheBox** [jaegertracing/jaeger-ui#1592]
### What happened?

I have a sample C++ program where in  I have a main span that lasts for 10 seconds.
Span 1 - 0-10 seconds
Now I have 5 children of Span 1
Span 2-6 - 2-8 seconds (duration of 6 seconds)

So, actual self time should be 4 seconds, however I get a self time of -14 seconds.

### Steps to reproduce

Create 1 span with 4-5 child spans with each having a duration just smaller than the parent span.

### Expected behavior

Self time should be positive, however it is not.

### Jaeger backend version

1.45

### SDK

OpenTelemetry C++ SDK

### Pipeline

Otel SDK -> Otel Collector -> Jaeger Collector & Query -> Cassandra DB

### Storage backend

Cassandra v4

### Operating system

Windows

### Deployment model

binaries on bare metal

**Comment by yurishkuro** [comment]
moving to UI repo

**Comment by yurishkuro** [comment]
This probably requires some tweak to the algorithm that may be too simplistic right now. This also overlaps with the Critical Path work #1288 by @GLVSKiriti

**Comment by GLVSKiriti** [comment]
@yurishkuro Please clarify this doubt Can a `CHiILD_OF` type span overflow from its parent span?

**Comment by yurishkuro** [comment]
what do you mean by overflow - end later than parent? Yes it can.

**Comment by GLVSKiriti** [comment]
> what do you mean by overflow - end later than parent? Yes it can.

Then what is difference between follow_from and child_of

like generally child_of span for sync process and follow_from span for async process
if parent not waits for child_of span to complete then how it is different from follow_from

**Comment by yurishkuro** [comment]
Parent is expected to wait for child to complete, but the finish time of the span is not necessarily when the response was sent to the parent. I've seen in Java instrumentation children spans finishing significantly later due to thread suspension, even though the successful response was already sent to the parent. There are also cases when parent times out waiting on a child.

However, these are usually cases with _remote child_. The relationship between parent server-span and children client-spans is more robust.

**Comment by GLVSKiriti** [comment]
What is selfTime in this cases.
(1.) child span ends later
![a1](https://github.com/jaegertracing/jaeger-ui/assets/116095646/bb724ad8-76b7-45c9-ab26-5002541180ef)
Here is selfTime of A = 2-1 = 1 and selfTime of B = 11-2 = 9
(2.) child starts later
![a2](https://github.com/jaegertracing/jaeger-ui/assets/116095646/2c5e08ab-6552-4024-8a0f-8daa3a1d344e)
Here selfTime of A = 10-1 =9 and selfTime of B = 21-11 = 10

Is this correct??

**Comment by yurishkuro** [comment]
yes, assuming B is child-of span. If it's follows-from then it should have no impact on parent's span
