### ISSUE TITLE
Build does not work on Windows

### ISSUE THREAD

**Issue by anshgoyalevil** [jaegertracing/jaeger-ui#1603]
### What happened?

- Bug: Currently, due to limited maintainer's support for windows os, there are a few glitches inside the package.json due to which the development installation of jaeger UI fails.
- Typo: The readme.md file suggests changing the ```proxyConfig.target``` inside the ```package.json``` file, though, it needs to be changed inside the ```vite.config.ts```.

### Steps to reproduce

1. git clone the project into a Windows OS
2. run ```yarn```
3. it would show an error after the installation of the required packages. The error says ```$npm_execpath' is not recognized as an internal or external command```

### Expected behavior

There should be a ```Troubleshooting``` section inside the readme.md (or any other place) file which could answer the possible fix for such issues.

For example, the issue above can be resolved by manually changing the ```$npm_execpath``` to ```\"%npm_execpath%\"```

### Relevant log output

```shell
$ lerna run --stream --sort prepublishOnly
lerna notice cli v7.1.3
lerna info versioning independent

> @jaegertracing/plexus:prepublishOnly

@jaegertracing/plexus: yarn run v1.22.4
$ $npm_execpath build
@jaegertracing/plexus: '$npm_execpath' is not recognized as an internal or external command,
@jaegertracing/plexus: operable program or batch file.
error Command failed with exit code 1.
@jaegertracing/plexus: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yurishkuro** [comment]
yes, please propose a PR

**Comment by yurishkuro** [comment]
I re-titled the issue as general "does not work on Windows", since it doesn't sound like it's just the misses in the README.

**Comment by anshgoyalevil** [comment]
@yurishkuro 
There are two approaches for helping user troubleshoot the error ```$npm_execpath' is not recognized as an internal or external command```,

- There's a package called [run-script-os](https://github.com/charlesguse/run-script-os). It selected the appropriate command based on the user's OS. For example,
```js
"scripts": {
    ...
    "test": "run-script-os",
    "test:win32": "echo 'del whatever you want in Windows 32/64'",
    "test:darwin:linux": "echo 'You can combine OS tags and rm all the things!'",
    "test:default": "echo 'This will run on any platform that does not have its own script'"
    ...
  },
```

- Another approach is to add a troubleshooting section inside the readme file. 

Though, the first approach is not helpful if we are in a CI environment because they are all the time Linux Distros.

Any suggestion would be highly appreciated 🛩️

**Comment by yurishkuro** [comment]
This PR #1611 should take care of `$npm_execpath' is not recognized`.

I believe another similar issue is the use of `$NODE_ENV`,

**Comment by yurishkuro** [comment]
> Another approach is to add a troubleshooting section inside the readme file.

What specifically are you suggesting to add?

**Comment by yurishkuro** [comment]
fwiw, seems like using `cross-env` and `cross-var` modules to set and read env variables in npm scripts can take care of the `$NODE_ENV` issue as well.

**Comment by anshgoyalevil** [comment]
> > Another approach is to add a troubleshooting section inside the readme file.
> 
> What specifically are you suggesting to add?

That section doesn't need to be explicitly added for this issue, but having a troubleshooting guide could suggest other contributors add answers to some most common problems which they were able to solve.

It can be a different section with h3 ``` Troubleshooting Local Dev Setup``` or a whole different readme file.

Seeing its future scope, it would be a developer overhead to maintain such a troubleshooting section or guide with the rapid code changes. So, in short, We can ignore that for now

**Comment by anshgoyalevil** [comment]
> fwiw, seems like using `cross-env` and `cross-var` modules to set and read env variables in npm scripts can take care of the `$NODE_ENV` issue as well.

Valid. Should we go ahead and make the changes? AFAIK it won't break any existing functionality.

**Comment by anshgoyalevil** [comment]
But again, as I am seeing, the whole project is built around Linux OS.

The best thing, for now, would be to explicitly ask users to use Linux Dev Environment.

**Comment by yurishkuro** [comment]
Feel free to propose a PR with readme changes. As I understand, Win10 now allows running bash/linux without dual booting.

**Comment by yurishkuro** [comment]
> It can be a different section with h3 Troubleshooting Local Dev Setup or a whole different readme file.

I still don't see what would be IN that section. What troubleshooting steps do you have in mind that would make it work on Win?

**Comment by anshgoyalevil** [comment]
> > It can be a different section with h3 Troubleshooting Local Dev Setup or a whole different readme file.
> 
> I still don't see what would be IN that section. What troubleshooting steps do you have in mind that would make it work on Win?

To be more precise, it would include:

-------------------

### Using Windows OS for Development?

While we don't natively support Windows OS for running the Jaeger UI Dev Environment, you can use WSL to run it.

Here are some steps to follow:
1. Install WSL: https://learn.microsoft.com/en-us/windows/wsl/install
2. Install Node.JS: https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl
3. Connect WSL Environment with VSCode: https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-visual-studio-code
4. Use the WSL Terminal inside VSCode and follow the jaeger UI installation steps as described above.

**Comment by anshgoyalevil** [comment]
I have manually tested running Jaeger UI WSL using the official and great Microsoft Guides. With Docker Desktop running the query service.

**Comment by yurishkuro** [comment]
sgtm, please create a PR
