### ISSUE TITLE
[Feature]: Dockerise the App

### ISSUE THREAD

**Issue by punithnayak** [jaegertracing/jaeger-ui#1610]
### Requirement

Making the app run in a docker container

### Problem

Contributors are facing challenges while setting up the development environment for the application. The current process involves multiple manual steps, which leads to inconsistent configurations and makes it difficult for new contributors to onboard smoothly

### Proposal

Dockerfile Creation: We will create a Dockerfile to define the application's environment, including its base image, required dependencies, and any configuration settings.
Docker Compose (Optional): To simplify local development setup and orchestrate multiple services, we can provide a Docker Compose file.
Documentation Updates: We will update the project's README and contribution guidelines to include Docker-related instructions for setting up the development environment.

**Comment by yurishkuro** [comment]
> Contributors are facing challenges while setting up the development environment for the application. 

If you have a concrete issue, please describe it, rather than making this vague claim.

**Comment by punithnayak** [comment]
So yesterday in could execute and start the server properly
and now i am getting this warning
Desktop/jaeger-ui$ yarn start
`
Internal Error: jaeger-ui-monorepo@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:435:5145)
    at kf.getCandidates (/home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:391:1264)
    at /home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:439:8033
    at df (/home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:390:11070)
    at ge (/home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:390:10398)
    at async /home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:439:8545
    at async ti.startProgressPromise (/home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:390:47579)
    at async je.resolveEverything (/home/punith/.cache/node/corepack/yarn/3.6.1/yarn.js:439:6573)
punith@punith-VivoBook-ASUSLaptop-X515DA-M515DA:~/Desktop/jaeger-ui$ `

followed it and executed `yan install` and then `yarn start`
Result :
![image](https://github.com/jaegertracing/jaeger-ui/assets/110713318/4ad62af2-ba8c-420f-b6fc-8cfa28c74684)
![image](https://github.com/jaegertracing/jaeger-ui/assets/110713318/2474bc73-cdd7-4cfc-b952-ec73fd6d2a46)

**Comment by punithnayak** [comment]
And one more think I remember you saying the UI doesn't  function on windows properly so don't you think it docker solves all of it.
I am new to this org ..I want to apologize in advance if i am not making any sense

**Comment by yurishkuro** [comment]
No need to apologize, but the best way to reach a result is to state a problem you have and then discuss how it can be solved.

Not all problems are worth solving either. We may have an issue with building on Windows. But it is not difficult these days to have access to a Linux-like environment, including by running a Docker image. I wouldn't want to invest a lot of time in solving that problem, especially by disrupting the existing build-on-linux process and making it more cumbersome.

Having said that, from what I know of NPM ecosystem, there's no reason why it shouldn't work on Windows. It's likely that our build process just needs small tweaks to make it work, not a complete redesign via Docker.

**Comment by yurishkuro** [comment]
BTW, if the essence of your issue is "cannot build in Windows", then please close this ticket as a duplicate of #1603.

**Comment by punithnayak** [comment]
OK
