### ISSUE TITLE
[deps] Help with upgrading eslint-plugin-import

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1613]
@dependabot tried to upgrade https://github.com/jaegertracing/jaeger-ui/pull/1609 but it broke the CI, probably requires some minor code changes to satisfy the new linter version

**Comment by sambhavgupta0705** [comment]
@yurishkuro I would like to resolve this issue 😄

**Comment by krishnasvp** [comment]
@Yushmanth-reddy I guess this can be combined with #1608 as they both deal with eslint stuff. Would love to know your opinion on the same @yurishkuro :)

**Comment by Kavinjsir** [comment]
Hey @yurishkuro @krishnasvp I'd like to join the jaeger community with contributions.
Trying to initialize a PR https://github.com/jaegertracing/jaeger-ui/pull/1652 for this issue.
Please let me know if I can make it properly, thx!
