### ISSUE TITLE
Operation name dropdown doesn't populate if service name contains "/"

### ISSUE THREAD

**Issue by wkiser** [jaegertracing/jaeger-ui#163]
**Description**
Operation name dropdown does not populate when service name contains forward slashes.

**Steps to reproduce the issue:**
1. Run [all in one jaeger docker image](https://jaeger.readthedocs.io/en/latest/getting_started/)
2. Execute [this gist](https://gist.github.com/wkiser/415ffdce73c99a45cc6b66ae8db0b013), which is the example code from [jaeger-client-python](https://github.com/jaegertracing/jaeger-client-python) but with the service name modified.
3. Navigate to localhost:16686. Select "your/app/name" from the service dropdown. See that the only option in the operation name dropdown is "all"

**Describe the results you received:**
Operation name dropdown only contains the "all" element

**Describe the results you expected:**
Operation name dropdown should include all operations. In the example above I would expect to see the elements: "ChildSpan", "TestSpan"

**Comment by tiffon** [comment]
@wkiser Thanks for filing this. This should be resolved on master, but I don't think it's released yet.

@yurishkuro When will #140 (fixed #138) be going out?

**Comment by tiffon** [comment]
Duplicate of #138.

**Comment by wkiser** [comment]
@tiffon, thanks! did not see the duplicate issue.
