### ISSUE TITLE
Use Ant Design instead of Semantic UI

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#164]
Switch to [Ant Design UI Components](https://ant.design/docs/react/introduce).

**Comment by NeoCN** [comment]
the reason to switch?

**Comment by tiffon** [comment]
I'd say Ant Design has a brighter future. They're doing a much better job of staying on top of GitHub issues and PRs; unlike semantic UI, Ant is intended to be a React UI library from the start; and we've had some good experiences using it with other projects. Also, so far it's easier to customize Ant Design's styling.

**Comment by Dieterbe** [comment]
hi @tiffon i upgraded to 1.2.0 and the new UI looks slick!

**Comment by tiffon** [comment]
@Dieterbe Hey, thanks! :+1:
