### ISSUE TITLE
[Bug]: Change the tooltip position of Copy value & json

### ISSUE THREAD

**Issue by anikdhabal** [jaegertracing/jaeger-ui#1649]
### What happened?

After hovering over the 'Copy JSON' button, I am unable to access the 'Copy Value' button. The tooltip of the 'Copy JSON' button is blocking the 'Copy Value' button.

### Steps to reproduce

1.Hover over the copy json button

### Expected behavior

It would be better if the tooltip were positioned at the top or if the value of mouseLeaveDelay is 0.

### Screenshot

![Screenshot 2023-08-09 023328](https://github.com/jaegertracing/jaeger-ui/assets/81948346/eada710f-d46e-4827-939f-dd078bf97bdf)

**Comment by yurishkuro** [comment]
yeah, I also found it annoying. You can still just move off the right button and the left one becomes visible, but if it's an easy fix then we should fix it.

**Comment by anikdhabal** [comment]
> yeah, I also found it annoying. You can still just move off the right button and the left one becomes visible, but if it's an easy fix then we should fix it.

Yes, I will create a Pr then.

**Comment by sivasathyaseeelan** [comment]
Hi @yurishkuro, I think in
```typescript

<Tooltip
        arrowPointAtCenter
        mouseLeaveDelay={0.1}
        onVisibleChange={this.handleTooltipVisibilityChange}
        placement={this.props.placement}
        title={this.state.hasCopied ? 'Copied' : this.props.tooltipTitle}
      >

```
mouseLeaveDelay={0} works.





with mouseLeaveDelay={0.1}

https://github.com/jaegertracing/jaeger-ui/assets/95441117/feea4d4b-e89c-49bf-95e8-f8d3c3e04615





with mouseLeaveDelay={0}

https://github.com/jaegertracing/jaeger-ui/assets/95441117/f2962cfd-e49f-4f62-aecb-c9221c8ad461



can I go and create PR @yurishkuro ?
