### ISSUE TITLE
Make help popup on the Search input field less intrusive

### ISSUE THREAD

**Issue by anikdhabal** [jaegertracing/jaeger-ui#1651]
### What happened?

It's quite frustrating to see the tooltip every time when hovering over input fields; sometimes, they remain stuck on the page for an extended period of time.

### Steps to reproduce

1.Hover over the page search input field.

### Expected behavior

It would be better to have a specific button either inside or outside the input field instead of the whole input field. Clicking or hovering over that button would then trigger a popover to open, providing the information.

eg:
Just like this.
![Screenshot 2023-08-09 053015](https://github.com/jaegertracing/jaeger-ui/assets/81948346/697140f2-6089-4ff7-a674-a79e06431fee)
Or here
![Screenshot 2023-08-09 054828](https://github.com/jaegertracing/jaeger-ui/assets/81948346/036ab8e0-01ff-4b8b-a288-02a303adc1be)

### Screenshot

![Screenshot 2023-08-09 054550](https://github.com/jaegertracing/jaeger-ui/assets/81948346/202f5f9f-6922-478c-9a24-ef8389a8d52b)

**Comment by yurishkuro** [comment]
I am trying this in the main branch and not getting any tooltip popup.

**Comment by anikdhabal** [comment]
> I am trying this in the main branch and not getting any tooltip popup.

Don't Know why, but I am getting it every time in the UI.

**Comment by yurishkuro** [comment]
I can see it now too, not sure why it wasn't working on my other laptop. Do you have a proposal what to replace it with? A visual mock up would be helpful.

**Comment by anikdhabal** [comment]
> I can see it now too, not sure why it wasn't working on my other laptop. Do you have a proposal what to replace it with? A visual mock up would be helpful.

@yurishkuro I've added the expected behavior. Can we it like that?

**Comment by yurishkuro** [comment]
I don't follow.

**Comment by anikdhabal** [comment]
> I don't follow.

Instead of hover if the toot tip is appeared on focusing on the input, then it would be better. And we can make it clickable to remove. Means after clicking, it will automatically remove from the screen.

**Comment by yurishkuro** [comment]
How would it make it less frustrating / intrusive? I thought you were talking about adding something like a (?) button

**Comment by anikdhabal** [comment]
> How would it make it less frustrating / intrusive? I thought you were talking about adding something like a (?) button

Anything else would you like to add to fix it?

**Comment by anikdhabal** [comment]
> How would it make it less frustrating / intrusive? I thought you were talking about adding something like a (?) button

I've two visual representation-
![Screenshot 2023-08-14 014824](https://github.com/jaegertracing/jaeger-ui/assets/81948346/24e170db-61a3-4e8d-a862-796fbfbe3c4f)
It Appear on focus not when hovering.
![Screenshot 2023-08-14 022158](https://github.com/jaegertracing/jaeger-ui/assets/81948346/962bd4d7-7907-48eb-b106-2395fd700c6a)
Add a button.
@yurishkuro

**Comment by anikdhabal** [comment]
Or last option is to reduce the mouseLeaveDelay to 0

**Comment by anikdhabal** [comment]
@yurishkuro This is proposal for this issue. Do you have any additional idea to fix this issue?

**Comment by yurishkuro** [comment]
button with question marks sounds good. Only it would be better to have it styled the same as the question mark in the Search panel.

**Comment by anikdhabal** [comment]
@anikdhabal

**Comment by anikdhabal** [comment]
fixed with #1685
