### ISSUE TITLE
[Bug]: can not show 50000+ spans

### ISSUE THREAD

**Issue by Liubey** [jaegertracing/jaeger-ui#1663]
### What happened?

I got a trace that include 120000 spans.
But In query result, I got:
![image](https://github.com/jaegertracing/jaeger-ui/assets/5568302/ab96361b-403c-466e-959d-eaa0b0403ffe)

And, When I click for details, I got an warning:
![image](https://github.com/jaegertracing/jaeger-ui/assets/5568302/6f3e4948-fa70-4269-9a8e-b433ebf06891)
But in fact, the span have storaged in ElasticSearch.

### Steps to reproduce

TBD

### Expected behavior

Is there any limit for the result page?

### Jaeger backend version

lastest

### Stogage backend

AWS ElasticSearch(ElasticSearch 7.9)

**Comment by TheOxFromOutOfTheBox** [comment]
I faced a similar issue but with having no more than 10000 spans...

Not sure if its an optimal solution,
but I changed elasticsearch settings to return 
` "index.max_result_window":50000`
and on starting jaeger set an env variable
`--es.max-doc-count=50000`
to get 50k spans in a trace.

**Comment by Liubey** [comment]
@TheOxFromOutOfTheBox whoa!Thanks for you comments.
Maybe your solution is ok.I find [the parameter on this](https://www.jaegertracing.io/docs/1.47/cli/#jaeger-query).

**Comment by Liubey** [comment]
But I still confused about the size of 50000.

**Comment by TheOxFromOutOfTheBox** [comment]
@Liubey that was just an example...you can set the limit to what you want, not sure what the ceiling is.

**Comment by Liubey** [comment]
@TheOxFromOutOfTheBox I know that. I mean the number 50000 maybe limit by jaeger ui. But I can not read the node.js code.

**Comment by yurishkuro** [comment]
or it could be the limit of documents per response in AWS ES cluster

**Comment by Liubey** [comment]
@yurishkuro No. 10000 is the limit of per request.

**Comment by Liubey** [comment]
no way to go.
