### ISSUE TITLE
Trace - Indent guides in span-name column to indicate span ancestry

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#172]
>It may be helpful to test some of these designs with applications that have many internal spans. The hot rod application doesn't have too many levels of indentation and uses several different "application tracers" resulting in spans that are more visually legible. Here is a short segment from a trace in our infra::
>
>![image](https://user-images.githubusercontent.com/1816394/35171913-6ceccde6-fd33-11e7-8e73-0b7e8861c73a.png)
>
>Since everything is in the same service and there are several levels of indentation, it is very hard to see what elements are children of the others.
>
>A couple suggestions:
>
>1. Add guidelines down each indentation level like code editors do for whitespace
>![image](https://user-images.githubusercontent.com/1816394/35171967-aaee62bc-fd33-11e7-8408-7106592dcdf9.png)
>
>2. When a parent is hovered, every element that is a child of that element should have some sort of hover state. At the very least, the first and last child should have some marker. I would suggest just extending   that hover state down to cover its children (mockup based on posted screenshots):
>![image](https://user-images.githubusercontent.com/1816394/35172062-302f8532-fd34-11e7-9414-7110930f9d9a.png)
>
>Aside from that, the screenshots posted here look great.

The approach that initially comes to mind is to have low-contrast, persistent indent guides visible at all times and to highlight the relevant indent guides on hover (e.g. ancestors of the span the mouse is over). In the screenshot below, the all of the indent guides of the `return` statement and subsequent lines would still be visible, but they would be the low-contrast variation instead of emphasized with orange.

<img width="368" alt="screen shot 2018-01-21 at 3 37 38 pm" src="https://user-images.githubusercontent.com/2304337/35198736-5d498a48-fec1-11e7-8ac3-a858598b2799.png">

**Comment by black-adder** [comment]
+1 for guidelines

**Comment by tiffon** [comment]
Fixed in #297.
