### ISSUE TITLE
[Bug]: UI is escaping = in tag search

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-ui#1733]
### What happened?

Searching for tags that contain `=` does not work.

E.g. `http.url=http://0.0.0.0:8081/customer?customer=567` is escaped to http://localhost:16686/api/traces?end=1692956466480000&limit=20&lookback=1h&maxDuration&minDuration&service=frontend&start=1692952866480000&tags=%7B%22http.url%22%3A%22http%3A%2F%2F0.0.0.0%3A8081%2Fcustomer%3Fcustomer567%22%7D 

```
end: 1692956466480000
limit: 20
lookback: 1h
maxDuration: 
minDuration: 
service: frontend
start: 1692952866480000
tags: {"http.url":"http://0.0.0.0:8081/customer?customer567"}
```

![Screenshot of Jaeger UI (7)](https://github.com/jaegertracing/jaeger-ui/assets/5618424/44a60fa8-beb6-4f0e-8a13-8a7460994243)

### Steps to reproduce

1. run Jaeger all-in-one
2. run hotrod
3. create traces
4. search for `http.url=http://0.0.0.0:8081/customer?customer=567` in frontend service

### Expected behavior

Find trace with `http.url=http://0.0.0.0:8081/customer?customer=567`

### Jaeger backend version

1.48.0

### Stogage backend

all-in-one, but it does not matter, UI is escaping `=`

**Comment by yurishkuro** [comment]
Tag query:
  * `url=/customer?customer=123` - does not find a trace
  * `url="/customer?customer=123"` - does find a trace

I think the expectation of the logftm syntax is that the rhs should be in quotes if it contains special characters, even though the tool tip only says "whitespace". 

So (a) I don't think this is a bug, and (b) the tool tip should be changed 
```diff
- Values containing whitespace should be enclosed in quotes
+ Values containing whitespace or '=' should be enclosed in quotes
```

**Comment by yurishkuro** [comment]
and a bonus: for a string like `url=/customer?customer=123` display an error because `=` is used twice
