### ISSUE TITLE
[deps] Replace the use of moment.js with actively maintained library

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1736]
Moment.js is "a legacy project in maintenance mode", according to its official website https://momentjs.com/docs/#/-project-status/.

* [ ] do an inventory of features / APIs we are using from moment.js
* [ ] do analysis which replacement is most suitable (the fewer dependencies the better)
* [ ] make the corresponding changes. It's probably worth consolidating all usage of any new 3rd party library into `utils/date.tsx`

```
$ grx "from 'moment'" packages/jaeger-ui/src
packages/jaeger-ui/src/utils/date.tsx:15:import moment, { unitOfTime } from 'moment';
packages/jaeger-ui/src/components/common/RelativeDate.tsx:15:import moment from 'moment';
packages/jaeger-ui/src/components/TracePage/TraceSpanView/index.tsx:17:import moment from 'moment';
packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.jsx:16:import moment from 'moment';
packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.tsx:21:import moment from 'moment';
packages/jaeger-ui/src/components/SearchTracePage/SearchForm.jsx:20:import moment from 'moment';
packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js:20:import moment from 'moment';
packages/jaeger-ui/src/api/jaeger.js:16:import moment from 'moment';

$ grx "from 'moment'" packages/jaeger-ui/src packages/plexus/src
packages/jaeger-ui/src/utils/date.tsx:15:import moment, { unitOfTime } from 'moment';
packages/jaeger-ui/src/components/common/RelativeDate.tsx:15:import moment from 'moment';
packages/jaeger-ui/src/components/TracePage/TraceSpanView/index.tsx:17:import moment from 'moment';
packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.jsx:16:import moment from 'moment';
packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.tsx:21:import moment from 'moment';
packages/jaeger-ui/src/components/SearchTracePage/SearchForm.jsx:20:import moment from 'moment';
packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js:20:import moment from 'moment';
packages/jaeger-ui/src/api/jaeger.js:16:import moment from 'moment';
```

**Comment by prathamesh-mutkure** [comment]
I did some research around this and two of the most popular date libraries are [`date-fns`](https://www.npmjs.com/package/date-fns) and [`dayjs`](https://www.npmjs.com/package/dayjs)

`date-fns`
- Actively maintained (> 32k stars)
- Rich functionality 

`dayjs`
- Actively maintained too (44k stars)
- Similar API to `moment.js` (almost identical)
- Small bundle size (2kb)

I feel `dayjs` will be a very good choice since its API is almost the same as `moment.js` and it is much smaller in size compared to `date-fns` and `moment.js`

What do you say? I'm willing to work on this

**Comment by kumarankit999** [comment]
Can I work on this, if no one is working on this issue
