### ISSUE TITLE
[tests] Another flaky test seems to be introduced

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1747]
A couple PRs failed with a drop of code coverage, even though they did not change the code in question (e.g. one was dependencies upgrade). Codecov shows the issue in the date.tsx util file

<img width="2371" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/3523016/837612f2-1104-4b35-b556-516f6d6a7bfb">

It is possible that the function being tested executes different code paths depending on time of day or some other variable, which should really be controlled better from within the test.

**Comment by suhail34** [comment]
I would like to take this one up to work

**Comment by dhiraj0911** [comment]
I would like to work on this issue
