### ISSUE TITLE
Fails to compile on Windows: ERROR: "_tasks/clean/worker"

### ISSUE THREAD

**Issue by dhiraj0911** [jaegertracing/jaeger-ui#1760]
### What happened?

While trying to compile the jaeger-ui project on Windows, the build process encounters an error specifically at the _tasks/clean/worker step. The error is related to illegal characters in the path during the rimraf operation.

### Steps to reproduce

Clone the jaeger-ui repository to a Windows machine.
Navigate to the directory: ROOT DIR
Run the command: yarn install --frozen-lockfile

### Expected behavior

The jaeger-ui project should compile successfully without any errors.

### Relevant log output

```shell
@jaegertracing/plexus: [_tasks/clean/worker ] Error: Illegal characters in path.
...
path: 'D:\\Open Source\\jaeger-ui\\packages\\plexus\\src\\LayoutManager\\layout.worker*js*',
code: 'EINVAL'
```

### Additional context

This issue seems to be platform-specific and is encountered on the Windows 11

### Operating system

64-bit operating system, x64-based processor Windows 11 

```shell
Directly from the cloned repository.
```

**Comment by yurishkuro** [comment]
We do not support building on Windows natively. See https://github.com/jaegertracing/jaeger-ui#running-on-windows-os
