### ISSUE TITLE
[bug] Unexpected error in Critical Path computation

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1766]
See https://github.com/jaegertracing/jaeger-ui/pull/1765#issuecomment-1708467413

cc @GLVSKiriti

**Comment by joe-elliott** [comment]
Just saw this issue while cutting v1.33.0.

**Comment by yurishkuro** [comment]
yeah, I think we need a try/catch around CP function invocation so that if it bombs we just don't display CP but the UI still works. I should be able to patch it tonight.

**Comment by GLVSKiriti** [comment]
@yurishkuro can't we also close this issue through PR's #1780 and #1785

**Comment by yurishkuro** [comment]
thanks
