### ISSUE TITLE
[Bug]: Can not use search in service or Operation

### ISSUE THREAD

**Issue by easayliu** [jaegertracing/jaeger-ui#1784]
### What happened?

i get the new ui with 1.33, i can not search anything at service or Operation.

roll back 1.32,it works.

### Steps to reproduce

just input anything  at service or Operation,you will find without anything input

### Expected behavior

no

### Jaeger backend version

v1.49.0

**Comment by anshgoyalevil** [comment]
@easayliu Could you please provide some steps to reproduce the issue locally? As in my local setup, it is working with v1.33 also.

**Comment by easayliu** [comment]
> @easayliu Could you please provide some steps to reproduce the issue locally? As in my local setup, it is working with v1.33 also.
<img width="413" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/54569917/e82d9c8d-9e12-4fdf-bae2-8e6bb644e36e">
I can not input anything at here.. chrome safari all get the same promble. 
I am using jaegertracing/jaeger query: 1.49

**Comment by easayliu** [comment]
![image](https://github.com/jaegertracing/jaeger-ui/assets/54569917/afbb2667-256c-4a0f-954a-6db6cbb64179)
When i used jaegertracing/jaeger-query:1.48, it works. I can input anything. But at jaegertracing/jaeger-query:1.49, it can not input anything.

**Comment by anshgoyalevil** [comment]
@yurishkuro I think this is related to https://github.com/jaegertracing/jaeger-ui/pull/1737

**Comment by anshgoyalevil** [comment]
@yurishkuro I think this is related to https://github.com/jaegertracing/jaeger-ui/pull/1737

**Comment by yurishkuro** [comment]
cc @prathamesh-mutkure

**Comment by prathamesh-mutkure** [comment]
Hi @easayliu @yurishkuro, I looked up Ant Design's docs and unlike previous implementation, searching is not enabled by default, We need to pass a prop to make it searchable, essentially making it a ComboBox.

I'll submit a PR to fix this issue

Also I'll find a way to of Select field being searchable by default, is this okay?

**Comment by yurishkuro** [comment]
@prathamesh-mutkure could we also add a unit test for type-to-search, so that we don't get such regressions in the future?
