### ISSUE TITLE
[deps] Upgrade react-json-view-lite

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1797]
PR #1774 is failing because of breaking changes in 1.0, needs a fix.

This PR in the backend may be helpful for testing JSON rendering: https://github.com/jaegertracing/jaeger/pull/4765

**Comment by anurag-dhamala** [comment]
I'd like to work on this issue. Thanks.

**Comment by duckling69** [comment]
@yurishkuro I'd like to take this issue
