### ISSUE TITLE
No Service Dependencies found with Elasticsearch 5.6.x as storage backend

### ISSUE THREAD

**Issue by cinhtau** [jaegertracing/jaeger-ui#185]
Hello Jaegers,

I'am using Jaegertracing with Elasticsearch v5.6.4 as storage backend. If I run the HotRod example against the Docker All in One Solution , the dependencies are nicely displayed. However if I switch it to my running instance with Elasticsearch it does display all information except the dependencies. Is that UI feature supported with Elasticsearch as storage? 

I can see that Jaeger has created following indices:

```
health status index                     uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   jaeger-service-2018-02-02 h8a6tTYIQpuiAggw__b8BQ   1   1         12            9     15.3kb          7.6kb
green  open   jaeger-service-2018-02-06 csLs_IFrS2SLVT_LzgrdIg   1   1         26            1     51.7kb         24.3kb
green  open   jaeger-service-2018-02-07 cavH_ePcQ6GhhBWKF7uCOQ   1   1         45           23     34.9kb         17.4kb
green  open   jaeger-span-2018-02-02    xfMCh9eJRrWg7DsTbgb5Dg   1   1       2797            0    476.9kb        238.4kb
green  open   jaeger-span-2018-02-06    SFKXix1xSwuSC8dcJ98vTg   1   1      11505            0      1.4mb        765.9kb
green  open   jaeger-span-2018-02-07    75kWkwPOSYi3UKW-AOQCtQ   1   1      12510            0      1.7mb        897.4kb
```

Thanks in advance.

**Comment by objectiser** [comment]
When using the all-in-one image, the dependencies are derived in memory. When you change to use a production configuration with persistent storage, you currently need to setup a separate spark job - see https://github.com/jaegertracing/spark-dependencies.

**Comment by yurishkuro** [comment]
@cinhtau do you have suggestions on how this could be made more explicit?

* we can call this out in the documentation / tutorials
* we could disable the Dependencies tab by default

**Comment by cinhtau** [comment]
Hi Jaegers, thank you for helpful answers. You can find the outcome in my current [blog draft](http://cinhtau-website.s3-website-us-east-1.amazonaws.com/2018/02/02/jaegertracing-with-elasticsearch/#dependencies), if you are interested. `spark-dependencies` also works great with Elasticsearch. 

@yurishkuro I wouldn't hide this amazing depency feature by default. As I presented the hotrod example in front of our development teams, this was one major game changer to go for Jaegertracing. I would certainly point it out in the documentation. I have found that is documented, pretty well, but I was looking in the wrong place. It is described in the jaeger/spark-dependencies site. I was looking in the UI :smile:. 

From my experience, I would recommend to place the hint in the Dependency Tab itself! One example: These dependencies are proudly generated by the jaeger/spark-dependencies. A small label or hint is enough and there is no need to hide it IMHO.

**Comment by quaff** [comment]
A help tips should present if "No service dependencies found" in "Dependencies" tab.
