### ISSUE TITLE
[Bug]: Poor choice of right-arrow icon

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1858]
In v1.48:
<img width="402" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/3523016/7be3c618-2677-4b4a-b473-3c2a41c20650">

In v1.50:
<img width="402" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/3523016/b630cb4d-a668-451e-9dd6-07e51f7fef7b">

The arrow is thinner and does not align with the text vertically.

**Comment by MeenuyD** [comment]
can you tell where i can see this

**Comment by yurishkuro** [comment]
It's in the main trace view, e.g. when you run a HotROD demo app and open one of its traces

**Comment by yurishkuro** [comment]
More concretely, you can run this example https://github.com/jaegertracing/jaeger/tree/main/examples/hotrod

**Comment by NineKama** [comment]
The arrow in v1.48 was using **IMArrowRight** from **react-icons/im**
![image](https://github.com/jaegertracing/jaeger-ui/assets/12762270/c5af7335-3fcb-4328-a1e0-adf3e6468721)

and we don't have the similar icon in **react-icons/io5** to replace https://react-icons.github.io/react-icons/icons?name=io5. We are using: 
![image](https://github.com/jaegertracing/jaeger-ui/assets/12762270/23452e0a-f325-4589-afa4-20476c261bb2)

We can revert it but it will conflict with idea https://github.com/jaegertracing/jaeger-ui/issues/1723.

Do you have any suggestions?

**Comment by yurishkuro** [comment]
I am fine to stick with thinner arrow, it just needs to be styled to align with the center of the circle
