### ISSUE TITLE
Very slow UI responsiveness after large query set

### ISSUE THREAD

**Issue by rbtcollins** [jaegertracing/jaeger-ui#186]
After doing a large query (e.g. 2000 traces), type in the query box on the left was very slow: several seconds per character as I added a tag specifier.

**Steps to reproduce the issue:**
1. Deploy Jaeger-UI
2. Query for 2000 spans
3. Attempt to add in a tag constraint

**Describe the results you received:**

Slow behaviour of the UI

**Describe the results you expected:**

Fast behaviour: the only thing changing was the query definition, and that should not have any data dependency on the previous queries results.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (Browser, etc.):**

This was with builds from about 2 weeks back.

**Comment by tiffon** [comment]
Thanks for filing this.

We had a regression (#178). It should be resolved with this #179, which was merged a few days ago but released yesterday.

Can you confirm the update resolves this?

**Comment by rbtcollins** [comment]
Yes, it is substantially better.
