### ISSUE TITLE
[Bug]: Change twitter logo to X

### ISSUE THREAD

**Issue by singodiyashubham87** [jaegertracing/jaeger-ui#1874]
### What happened?

The logo of twitter has been changed

### Steps to reproduce

Change the logo from twitter bird to 'X'

### Expected behavior

The logo has to be of 'X'

### Screenshot

![image](https://github.com/jaegertracing/jaeger-ui/assets/93720428/697c246d-99c5-48c6-8b17-d4290138228a)

**Comment by anshgoyalevil** [comment]
I think https://github.com/jaegertracing/documentation is the repository where this issue should have been raised

**Comment by yurishkuro** [comment]
Also, I just don't care.
