### ISSUE TITLE
ci: Flaky unit test VirtualizedTraceView.test.js

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1875]
packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.test.js

An unrelated PR failed due to code coverage change in VirtualizedTraceView.tsx:
![image](https://github.com/jaegertracing/jaeger-ui/assets/3523016/5c640e9a-cd9f-46dc-93a0-fd1a170cc8e9)

The diff shows that the empty array code path was not executed - it's easy to add a test for that, but what's surprising is why it was executed before. I wonder if it's related to #1872 which was just merged.

cc @GLVSKiriti

**Comment by GLVSKiriti** [comment]
No, it is not related to the #1872 this line is not covered in tests before #1872 too.
Anyways I will add a test for that!
