### ISSUE TITLE
[Feature]: Add hover scale up animation on cards

### ISSUE THREAD

**Issue by singodiyashubham87** [jaegertracing/jaeger-ui#1876]
### Requirement

It will be better if there is scale up animation on cards

### Problem

It's not clearly highlighted that which div is being hovered upon 

![image](https://github.com/jaegertracing/jaeger-ui/assets/93720428/89be18ee-ee09-446e-8a55-f4a12ee40ff8)

### Proposal

Kindly assign me this issue

**Comment by theavitw** [comment]
Assign Me!

**Comment by GLVSKiriti** [comment]
This issue should be moved to [documentation](https://github.com/jaegertracing/documentation) repo 
not related to this repo!
