### ISSUE TITLE
[Feature]: Speed up Trace Statistics view calculation

### ISSUE THREAD

**Issue by maxgaponov** [jaegertracing/jaeger-ui#1925]
### Requirement

I would like to view Statistics for traces with a big amount of spans.

### Problem

Currently Trace Statistics view is calculating very slowly which makes it impossible to use for large traces.

**Comment by yurishkuro** [comment]
It's because the code uses linear searches all over the place, so the complexity is at least O(n^2) right now, if not worse. The solution is to build a map spanID->span once and use it in all lookups.
