### ISSUE TITLE
Format "Trace JSON"

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-ui#199]
Format "Trace JSON" output so the output is nicely readable.

**Comment by yurishkuro** [comment]
I just use a browser plugin for formatting

**Comment by tiffon** [comment]
I also use a browser plugin for this. 

https://chrome.google.com/webstore/detail/json-handle/iahnhfdhidomcpggpaimmmahffihkfnj

Also, the UI is not able to achieve this as the JSON is not presented in the UI. This falls to the query-service.

New ticket: jaegertracing/jaeger#756

**Comment by yurishkuro** [comment]
@tiffon the server side change landed, if you add `?prettyPrint=true` to the trace url the backend will format it.

**Comment by tiffon** [comment]
Is this not working?

https://github.com/jaegertracing/jaeger-ui/blob/master/src/components/TracePage/TracePageHeader.js

**Comment by tiffon** [comment]
Is this not working? Is `prertyPrint=true` the wrong flag?

https://github.com/jaegertracing/jaeger-ui/blob/master/src/components/TracePage/TracePageHeader.js#L114

**Comment by yurishkuro** [comment]
oh, damn, I missed that it was merged. Too late, 1.4.0 is out already.
