### ISSUE TITLE
 .nvmrc 

### ISSUE THREAD

**Issue by Shreya1771** [jaegertracing/jaeger-ui#201]
**Description** 
the recommended npm and Node versions should be defined in .nvmrc file but its blank .Need to define versions in file to guide newbies

**Comment by yurishkuro** [comment]
It is not blank, it says "6". Try "nvm use" in the project dir.

**Comment by tiffon** [comment]
I don't see it being blank.

https://github.com/jaegertracing/jaeger-ui/blob/master/.nvmrc

Can you elaborate?

**Comment by yurishkuro** [comment]
there was no response for 12 days, I am closing it as invalid.
