### ISSUE TITLE
Add screenshots of the UI to the README

### ISSUE THREAD

**Issue by KyleAMathews** [jaegertracing/jaeger-ui#202]
This would be helpful for people evaluating the project.

**Comment by yurishkuro** [comment]
Good suggestion. Meanwhile, you can see screenshots on the documentation site https://jaegertracing.netlify.com/docs/ and in the blog post https://medium.com/opentracing/take-opentracing-for-a-hotrod-ride-f6e3141f7941

**Comment by KyleAMathews** [comment]
Thanks!

I didn't realize there was a docs site either as http://jaegertracing.io/ points to the github repo.

**Comment by yurishkuro** [comment]
Yeah, sorry, we're planning to repoint it to the new site, but there's a bit of bureaucracy involved.

**Comment by KyleAMathews** [comment]
Cool, not a big deal :-) appreciate the pointers! Planning on adding tracing to Gatsby soon https://github.com/gatsbyjs/gatsby/pull/4785
