### ISSUE TITLE
Import only lodash submodules

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#2032]
In order to reduce the bundle size, lodash recommends importing submodules, e.g. `import _get from 'lodash/get'` instead of `import { debounce } from 'lodash'`. Most of our code is already like that, with the exception of just a handful of files:

```
$ grx lodash packages/*/src | grep -v 'lodash/'
packages/jaeger-ui/src/components/DependencyGraph/DependencyForceGraph.jsx:18:import { debounce } from 'lodash';
packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.tsx:16:import * as _ from 'lodash';
packages/jaeger-ui/src/components/TracePage/TraceStatistics/generateDropdownValue.tsx:15:import _ from 'lodash';
packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.tsx:20:import { sortBy } from 'lodash';
```

This ticket is to clean up these remaining full imports by replacing them with the needed submodule imports.

It will be interesting to see how much it would affect the bundle size:
<img width="1848" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/3523016/dfbbe701-9065-41d9-80b1-7e6f5f6374b7">

**Comment by professorabhay** [comment]
Hey, @yurishkuro! I would like to work on this.

**Comment by yurishkuro** [comment]
It's auto generated by our build, stats.html
