### ISSUE TITLE
[Feature]: Add zoom in/out controls to graphs

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#2056]
### Requirement

As a user of graph views, such as trace comparison or DDG, I want to zoom in to certain sections of the graph to see more details.

### Problem

The zoom capability is not intuitive, e.g see [this user question ](https://cloud-native.slack.com/archives/CGG7NFUJ3/p1702645103641289).

### Proposal

Add [+] / [-] buttons to the minimap (in addition to the existing Reset button)

![image](https://github.com/jaegertracing/jaeger-ui/assets/3523016/9786fef6-afda-46d3-b87a-fd0f9d1c97c2)

**Comment by Wise-Wizard** [comment]
I would like to work on this next!
