### ISSUE TITLE
[Enhancement]: `@types` packages should be all listed as dev-dependencies

### ISSUE THREAD

**Issue by EshaanAgg** [jaegertracing/jaeger-ui#2073]
### Requirement

![image](https://github.com/jaegertracing/jaeger-ui/assets/96648934/70a3613a-7ea4-4316-ab32-bfe8797c4526)
Currently, many `@types` packages have been listed as `dependencies` instead of `devDependencies`.

### Problem

It leads to their download in the production environment, which is a wastage of computation resources and build time. 

### Proposal

Move them to `devDependencies`.

**Comment by yurishkuro** [comment]
+1
