### ISSUE TITLE
[Feature]: remove the `is-promise` library

### ISSUE THREAD

**Issue by EshaanAgg** [jaegertracing/jaeger-ui#2074]
### Requirement

Currently, we are using the `is-promise` package's exported `isPromise` function in some tests to check if the returned payload is a promise. This feels very counterintuitive. 
https://github.com/jaegertracing/jaeger-ui/blob/f7db33e8ecb2e77c64ab7a84b428e8a34630c6e5/packages/jaeger-ui/src/actions/jaeger-api.test.js#L27
https://github.com/jaegertracing/jaeger-ui/blob/f7db33e8ecb2e77c64ab7a84b428e8a34630c6e5/packages/jaeger-ui/src/actions/jaeger-api.test.js#L84-L87

### Problem

Since the codebase uses TypeScript, either of the two things should happen:
- The types of the functions using this function should be updated to give us the confidence that the returned result is always a promise of the appropriate type. (And then these type assertions should be removed from the tests)
- We can make use of the `PromiseLike` type by TS.

Anyhow, I believe the use case is too trivial to add a new library. 

### Proposal
Remove the library and adopt one of the above mentioned approaches.

**Comment by yurishkuro** [comment]
+1

**Comment by shubhamku044** [comment]
Hii can I take this issue?

**Comment by ShivamMadlani** [comment]
Hey there, would like to work on this issue

**Comment by ShivamMadlani** [comment]
Im thinking of implementing a function isPromise() instead of changing every instance where the ispromise library is called as it would be better for code redability...thaughts?? @yurishkuro

**Comment by EshaanAgg** [comment]
Defeats the whole purpose of Typescript IMO. The types/return signatures of these function should give us this confidence, and not any external function like isPromise. 

If the functions do not return a Promise, but a promise-equivalent object, we can use Typescript's PromiseLike type.

**Comment by ShivamMadlani** [comment]
Alright got it...

**Comment by kumarankit999** [comment]
I would like to work on it!
