### ISSUE TITLE
Change tag search input to be more user friendly

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#21]
Currently tag query must be entered into a single textbox with `tag:value` syntax, which is not obvious and too sensitive to white space. Also doesn't seem to work for multi-tag search at all.

The suggestion is to replace a single box with "add tag query" button which adds two text boxes side by side, for tag name (can be used with auto-complete in the future) and tag value. The button allows adding more tag queries. Each pair of key-value text boxes should have a red X to remove it from the search.

**Comment by vprithvi** [comment]
Related: https://github.com/uber/jaeger/issues/139 (indexing values for autocomplete)

**Comment by tiffon** [comment]
@yurishkuro Would you say the intent of this ticket has been addressed now that the tag input on the search form handles logfmt values?

**Comment by yurishkuro** [comment]
Fixed by #147
