### ISSUE TITLE
Tag search does not support spaces in value

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-ui#210]
**Description**
If a tag value includes spaces, it cannot be searched for via the tag search bar. This happens, for example, with sql queries: `SELECT * FROM foo`.
EDIT: see minimal example below

**Steps to reproduce the issue:**
1. Insert a span with a tag that has a space in the value. 
2. Attempt to search for the tag via the search box

**Describe the results you received:**
The trace is not found

**Describe the results you expected:**
The trace should be found

**Additional information you deem important (e.g. issue happens only occasionally):**
I have tried various things such as escaping, mucking with the actual URL query paramts, etc. I was not able to get this to work

**Additional environment details (Browser, etc.):**

**Comment by nziebart** [comment]
Actually, this issue seems to be related to spaces as well. As a minimal example, searching for the tag value `foo bar` does not work. I have tried with both elasticsearch backend and the in-memory backend (from the all in one docker image).

Screenshot of tag value:
![screen shot 2018-05-08 at 11 57 22 am](https://user-images.githubusercontent.com/2740512/39777004-308b3d22-52b7-11e8-8811-ccaacad8b980.png)
It cannot be found via search:
![screen shot 2018-05-08 at 11 57 37 am](https://user-images.githubusercontent.com/2740512/39777003-30752cd0-52b7-11e8-85be-b8d3ad11dce1.png)

**Comment by tiffon** [comment]
@nziebart Thanks for filing this ticket!

So far I'm unable to reproduce the issue. I tried our cassandra backed deployment and the all-in-one Docker image (in-memory backed) with the HotROD demo. So far seems like it's working.

[In memory + HotROD demo search results](http://localhost:16686/search?limit=20&lookback=2d&maxDuration&minDuration&service=mysql&tags=%7B%22sql.query%22%3A%22SELECT%20%2A%20FROM%20customer%20WHERE%20customer_id%3D123%22%7D)

<img width="1467" alt="screen shot 2018-06-16 at 10 56 23 pm" src="https://user-images.githubusercontent.com/2304337/41504322-13acdcbc-71b9-11e8-8602-9ff26e20d044.png">

This might seem like a silly question, but was the span with the tag `test="foo bar"` from the `test` service? Searching the root service for tags on a child span from some other service has tripped me up before.

**Comment by tiffon** [comment]
@nziebart – Just checking in... Are you still seeing this issue?

**Comment by tiffon** [comment]
Closing due to inability to reproduce and lack of response from OP.
