### ISSUE TITLE
Find out and document how to debug unit tests from VSCode

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#2118]
How to run and debug unit tests is rather confusing, we need to document it better.

For example, from the command line it's possible to run a test like this:
```
$ yarn test packages/jaeger-ui/src/model/transform-trace-data.test.js
```

However, to run with debugger in VSCode we need a launch configuration, and I had trouble coming up with a generic one.

This one has file name hardcoded:
```json
        {
            "type": "node",
            "request": "launch",
            "name": "Jest: current file",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/packages/jaeger-ui/node_modules/.bin/jest",
            "args": ["src/model/transform-trace-data.test.js"],
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}/packages/jaeger-ui",
        }
```

**Comment by RISHIKESHk07** [comment]
@yurishkuro would like to help

**Comment by RISHIKESHk07** [comment]
@yurishkuro  Does this work ?
``` js
{
    "type": "node",
    "request": "launch",
    "name": "Jest: current file",
    "skipFiles": [
        "<node_internals>/**"
    ],
    "program": "${workspaceFolder}/node_modules/.bin/jest",
    "args": [
        "${relativeFile}",
        "--config",
        "jest.config.js" // this would run the jest test for current file when we launch on vscode
    ],
    "console": "integratedTerminal",
    "cwd": "${workspaceFolder}"
}
``````

**Comment by yurishkuro** [comment]
does it work for you?

**Comment by RISHIKESHk07** [comment]
i got a peer dependency conflict on npm i , 

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: jaeger-ui@1.37.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from jaeger-ui@1.37.0
npm ERR!   packages/jaeger-ui
npm ERR!     jaeger-ui@1.37.0
npm ERR!     node_modules/jaeger-ui
npm ERR!       workspace packages/jaeger-ui from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.3.0 - 16.x" from react-vis@1.11.12
npm ERR! node_modules/react-vis
npm ERR!   react-vis@"^1.7.2" from jaeger-ui@1.37.0
npm ERR!   packages/jaeger-ui
npm ERR!     jaeger-ui@1.37.0
npm ERR!     node_modules/jaeger-ui
npm ERR!       workspace packages/jaeger-ui from the root project
```

**Comment by RISHIKESHk07** [comment]
@yurishkuro should i resolve it directly , or is there any other solution for this ?

**Comment by RISHIKESHk07** [comment]
@yurishkuro I did try various changes  but it did not fix it , any suggestion where I should focus , I did see that jest is having a problem with esm modules , but in the docs i found the support for it is experimental,

**Comment by RISHIKESHk07** [comment]
@yurishkuro does this look fine  ? 
![image](https://github.com/jaegertracing/jaeger-ui/assets/117551967/79b87c07-89d0-4273-a9fd-88f0ca4cd6cc)

**Comment by yurishkuro** [comment]
(a) you have test name hardcoded, instead of using the current test file, (b) can you set breakpoints?

**Comment by RISHIKESHk07** [comment]
a) Is solved can be solved by replace the hardcoded part with {file}.
For  b) , we cannot directly set breakpoints in the launch.json  , my solution is we  can list a certain amount of breakpoints and jest takes these as input  , should this working like this or you  have something else in mind

**Comment by yurishkuro** [comment]
+1 please open a PR

**Comment by yurishkuro** [comment]
Readme or launch.example.json
