### ISSUE TITLE
[Bug]: depcheck incorrectly flags dependencies as unused

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#2132]
### What happened?
I want to see if all declared dependencies are actually used. We have `yarn depcheck` for this, but it incorrectly flags dependencies that are currently in use:
```
$ yarn depcheck
Unused devDependencies
* @types/rollup-plugin-visualizer
* @vitejs/plugin-legacy
* @vitejs/plugin-react
* rollup-plugin-visualizer
* vite-plugin-imp
```

Some of these plugins are in fact in use, they are declared in `packages/jaeger-ui/vite.config.mts`. Somehow we need to tell depcheck to ignore them. We already generate custom configs for depcheck in the `scripts/run-depcheck.sh` script, it probably needs to be extended somehow.

**Comment by prashantrewar** [comment]
hey @yurishkuro, I would like to work on this issue. Could you please guide me on this issue?

**Comment by yurishkuro** [comment]
start with `yarn depcheck` and go from there

**Comment by MeenuyD** [comment]
I am confused i have to change in scripts/run-depcheck.sh this or this packages/jaeger-ui/vite.config.mts

**Comment by yurishkuro** [comment]
@MeenuyD I don't know that the solution is. I described a problem that we want to solve, which is that depcheck incorrectly flags dependencies which are in fact being used.

**Comment by MeenuyD** [comment]
Ok

**Comment by tico88612** [comment]
@yurishkuro, Is the issue resolved? I checked the [latest build](https://github.com/jaegertracing/jaeger-ui/actions/runs/8160732437/job/22307962527#step:5:17) and my PC, and there was no depcheck issue. 

<img width="489" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/17496418/11446bf5-1f10-4e5c-adcc-dc3f48a1e8ab">

**Comment by tico88612** [comment]
Which depcheck version do you use?
```
❯ npm install -g depcheck@1.4.3


added 17 packages, removed 17 packages, and changed 111 packages in 708ms

15 packages are looking for funding
  run `npm fund` for details
❯ yarn depcheck
yarn run v1.22.19
$ ./scripts/run-depcheck.sh
Checking packages/jaeger-ui
    Unused devDependencies
    ⛔ @types/rollup-plugin-visualizer
    ⛔ @vitejs/plugin-legacy
    ⛔ @vitejs/plugin-react
    ⛔ rollup-plugin-visualizer
    ⛔ vite-plugin-imp
Checking packages/plexus
    No depcheck issue
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
❯ npm install -g depcheck@1.4.7


added 17 packages, removed 17 packages, and changed 111 packages in 676ms

15 packages are looking for funding
  run `npm fund` for details
❯ yarn depcheck
yarn run v1.22.19
$ ./scripts/run-depcheck.sh
Checking packages/jaeger-ui
    No depcheck issue
Checking packages/plexus
    No depcheck issue
✨  Done in 2.27s.
```

**Comment by yurishkuro** [comment]
I didn't realize we're running a globally installed depcheck - that's very bad, we need the builds to be reproducible, this is why we have `yarn.lock`. https://github.com/jaegertracing/jaeger-ui/blob/8fe552a89c8062661a341b79262b37d4f329154f/.github/workflows/lint-build.yml#L30

`depcheck` itself should be added as a dependency.

**Comment by tico88612** [comment]
Agree. Do we lock `depcheck` to the latest version (1.4.7)?

**Comment by yurishkuro** [comment]
If we add to `github/workflows/lint-build.yml` then dependabot probably won't be able to upgrade it, so it's not ideal. It's better to keep all deps in package.json. Latest version is fine.
