### ISSUE TITLE
"Import JSON file" option in Jaeger UI

### ISSUE THREAD

**Issue by sagrath23** [jaegertracing/jaeger-ui#214]
**Description**
Hi, 
¿Is there any plans to add an "Import JSON" Option to Jaeger-UI?. 

In my current job, we're developing a huge platform from utilities companies, and i'm making some changes in Jaeger-UI, in order to add an option that allow the upload of a JSON file (exported from another Jaeger-UI instance or only spans data). In my work, i'm using IndexedDB Storage to store the parsed JSON (exported from another Jaeger-UI) and displayed when that trace is requested. Also, i'm adding a component that allow to upload an un-parsed JSON file (this file only contains spans info), and send it to jaeger's collector, and redirect to that specific trace when upload are finished.

This changes can be evaluated, and eventually included in jaeger-ui codebase?

**Comment by yurishkuro** [comment]
I think uploading JSON would be a useful feature. I am not sure how it's related to storing in indexedDb, that sounds like a completely different thing.

**Comment by sagrath23** [comment]
@yurishkuro the main idea behind store exported trace JSON in IndexedDB storage is purely to detatch Jaeger-UI from Jaeger's Collector & Jaeger's Query components (thinking in a Jaeger-UI back-endless implementation, for visualization purprose only). I will keep working on the upload JSON feature a few more. Thank you so much.

**Comment by tiffon** [comment]
@sagrath23 Thanks for creating this ticket!

If I follow correctly, there are three features described:

1. Loading a local file for viewing in the trace detail page.
1. Upload an un-parsed JSON file (span-only data) to a Jaeger collector agent (with redirect functionality)
1. Storing large volumes of trace data locally via IndexDB

Is that right?

Each sound pretty separate from one another, e.g. trace data can be stored in IndexDB regardless of the source.

Using IndexDB makes great sense in an off-line mode, but what's the benefit in typical, online scenarios? 

>This changes can be evaluated, and eventually included in jaeger-ui codebase?

Contributions are **definitely** welcomed. :tada::tada:

**Comment by SwarnimRaj** [comment]
@sagrath23 Thank you for taking the initiative. I also need the above functionality in my current project and was wondering if you could share your code changes so that I don't have to reinvent the wheel.

**Comment by tiffon** [comment]
@sagrath23 Is this going to be a combined PR or split into separate features?

**Comment by yuribit** [comment]
Hi @sagrath23, thanks for creating this ticket. Do you have any update?

**Comment by sagrath23** [comment]
Hi @yuribit , right now, i'm working on the UI implementing the upload of a parsed JSON to visualize it.
Later, i will start to work on a functionality that allows Jaeger UI to upload an un-parsed JSON file to store it in jaegers back-end service.

**Comment by yuribit** [comment]
That sounds great! I was also planning to add the same feature, do you have an ETA?

**Comment by sagrath23** [comment]
Hi @yuribit , i will be uploading this approximately in 2-3 weeks, right now, i'm very busy with a release in my job.

**Comment by iNecas** [comment]
Hi, this feature would be very useful for my use-case as well. @sagrath23 Any progress/things to try regarding this topic?
