### ISSUE TITLE
Reset Viewing Layer zoom 

### ISSUE THREAD

**Issue by yuribit** [jaegertracing/jaeger-ui#215]
It would be nice to have a way to reset the selection on the Viewing Layer in the Trace Page Header. 
The easiest way to do that could be a "Reset Selection" button right above the Viewing Layer. 

Something like this:
![example](https://user-images.githubusercontent.com/1260900/41007755-22fa9000-68dc-11e8-8894-305525fc1ca1.gif)

What do you think?

**Comment by tiffon** [comment]
@yuribit Thanks for creating this ticket!

Great suggestion. Maybe it can show on mouse-over of the minimap, just below the bottom of the map. That way it won't obscure image or other zoom controls.

**Comment by tiffon** [comment]
This was fixed in #290 (although there is a regression where the minimap dragging is not working, at the moment).
