### ISSUE TITLE
[Bug]: Jaeger UI Displays spans in incorrect order

### ISSUE THREAD

**Issue by sanasz91mdev** [jaegertracing/jaeger-ui#2178]
### What happened?

Spans are shown in incorrect order. 

they are not in chronological order, why is that?

SOAP CLIENT Spans should come above API SERVER SPAN and API Server span should have been at bottom most

![spans-incorrect](https://github.com/jaegertracing/jaeger-ui/assets/39674269/f7b3d09b-2084-43ef-98d0-dc10aeda5191)

### Steps to reproduce

1. Start jaeger.
2. Put some sequential stress on any API containing multiple spans of different services

### Expected behavior

Spans should come in chronological order

### Jaeger backend version

v1.36.0

### Stogage backend

Elasticsearch

### Operating system

Linux

### Deployment model

Bare Metal - Linux VM

### Deployment configs

```shell
-
```

**Comment by yurishkuro** [comment]
there's nothing wrong with the screenshot, the API span is a child of some higher level parent, and within the parent all spans are shown chronologically.

**Comment by yurishkuro** [comment]
API span is not a sibling of SOAP spans, it's a child of a higher level span (which itself may be a sibling of SOAP spans)

**Comment by yurishkuro** [comment]
TPE span is not a parent span of API, they are at the same level. If you think it needs to be a parent span then your instrumentation is not producing the right data. Jaeger displays the data you send, and in that data TPE and API spans are sublings, according to the screenshot and indentation.
