### ISSUE TITLE
[Bug]: Y-axis (duration) is not accurate for long-running traces 

### ISSUE THREAD

**Issue by LeelaChacha** [jaegertracing/jaeger-ui#2180]
### What happened?

As a user of Jaeger UI, I want to see accurate axes for my traces. However, for long-running traces, that's not the case:
![image](https://github.com/jaegertracing/jaeger-ui/assets/54686422/7b6ec38f-5d55-4a1a-9b6e-6f3b89839e63)
One can observe that in the time range between 18 minutes and 19 minutes, there are two inaccurate time steps of 8 minutes.

### Steps to reproduce

1. Use the jaeger-all-in-one image
2. Generate long-running traces
3. Observe the time steps in the duration axis

### Expected behavior

Accurate time steps on the duration axis.

### Jaeger backend version

v1.54.0

### SDK

opentelemetry-sdk==1.22.0

### Pipeline

![image](https://github.com/jaegertracing/jaeger-ui/assets/54686422/56655a84-c00e-4768-ae89-e03602852e91)

### Stogage backend

In-memory

### Operating system

Ubuntu 22.04.4 LTS

### Deployment model

Kubernetes

**Comment by yurishkuro** [comment]
it looks like digit `1` is getting cut off by the margin

**Comment by tico88612** [comment]
> it looks like digit `1` is getting cut off by the margin

`overflow` default is `hidden`. What do you about `overflow` set `visible`? (`999999999918m` at the bottom is simulated non-real data.)

Before:
<img width="1394" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/17496418/c06762c1-76df-4b54-bd19-c5d335b20e82">

Preview:
<img width="1387" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/17496418/9d51332c-ac0f-40fd-b0a9-51c3c5322719">

**Comment by yurishkuro** [comment]
I think enabling overflow looks ugly, it's a lazy solution. I think something with two double digit numbers should just fit in the margins, we can make them wider. And longer values can wrap.

**Comment by yurishkuro** [comment]
wrapping behavior is controlled by CSS style somewhere. Browsers can wrap text not just on word boundary.

**Comment by tico88612** [comment]
> wrapping behavior is controlled by CSS style somewhere. Browsers can wrap text not just on word boundary.

This is SVG text, not a div. Some implementations might use `foreignObject`, but this would require deep rewriting of the react-div package, and I don't think that's a good idea.

But making it wider is fine. 70 px is suitable.

<img width="1426" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/17496418/56276fd1-0bcd-4652-8f45-207faab4fcaf">

What do you think?

**Comment by yurishkuro** [comment]
Ok
