### ISSUE TITLE
Uploading files into Search page performs unnecessary POST

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#2192]
To reproduce:
  * run jaeger-all-in-one separately
  * `yarn start`
  * Refresh screen so that Services dropdown shows all-in-one, and find & load its trace
  * Export that trace to local JSON file
  * Click on Search | Upload
  * Open DevTools in Chrome
  * click on upload icon and select saved file
  * The console shows an error message `POST http://localhost:5173/ 404 (Not Found)`
  * The file name shows up in red and its tooltip shows an error message
  * Meanwhile the file is loaded normally and shown in search results
<img width="461" alt="image" src="https://github.com/jaegertracing/jaeger-ui/assets/3523016/049f0cee-527f-4e12-9f98-072e06ee40f3">

The uploading files does not require communication with the server, it loads JSON in browser and displays the traces. However, somehow the way we're using `Upload` [from AntDesign](https://ant.design/components/upload) is causing it to submit the file back to the server from where the UI is loaded (normally it would be jaeger query service), which is neither necessary nor safe.

**Comment by tico88612** [comment]
@yurishkuro
I have a solution to resolve this issue. Can I work on this?

**Comment by yurishkuro** [comment]
go for it
