### ISSUE TITLE
[Feature]: Create GitHub Action to block PRs from ${fork}/main branch

### ISSUE THREAD

**Issue by varshith257** [jaegertracing/jaeger-ui#2213]
### Requirement

We should set up a new workflow that will fail if the PR is submitted from main branch. This workflow should be added to jearger/jarger-ui/documentation repositories (perhaps we need a reusable action - only if the check logic is reasonably complex).

### Problem

Making PR changes on the main branch of a fork is a bad practice, and breaks some of our workflows that check if the current branch is main before doing certain steps (like trying to push to Docker).

**Comment by varshith257** [comment]
It is a part of:

-  https://github.com/jaegertracing/jaeger/issues/5271

**Comment by varshith257** [comment]
@yurishkuro Here in this repo I can't find any GitHub actions. Should I add this functionality as a separate workflow in this repo?

**Comment by yurishkuro** [comment]
you can refer to the action from the main repo and add it to lint workflow

**Comment by varshith257** [comment]
> you can refer to the action from the main repo and add it to lint workflow

@yurishkuro Can guide this how can we link with main repo action? So that it can be make ease for me to raise a PR. I tried it before when issue created but didn't get a work around solution

**Comment by yurishkuro** [comment]
In the main repo we call the actions via relative path
```
    - name: Ensure PR is not on main branch
      uses: ./.github/actions/block-pr-not-on-main
```

In the other repos I think you can call the same action via full path `jaegertracing/jaeger/.github/actions/block-pr-not-on-main@main`

If that doesn't work for actions, it should definitely work for helper workflows according to the docs https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-caller-workflow
