### ISSUE TITLE
DAG view for individual traces

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#225]
## Requirement - what kind of business use case are you trying to solve?

Represent a trace as a DAG.

## Problem - what in Jaeger blocks you from solving the requirement?

The view is not available in the UI.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a DAG view for individual traces. This can leverage work done on #155.

## Any open questions to address

How to represent span details, etc., in the collapsed view.

Note: The [research for trace diffs](https://docs.google.com/document/d/1aW5PkSmvOp5-6AQ7YzQYEXAul59YEaqsiLPAvXHCGgg/edit?usp=sharing) might be relevant. The aesthetic should be consistent with trace diffs.

**Comment by ab-pm** [comment]
Is this what #276 implemented?

**Comment by yurishkuro** [comment]
Yes, thanks for noticing.
