### ISSUE TITLE
"Collapse One" button throws an error when trace is fully collapsed

### ISSUE THREAD

**Issue by yuribit** [jaegertracing/jaeger-ui#229]
```
0
- 1
--- 2
- 3
--- 4
- 5
```
When you click on the "Collapse One" button for 3 times using the above trace as input, the webapp throws the following error:
`Uncaught TypeError: Cannot read property 'spanID' of undefined
    at collapseOne (duck.js:174)`

**Comment by tiffon** [comment]
Thank you for filing!
