### ISSUE TITLE
Showing results from previous run in service DAG

### ISSUE THREAD

**Issue by etsangsplk** [jaegertracing/jaeger-ui#233]
## Requirement - what kind of business use case are you trying to solve?

Viewing service dependencies collected from traces.

## Problem - what in Jaeger blocks you from solving the requirement?
I am using the out of the box solution from HotRod. But I also run my own dummy example agiant the same backend. What I notice is that they serivce DAG graph is howin results form hotRod and other runs which I already select for specific seraches in the first panel. Why is it showing all the runs? Is there configuration or something else I have to pass in to the trace?

It does not look like doing any filtering for dependencies
https://github.com/jaegertracing/jaeger-ui/blob/045524adcebfef1b2cc2e3ca2263fcefdeec2b64/packages/jaeger-ui/src/api/jaeger.js#L94

**Comment by tiffon** [comment]
Hi @etsangsplk, thanks for creating this ticket. And, apologies for the slow reply.

The current functionality shows the service dependency graph for all services. It's not based on queries from the search page.

We are planning to add a dependency graph which can be filtered by service or service-operation. That work is not yet underway, but should be done this year.

I re-read your comments, and it seems like what you're referring to might be to generate a dependency graph from a group of traces? We're looking into functionality along those lines but haven't settled on requirements, yet. Can you tell us a little about your use-case? Or, did I get my wires crossed regarding creating a dependency graph from a set of traces?
