### ISSUE TITLE
[Feature]: Order by Longest First maybe is better than Most Recent

### ISSUE THREAD

**Issue by RaymondLam1** [jaegertracing/jaeger-ui#2343]
### Requirement

In fact, when we look at trace data, we pay more attention to traces that take a long time.

### Problem

By default, jaeger-ui sorts trace data by 'Most Recent'

### Proposal

Just order by 'Longest First' instead of 'Most Recent' by default.

**Comment by RaymondLam1** [comment]
If the community approves, I'd be happy to submit a PR

**Comment by yurishkuro** [comment]
Returning most recent data first is the standard behavior for most telemetry platforms. It suits well many other use cases, whereas longest-first is just one specific use case. We're not planning to change this.
