### ISSUE TITLE
[Bug]: Duplicate Shortcut Key in Jaeger-UI

### ISSUE THREAD

**Issue by smritidoneria** [jaegertracing/jaeger-ui#2379]
### What happened?

Users have observed that multiple keyboard shortcuts within the application,This similarity across keyboard shortcuts has caused confusion among users, as they seek clarity on the precise differences and intended uses for each shortcut.
<img width="851" alt="Screenshot 2024-07-11 at 5 30 05 PM" src="https://github.com/jaegertracing/jaeger-ui/assets/109029101/508ac363-afc4-453a-aa32-708d8682929f">

### Steps to reproduce

go to jaeger-ui interface.

### Expected behavior

there should be only one listing of one keyboard shortcut.

### Operating system

MacOs

### Deployment model

docker

### Deployment configs

```shell
docker-compose.yml
```

**Comment by smritidoneria** [comment]
if this approves, I will like to work on this

**Comment by yurishkuro** [comment]
AWDS keys for navigation is a broadly used combination. I don't see what's confusing about that.
