### ISSUE TITLE
Extra vertical scrollbar in the Trace View

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#241]
Not sure how, I was running local Jaeger UI with external monitor, and the trace view got an inner scrollbar, next to the full page scrollbar, which makes the scrolling work poorly.

![image](https://user-images.githubusercontent.com/3523016/44633315-cc526180-a957-11e8-8b9f-e4e51961d56b.png)

**Comment by tiffon** [comment]
Thanks, @yurishkuro for reporting this.

Was this issue persistent or was it kind of a one-time-thing? Also, it'd be preferable if you can send me a link to the issue (point to the site on your local machine), but if that's not possible, can you save a page with the issue occurring? If you do CMD+S and then set the "Format" to web-page complete, that would be super helpful. 

Lastly, what browser and version did you see this with?

**Comment by yurishkuro** [comment]
I was able to reproduce it just now in Chrome, Version 68.0.3440.106, on MacBook Pro.  Complete page attached. The issue was not as bad as previously, but essentially if I zoom in to 200% and try swiping up/down in the gantt chart area, sometimes the full page scroll bar appears, and sometimes the inner one.

[Archive.zip](https://github.com/jaegertracing/jaeger-ui/files/2344121/Archive.zip)
