### ISSUE TITLE
Help upgrading from raven-js

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#2412]
We are using a deprecated https://www.npmjs.com/package/raven-js package in [packages/jaeger-ui/src/utils/tracking/](./packages/jaeger-ui/src/utils/tracking/). Maybe we can use `@sentry/browser` for that, or maybe we can just implement the needed functionality internally since we use it only to capture some basic error information to submit to the tracking backend.

**Comment by BenzeneAlcohol** [comment]
I can take this up. I'll do this first, and then the other bug for spans (in case someone doesn't solve that yet.)

**Comment by BenzeneAlcohol** [comment]
Ok, so I went through @sentry/browser, and tried integrating it. I feel the work is same if we change it to @sentry/browser, or just re write functionality internally, however having a package means added scope for development in the future. I do prefer re writing the functions internally tho. But I'm not sure how to structure the files in that case? Where to write the new functions (under what folder) and testing them. If there is a method for this, I'll propose an idea for re writing the internal functions.

**Comment by yurishkuro** [comment]
I am not opposed to just switching to `@sentry/browser` if it provides equivalent functionality

**Comment by yurishkuro** [comment]
but if we're talking about like 10 lines of code that I'd rather re-implement than pull a separate dependency

**Comment by BenzeneAlcohol** [comment]
It won't be 10 lines of code tho. Right now the biggest issue I've faced is the lack of a direct shift from `RavenTrasportOptions` in `@sentry/browser` package. Have to rewrite a few interfaces for that, and a few functions as well. It just feels like we can just shift half the functionality to `@sentry/browser`, the other half has to be custom. Perhaps I'll open a draft PR with changes I've done so far and you can comment on them? I am yet to migrate the biggest file `ga.tsx` - this is where the custom interfaces need to come in, but others are done.
