### ISSUE TITLE
[Bug]: Operation all dosen't return all the trace 

### ISSUE THREAD

**Issue by MattiaRigon** [jaegertracing/jaeger-ui#2426]
### What happened?

Using the jaeger ui, if I want to search all the trace, selecting all in the operation form dose not return all the trace.
While if I set the operation field to a specific value like GET I can see traces that I should see also with the "all" option.

We can see filtering by all, I get just 3 trace (and 0 get request ...), while if I explicit GET I can see correctly all the GET.
<img width="1262" alt="all_screen" src="https://github.com/user-attachments/assets/a7866086-7d07-41fe-be12-6ee4646e3632">

<img width="1262" alt="get_screen" src="https://github.com/user-attachments/assets/14d30453-eb03-4eed-8fd5-2dd16fb9f08b">

In addition I have looked the cassandra table traces, where all the trace are stored and in db running a simple distinct on the trace_id I have seen that there are a lot of more distinct trace_id (more than 100).

### Steps to reproduce

1. Look if the trace filtered setting operation to all are correctly all the trace
2. Look if filtering the operation setting others value shows some trace that are not present in the all case.

### Expected behavior

I expect that selecting all in the operation enable me to see all the trace that was produced the selected time interval, not just a few.

### Stogage backend

cassandra

### Operating system

Windows(WSL2)

### Deployment model

docker compose

### Deployment configs

```shell
docker-compose.yml

services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.57.0
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.otlp.enabled=true"
    environment:
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - "4317" # accept OpenTelemetry Protocol (OTLP) over gRPC
    restart: on-failure
    depends_on:
      - cassandra-schema
 
  cassandra:
    image: cassandra:4.1.4
    volumes:
      - ./cassandra_data:/var/lib/cassandra
 
  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.57.0
    depends_on:
      - cassandra
 
  jaeger-query:
    image: jaegertracing/jaeger-query:1.57.0
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--prometheus.query.support-spanmetrics-connector=true"
      - "--prometheus.server-url=http://prometheus:9090"
      - "--prometheus.query.normalize-duration=true"
      - "--prometheus.query.normalize-calls=true"
    ports:
      - "16686:16686"
      - "16687:16687"
    restart: on-failure
    depends_on:
      - cassandra-schema
 
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./conf/otel-collector-config.yaml:/conf/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - "8889" # Prometheus metrics exporter

    restart: on-failure
    depends_on:
      - jaeger-collector

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yml:/workspace/prometheus.yml
    command:
      - --config.file=/workspace/prometheus.yml

otel-collector-conf.yaml

receivers:
  otlp:
    protocols:
      grpc:
      http:
 
exporters:
  otlp:
    endpoint: jaeger-collector:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://jaeger-collector:4318
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  
processors:
  tail_sampling:
    decision_wait: 10s
    num_traces: 100
    policies:
      # ALWAYS SAMPLE
      - name: always-sample
        type: always_sample
```

**Comment by yurishkuro** [comment]
did you try increasing the Limit number?

**Comment by MattiaRigon** [comment]
Yes, I have also tried to use the batch processor without specific limit, but I have the same problem.
Thanks

**Comment by MattiaRigon** [comment]
Yes I have also tried to use the batch processor without limitations, but I have the same issue.
Thanks
