### ISSUE TITLE
Validate duration fields in UI

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-ui#244]
## Requirement - what kind of business use case are you trying to solve?

Validate the duration fields before allowing the search

## Problem - what in Jaeger blocks you from solving the requirement?

Currently an invalid duration field can be specified and sent to the backend, resulting in an error in the main area.

![jaeger-invalid-min-duration](https://user-images.githubusercontent.com/164562/45026859-90925880-b037-11e8-9bb2-68a7737b58ce.png)

## Proposal - what do you suggest to solve the problem or improve the existing situation?

`Find Traces` button only enabled if all of the fields are valid - so when user enters content into the min/max duration fields it must be valid before the search button is re-enabled.

**Comment by everett980** [comment]
I didn't use the correct syntax in the PR that addressed this, closing now. Please re-open if the issue persists.
