### ISSUE TITLE
[Bug]: DAG view display issue

### ISSUE THREAD

**Issue by ijavaofkid** [jaegertracing/jaeger-ui#2454]
### What happened?

DAG - nodeCircle is blocking the number to be displayed，As shown in the following figure
![image](https://github.com/user-attachments/assets/ec07e52e-359f-44e1-b9a3-e779a49f75df)

### Steps to reproduce

Add dependencies support and open DAG view

### Expected behavior

Adjust the position or hierarchy of the numbers to be displayed
Causes and solutions
![image](https://github.com/user-attachments/assets/3c696bcb-59cc-4d85-b23e-d5369e50d2df)
Swap the output order of div and svg in the above figure
as like this 
![image](https://github.com/user-attachments/assets/2205eff8-c4ec-4728-9f33-477ec4d01d2d)
So it's okay
![image](https://github.com/user-attachments/assets/6ee5b636-3093-409f-8bd8-ca2558f19b49)
Please fix as soon as possible

**Comment by SaunakNandi** [comment]
@ijavaofkid If open the website https://www.jaegertracing.io then after this how can I reach this DAG part or the above image

**Comment by ijavaofkid** [comment]
> @ijavaofkid If open the website https://www.jaegertracing.io then after this how can I reach this DAG part or the above image

it is just an jaeger website ，I think you need to this https://www.jaegertracing.io/docs/1.61/getting-started/  first

**Comment by jayabha-jayas** [comment]
@ijavaofkid Hi, I tried to reproduce this issue. For me, the numbers were visible. Can you please help me with the steps to reproduce this. Thanks

**Comment by ijavaofkid** [comment]
> [@ijavaofkid](https://github.com/ijavaofkid) Hi, I tried to reproduce this issue. For me, the numbers were visible. Can you please help me with the steps to reproduce this. Thanks

sure，When the parent service and child service are the same service, this problem can be replicated。
