### ISSUE TITLE
Provide a view to project service name and tag value by tag name

### ISSUE THREAD

**Issue by quaff** [jaegertracing/jaeger-ui#246]
In a large organization, there is numbers of services deployed base on different version runtime, version info can be collected as process tag, It's appreciated if jaeger ui provide a view to project them, like this:

| Service  | java.version |
| ------------- | ------------- |
| Service A | 1.8.0_181 |
| Service A | 9 |
| Service B | 1.8.0_181 |
| Service C | 1.8.0_181 |
| Service D | 10.0.2 |

`java.version` is tag name inputed by user, and same service could have multiple tag value.

**Comment by yurishkuro** [comment]
Also worth mentioning, if you are using ElasticSearch as a storage backend, and have the versions in span tags, you should be able to get this data directly from ES.

**Comment by quaff** [comment]
@yurishkuro `process.tags` is not indexed, query return empty results.
```
{
  "query": {
    "exists": {
      "field": "process.tags"
    }
  }
}
```

I think this is blocked by https://github.com/jaegertracing/jaeger/issues/906

**Comment by jkowall** [comment]
Feel free to re-open if the ElasticSearch/OpenSearch solution doesn't solve this.
