### ISSUE TITLE
Need to speed up s390x-build

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#2468]
@pavolloffay @andreasgerstmayr are there things you can do to speed up `s390x-build` workflow? The rest of our CI runs within 2min, this workflow takes 12min, blocking auto-merges, etc.

**Comment by andreasgerstmayr** [comment]
I'll take a look, probably we can utilize a cache in GitHub actions.

**Comment by andreasgerstmayr** [comment]
In #2462 I restructured the Dockerfile to cache the dependencies in a new layer.

Timings:
2 minutes for `npm ci` (now cached in case the package.json and lockfile doesn't change)
4 minutes for plexus build
5 minutes for jaeger-ui build

Not sure if/how we can accelerate the plexus/jaeger-ui builds. QEMU/docker is emulating s390x on a x86 GitHub actions VM, making the build much slower.

**Comment by yurishkuro** [comment]
It would be ideal to have a native runner. CNCF has custom runner types, including Apple silicone, but I don't see s390 among them.

**Comment by yurishkuro** [comment]
> now cached in case the package.json and lockfile doesn't change

I think the most frequent runs we do are dependency upgrades, so I expect that to always bust the cache.

**Comment by andreasgerstmayr** [comment]
> > now cached in case the package.json and lockfile doesn't change
> 
> I think the most frequent runs we do are dependency upgrades, so I expect that to always bust the cache.

I'll try to cache the global npm package cache then (next week).

Regarding the build tasks (which take significantly more time than the dependency task), the only idea I have is to switch the tooling to something native instead of Node.js ([SWC](https://swc.rs/) for example). But that would replace Vite, and I'm not sure if it's worth it if we're happy with Vite.

**Comment by yurishkuro** [comment]
What if we remove s390x from the CI and only run it on main?

**Comment by andreasgerstmayr** [comment]
> What if we remove s390x from the CI and only run it on main?

I'm not too happy about getting informed of build failures after the fact, when the faulty code is already merged, but I'm out of options here 😬 . I'll create a PR
