### ISSUE TITLE
Make jaeger-ui installable by npm

### ISSUE THREAD

**Issue by aljesusg** [jaegertracing/jaeger-ui#248]
## Requirement - what kind of business use case are you trying to solve?

I am from Jaeger team and [Kiali](https://github.com/kiali) in RH. 
Kiali is the UI for [Istio](https://istio.io/), we are currently integrating the jaeger with some external links.

We want to collect the information provided by jaeger and the information of Kiali and show the relation to improve the tracing and observability of the service mesh so for example if we can show the component of the traceresults with our information, will be useful for the user.

Actually we have an external link to the full UI jaeger in tabs, our idea is contribute/improve the component to import them to our project from the jaeger UI for example the last 10 traces in our view using the component TraceTimelineViewer. 

## Problem - what in Jaeger blocks you from solving the requirement?

We can't integrate components of Jaeger UI  So we are using external links to the Jaeger-UI in a new tabs.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

1. Change the package.json to publish the releases
2. Compile al build the components to export them
3. Improve/contribute in  the component

cc @jpkrohling @objectiser

**Comment by yurishkuro** [comment]
@tiffon thoughts?

**Comment by mtho11** [comment]
It would be great to see these components published to npm so that others could use the jaeger-ui components directly in applications.

**Comment by saminzadeh** [comment]
> It would be great to see these components published to npm so that others could use the jaeger-ui components directly in applications.

+1. This would be nice as a component library.

A few initial ideas on how to approach this:

- **Stateless Components that take the standardized Trace object**. You will responsible for providing the Trace object to the component.

```js
import { TraceViewTimeline, TraceDAG } from '@jeagertracing/ui-kit';
import trace from './samples/my-jaeger-trace.json'

<TraceViewTimeline trace={trace} />
<TraceDAG trace={trace} customOverrides={...} />
```

- **React Provider Pattern (eg. Redux, Apollo GraphQL, etc)**. Similar to how [SearchKit](http://docs.searchkit.co/stable/) makes it easy to integrate with ElasticSearch. We could do something similar for the JaegerQuery API. 

```js
import { 
  TraceViewTimeline, 
  JaegerClient, 
  JaegerProvider, 
  JaegerRenderer 
} from '@jeagertracing/ui-kit';

// Init Jaeger client
const jaegerClient = new JaegerClient("http://my.jaeger.host.com")

const App = ()=> (
  <JaegerProvider jaegerClient={jaegerClient}>
    <Layout>
      <h2>My Trace</h2>

      // Predefined component
      <TraceViewTimeline traceId="e29208c2-bc23-11e8-a355-529269fb1459" />

      // Custom components via Render Props
      <JaegerRenderer traceId="e29208c2-bc23-11e8-a355-529269fb1459">
        {({ trace, loading }) => {
          if(loading) {
            return "Loading trace..."
          }

          return (
            //... do custom logic with trace here
          )
        }}
      </ JaegerRenderer>
    </Layout>
  </JaegerProvider>
)

ReactDOM.render(<App/>, document.getElementById('root'))


```

```

**Comment by tiffon** [comment]
@aljesusg – Thanks for creating this ticket! This topic is actually something that is coming up for us, internally, as well.

The two main avenues for integration we've been exploring are either publishing React components or using iframes to create an embedded experience.

One drawback for wholesale publishing the React components, in their current form, is that when all of the components become public, their combined API becomes the API contract. That's a massive contract. So much so it would essentially become impossible to maintain backwards compatibility while making any significant changes to the UI.

So, if we go down the path of publishing React components, I think the [approach outlined](https://github.com/jaegertracing/jaeger-ui/issues/248#issuecomment-422864697) by @saminzadeh would make the API contract more manageable.

But, it'd be nice to get a sense of the current use-cases and to see what, concretely, needs to be supported.

Can you elaborate a bit on the types of integrations you have in mind?

**Comment by saminzadeh** [comment]
> One drawback for wholesale publishing the React components, in their current form, is that when all of the components become public, their combined API becomes the API contract. That's a massive contract. 

@tiffon I agree with you here. The components in their current form were not built with a public API in mind and it could be a maintenance burden if we published them today.

**Comment by yurishkuro** [comment]
Perhaps I'm missing something, but why do we need to publish ALL components instead of just the ones on the highest level?

**Comment by aljesusg** [comment]
> But, it'd be nice to get a sense of the current use-cases and to see what, concretely, needs to be supported.
> 
> Can you elaborate a bit on the types of integrations you have in mind?

@tiffon SearchResults or ResultItem for example. Thanks

**Comment by yurishkuro** [comment]
@aljesusg I see you're creating PRs, but we have not agreed to what approach we want to take. I completely agree with @tiffon that we do not want to explore the public API surface of React components. If we still want to publish some embeddable components, I would prefer to design them from scratch, ie define a narrow interface and implement it with the existing components treating the latter as internal/private. It will allow us to change them freely without affecting the public facade.

Can we start with defining the API? Or even better, listing your specific requirements for embedding. Maybe they can be satisfied with embedding an iframe.

**Comment by aljesusg** [comment]
Yes @yurishkuro, sorry I saw later that you used **nbw** to create the plexus package, so I learned about and I redo the package, my idea was help you in this. About your comment I agree with you so I'll wait until your decision, It will be cleaner if it is done separately in another repo.

**Comment by lambertjosh** [comment]
Thanks @jpkrohling for the heads up on this. We've been looking for ways to best integrate the Jaeger UI, similar to Kiali, and this would be a great help.

I'd vote for the API route, as it would be more broadly adoptable than a React component. For example at GitLab we use Vue.

**Comment by aljesusg** [comment]
I think that we can close this in favor #279
