### ISSUE TITLE
Trace duration unit in scatterplot is always 'seconds'

### ISSUE THREAD

**Issue by zdicesare** [jaegertracing/jaeger-ui#253]
## Requirement - what kind of business use case are you trying to solve?

The graph of traces returned from a search should show the unit of trace duration correctly

## Problem - what in Jaeger blocks you from solving the requirement?

![graph](https://user-images.githubusercontent.com/1680362/46035665-937de780-c0d1-11e8-81cb-af9b6ddaac25.png)
When you search for traces, the unit on the y-axis is 's'. However, these traces took that many milliseconds, not seconds.
![trace](https://user-images.githubusercontent.com/1680362/46035664-937de780-c0d1-11e8-9f3f-a14b7217a59c.png)
Clicking in on one (this is the upper most trace) shows the duration was that many milliseconds.

**Comment by tiffon** [comment]
@zdicesare Thank you for reporting this!

**Comment by Puneeth-n** [comment]
Any idea when this will be released?

**Comment by yurishkuro** [comment]
In 1.8 - see https://github.com/jaegertracing/jaeger/issues/1150
