### ISSUE TITLE
Change archive enabled config to be consistent with dependencies

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-ui#277]
## Requirement - what kind of business use case are you trying to solve?

As discussed https://github.com/jaegertracing/documentation/pull/171, it might be good for consistency to change the archive enabled UI config to be consistent with the dependencies config.

## Problem - what in Jaeger blocks you from solving the requirement?

Not necessarily a problem, but would be more consistent.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Change archive config to be:

```
{
  "dependencies": {
    "menuEnabled": true
  },
  "archive": {
    "menuEnabled": true
  }
}
```
which would also enable other `archive` related config options to be easily added in the future if relevant.

**Comment by tiffon** [comment]
@objectiser Thanks for filing this.

The archive menu enabled is configured as a top-level property instead of a propery within an object because it's a single, isolated value. The dependencies is a collection of related configurations.

```
{
  "dependencies": {
    "dagMaxNumServices": 200,
    "menuEnabled": true
  },
  "archiveEnabled": true,
}
```

The rationale is to avoid something like:

```json
{
  "dependencies": {
    "dagMaxNumServices": 200,
    "menuEnabled": true
  },
  "archive": {
    "menuEnabled": true
  },
  "trace": {
    "maxSpans": 200
  },
  "search": {
    "maxLimit": 200
  },
  "comparisons": {
    "maxTraces": 20
  },
  "footer": {
    "enabled": true
  }
}
```

And to instead have:


```json
{
  "dependencies": {
    "dagMaxNumServices": 200,
    "menuEnabled": true
  },
  "archiveMenuEnabled": true,
  "traceMaxSpans": 200,
  "searchMaxLimit": 200,
  "comparisonsMaxTraces": 20,
  "footerEnabled": true
}
```

The downside, which I hadn't considered (thanks!), is adding a value changes the format becaue it becomes a group. We have a facility in the UI to easily handle that, but still annoying. OTOH, having to foresee future-appropriate namespaces is a trade-off:

```
{
    "traceHeader": {
        "archiveMenuEnabled": true
    }
}
```

vs

```
{
    "archive": {
        "menuEnabled": true
    }
}
```

What do you think?

**Comment by objectiser** [comment]
Understand the dilemma - although possibly would be useful to have groups for the areas that have a `menuEnabled` property, and keep the rest top level for now. So

```
{
    "archive": {
        "menuEnabled": true
    },
    "compare": {
        "menuEnabled": true,
        "maxTraces": 20
    },
    "dependencies": {
        "dagMaxNumServices": 200,
        "menuEnabled": true
    },
    "traceMaxSpans": 200,
    "searchMaxLimit": 200,
    "footerEnabled": true
}
```

**Comment by yurishkuro** [comment]
My preference is to have hierarchical structure grouped by top level views, ie all search defaults are under "search" key. But it does present a problem for crosscutting functionality such as archive, since it can theoretically be accessible from
