### ISSUE TITLE
[embed] Scatter plot links to trace lose embed mode when clicked

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#282]
## Requirement - what kind of business use case are you trying to solve?

When in embed mode on the search page, clicking a dot from the scatter plot should retain embed mode.

## Problem - what in Jaeger blocks you from solving the requirement?

When in embed mode on the search page, clicking a dot from the scatter plot loses retain embed mode, currently.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Retain embed mode when viewing the trace.

## Any open questions to address

n/a

**Comment by tiffon** [comment]
cc @aljesusg

**Comment by aljesusg** [comment]
We can close this issue ;) Thanks @tiffon

**Comment by tiffon** [comment]
Right. :+1:

If you add `Fixes #N.` to the PR it will close automatically.

**Comment by aljesusg** [comment]
I forgot I added #N to the commit but not in description my bad ^^. Thanks @tiffon
