### ISSUE TITLE
query by namespace

### ISSUE THREAD

**Issue by loveai88** [jaegertracing/jaeger-ui#285]
## Requirement - what kind of business use case are you trying to solve?
I have two namespaces and run same service in them,how can I query service in the namespace which I want?

**Comment by yurishkuro** [comment]
Are you referring to Kubernetes namespaces?  You need to capture those as a tracer tag, then you can search for it.

**Comment by objectiser** [comment]
@loveai88 Other approach is to include the namespace as part of the service name, e.g.  `<service>.<namespace>`. Benefit of this approach is when viewing the services on a dependency graph - they are represented as individual uniquely named nodes.

**Comment by tiffon** [comment]
@loveai88 Per @yurishkuro's suggestion, filtering by the tag:

<img width="458" alt="screen shot 2018-12-17 at 8 20 04 pm" src="https://user-images.githubusercontent.com/2304337/50126027-3a899f80-0239-11e9-8050-74d0c91b4e91.png">

In order for that to work, the namespace needs to be added as a span tag to the service's span.

I'm closing this as it's more of a question than a description of a problem or enhancement.
