### ISSUE TITLE
Error while building a docker with jaeger

### ISSUE THREAD

**Issue by Bharathvarsha** [jaegertracing/jaeger-ui#294]
## Requirement - what kind of business use case are you trying to solve?

!!

## Problem - what in Jaeger blocks you from solving the requirement?

I'm facing Error while building a dockerFile , the error is due to jaeger.
Step 4/13 : RUN go get
 ---> Running in 6e2eaefc3c0d
# github.com/uber/jaeger-client-go
../github.com/uber/jaeger-client-go/metrics.go:100:35: too many arguments in call to factory.Namespace
	have (string, nil)
	want (metrics.NSOptions)
The command '/bin/sh -c go get' returned a non-zero code: 2

**Comment by tiffon** [comment]
@Bharathvarsha Are you sure this is related to the UI? Looks like it has to do with the [go client](https://github.com/jaegertracing/jaeger-client-go)?

**Comment by Bharathvarsha** [comment]
Thanks for the reply @tiffon , I resolved it. It is because, I didn't use the latest version of Jaeger.(version Issue).

**Comment by tiffon** [comment]
Great to hear :+1:
