### ISSUE TITLE
Combining results 

### ISSUE THREAD

**Issue by DavitSo** [jaegertracing/jaeger-ui#295]

**Comment by DavitSo** [comment]
I run 2 different dummy program in the same host(use same collector). from first program(create 4 span) I pass root span to second program(create 1 span).  
In UI I get trace with 5 span.
my question is - Is it normal behavior?

**Comment by tiffon** [comment]
Kind of hard to tell based on your description. But, if you created spans from the same context, then they should be in the same trace. 

Btw, here is a [set of tutorials](https://github.com/yurishkuro/opentracing-tutorial/tree/master) on the concepts and application of OpenTracing that might be helpful. They cover using OpenTracing with Go, Python, C#, Java and Node.js. I think the Node tutorial is a WIP.

Also, the [Gitter channel](https://gitter.im/jaegertracing/Lobby) is probably better for this type of question.

I'm going to close this as it doesn't indicate a problem or enhancement to the UI.
