### ISSUE TITLE
Add query param to timeline view for deep linking

### ISSUE THREAD

**Issue by everett980** [jaegertracing/jaeger-ui#303]
## Requirement - what kind of business use case are you trying to solve?
Ability to link to a trace with a specified spanId selected and scrolled into view.

## Problem - what in Jaeger blocks you from solving the requirement?
Currently there is no ability to link to a specific span.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Add an optional query param for spanId to specify which span should be selected and in view.

## Any open questions to address
What to do if spanId is absent?
a) Ignore query param and behave as though not present.
b) (a) + small indicator that span id was not found

**Comment by yurishkuro** [comment]
I would add a dismissible warning banner at the top indicating that span id is not found in the trace
