### ISSUE TITLE
Trace Graph has wrong service hierarchy

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-ui#315]
## Requirement - what kind of business use case are you trying to solve?

Accurate service hierarchy in the new Trace Graph view.

## Problem - what in Jaeger blocks you from solving the requirement?

Working on PR to upgrade Istio to use Jaeger 1.9. I noticed that the trace graph didn't reflect the correct order of spans.

For example, in the bookinfo example, the istio-ingressgateway receives the initial call which then goes to the productpage service - as show in the following trace timeline:

![jaeger-istio-bookinfo-timeline](https://user-images.githubusercontent.com/164562/51541299-627bac80-1e50-11e9-8176-cb9f112803e1.png)

However the trace graph view for the same instance shows:

![jaeger-istio-bookinfo-graph](https://user-images.githubusercontent.com/164562/51541403-a2db2a80-1e50-11e9-935e-7ed927c21140.png)

This shows the productpage appearing to be the root (initial span) calling the istio-ingressgateway, which is the wrong way around. Also not clear whether all of the spans are represented in the graph (e.g. client spans for the productpage) - although possibly the graph doesn't show all of these?

The trace data is collected from envoy proxies reporting the information in zipkin format with shared span context (I believe, although it is now possible to disable this in envoy - but not sure this is configurable from Istio yet).

The trace data:

[jaeger-istio-bookinfo-trace-unadjusted.json.txt](https://github.com/jaegertracing/jaeger-ui/files/2783137/jaeger-istio-bookinfo-trace-unadjusted.json.txt)
[jaeger-istio-bookinfo-trace.json.txt](https://github.com/jaegertracing/jaeger-ui/files/2783139/jaeger-istio-bookinfo-trace.json.txt)

**Comment by tiffon** [comment]
@objectiser Thanks for filing this!

>This shows the productpage appearing to be the root (initial span)...

This is definitely incorrect.

>calling the istio-ingressgateway, which is the wrong way around. 

But, this looks consistent with the trace. `productpage.default` calls into `istio-ingressgateway`; the 7th trace from the top calls the bottommost span, in the timeline screenshot.

Definitely something is awry. Will check it out. And, thanks for the sample data!

**Comment by objectiser** [comment]
@tiffon Thanks, hadn't spotted that call back to `istio-ingressgateway`. Although I think it is wrong - related to the shared span context.

Not sure this is actually a bug in Jaeger, as have seen a similar problem with the data before, based on two consecutive server spans being reported by envoy proxy from different services, but because it uses the zipkin shared span context by default, the second server span still takes the passed span id (assuming the parent span is a client span). This messes up the Jaeger adjustment to try to make the client and server span ids unique.

If we can leave this open for now, and I will see if I can get the shared span context disabled and retry.

**Comment by objectiser** [comment]
Disabling the shared span context fixes the issue: https://github.com/istio/istio/pull/11232

**Comment by tiffon** [comment]
After disabling the shared span context, is the issue with the root-span still present?

**Comment by objectiser** [comment]
@tiffon No, the `istio-ingressgateway` span that was previously contained under `productpage` service is now shown correctly as a child of the root span: 

![jaeger-istio-bookinfo-timeline2](https://user-images.githubusercontent.com/164562/51693594-2cc4f800-1ff7-11e9-89e3-4652f1d082d0.png)

Also the graph is better:

![jaeger-istio-bookinfo-graph2](https://user-images.githubusercontent.com/164562/51693558-1b7beb80-1ff7-11e9-8150-ddab92e367c5.png)

**Comment by jacob-koren-zooz** [comment]
How can I disable the shared span context?
