### ISSUE TITLE
Unable to get span info when error is reported:<trace-without-root-span>

### ISSUE THREAD

**Issue by vbottu** [jaegertracing/jaeger-ui#316]
## Problem - what in Jaeger blocks you from solving the requirement?
I am trying to emulate error from my service and get it visualized on jaeger-ui, for successful requests the span has servicename, operationname etc,but when the service returns error for example 404, then all I can see is <trace-without-root-span> and I have to open that trace to see if it is error. Attaching the screenshot.  
Am i missing something here?

I want to be able to see the service name and operation name in case of error as well. 

## Any open questions to address

 
![image](https://user-images.githubusercontent.com/19859827/51703871-2590f080-1fdd-11e9-8b2d-db73d44bc4ec.png)

**Comment by tiffon** [comment]
Thanks for filing this. (Apologies for the delayed response!)

This is probably an instrumentation, issue. 

Can you send the trace JSON for the error trace? Mostly, I'm curious about the span's `references` field and `process` details.

**Comment by lekhRazz** [comment]
Probable you had forgot to close span. i.e. span.finish(); statement must be added to get your rootspan name.

**Comment by pavolloffay** [comment]
This seems like instrumentation issue and not Jaeger UI issue. In case of error your root span wasn't finished properly.
