### ISSUE TITLE
Browser back button of trace page not working if plot is clicked

### ISSUE THREAD

**Issue by tacigar** [jaegertracing/jaeger-ui#323]
## Requirement - what kind of business use case are you trying to solve?

If I move to the trace page by clicking Plot, the back button does not work.

![jaeger-back-button](https://user-images.githubusercontent.com/19551419/52319496-4d387d80-2a0d-11e9-9cd3-8335f3abf17d.gif)

## Problem - what in Jaeger blocks you from solving the requirement?

`goToTrace` in `SearchTracePageImpl` is not good.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Change `goToTrace` from

```
  goToTrace = traceID => {
    const { queryOfResults } = this.props;
    this.props.history.push(getTraceLocation(traceID, { fromSearch: queryOfResults }));
  };
```

to

```
  goToTrace = traceID => {
    const { queryOfResults } = this.props;
    const searchUrl = getUrl(stripEmbeddedState(queryOfResults));
    this.props.history.push(getTraceLocation(traceID, { fromSearch: searchUrl }));
  };
```

**Comment by tiffon** [comment]
Fixed in #324.
