### ISSUE TITLE
Extra chevron visible for span detail rows

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#328]
Span detail rows for spans that have children now show a chevron, which they shouldn't.

<img width="72" alt="screen shot 2019-02-14 at 4 55 32 pm" src="https://user-images.githubusercontent.com/2304337/52820293-9e81e600-3079-11e9-9eac-1f9779ede22b.png">

It's an extra artifact that implies the detail row, itself, can be used to expand or collapse children, which is not the case.

**Comment by rubenvp8510** [comment]
I'll take this one.
