### ISSUE TITLE
Timeline visualization regression

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger-ui#333]
## Requirement - what kind of business use case are you trying to solve?
Visualize traces

## Problem - what in Jaeger blocks you from solving the requirement?
I'm not totally sure how but seems like the pull request https://github.com/jaegertracing/jaeger-ui/pull/297 broke the indentation in the timeline view in some cases.

If I checkout the previous commit in master (ac4f7a7f5a66d8eea5a20f45bb3b86ac65ebd9e7) I see this:
<img width="420" alt="pre" src="https://user-images.githubusercontent.com/1359779/53206430-f337da80-35fe-11e9-9832-a233cddd6cf5.png">

But when I checkout this commit from master (f23eb487572a67047869dc2ea70098d943091146) I see this:
<img width="420" alt="post" src="https://user-images.githubusercontent.com/1359779/53206437-f763f800-35fe-11e9-9b0c-876c78dca77f.png">

Here's the trace that is in the screenshot above: https://gist.github.com/ledor473/a51e66aee1f14285eef4953ae7ee6d59

## Proposal - what do you suggest to solve the problem or improve the existing situation?
I'm not sure what broke it exactly, so its hard to propose a fix.

**Comment by yurishkuro** [comment]
@tiffon @everett980 please take a look

**Comment by everett980** [comment]
Thanks for raising!
I have a change to ancestor-ids in [this pr](https://github.com/jaegertracing/jaeger-ui/pull/310)
I will verify that it fixes the issue for this trace (it should).
