### ISSUE TITLE
Enable an optional 'sign out URL' to be added to the Jaeger UI menu

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-ui#347]
## Requirement - what kind of business use case are you trying to solve?

Enable an optional `Sign out` link to be presented on the Jaeger UI menu, for use with a reverse proxy providing authentication in front of the Jaeger UI.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently the UI menu items can be configured in the UI configuration - but it requires all of the menu items to be replicated to then add an extra item.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Create a new field, alongside the `label` and `items`, to optionally specify the sign-out URL. If defined, then include at the bottom of the menu, possibly with a separator above.

Other approach would be for user to create a new menu - but currently this would still require replicating the current "About Jaeger" menu items, unless a mechanism is provided to indicate that a menu is in addition to default menus.

**Comment by yurishkuro** [comment]
Internally we don't use the existing menu, we fully replace it. I am not sure that menu is particularly useful when Jaeger is deployed inside the company. Most of these items are only relevant to people charged with deploying Jaeger, not the end users. So it seems like it's completely fine to replace it.

If people really want to keep it, we could add a config flag for "keepAboutJaeger".

![image](https://user-images.githubusercontent.com/3523016/54372857-9ace8880-4652-11e9-9843-192339db7935.png)

**Comment by objectiser** [comment]
An alternative suggestion, that would be more general - provide an `url` field in the menu. If set, then will be used in conjunction with the label to define a button in the header instead of a dropdown menu.

This would give users the ability to have a combination of dropdown menus and buttons in the header. So for our use case, we could have an "About" menu with help sub-item etc, and a "Log Out" button, e.g.
```
  "menu": [
    {
      "label": "About",
      "items": [
        {
          "label": "Help",
          "url": "https://www.jaegertracing.io/docs/latest"
      ]
    },
    {
      "label": "Log Out",
      "url": "..."
    }
  ]
```

**Comment by yurishkuro** [comment]
I thought that was already supported - @tiffon

**Comment by tiffon** [comment]
@objectiser The format you described is already supported:

```js
menu: [
  {
    label: 'GitHub',
    url: 'https://github.com/uber/jaeger',
  },
  {
    label: 'About Jaeger',
    items: [
      {
        label: 'GitHub',
        url: 'https://github.com/uber/jaeger',
      },
      {
        label: 'Docs',
        url: 'http://jaeger.readthedocs.io/en/latest/',
      },
    ]
  }
]
```

![Screen Shot 2019-03-21 at 1 18 07 PM](https://user-images.githubusercontent.com/2304337/54771568-f0b7a900-4bdb-11e9-85dc-80c3400cf49e.png)

**Comment by objectiser** [comment]
Ok great, thanks.

**Comment by objectiser** [comment]
@tiffon Quick question - when I define a "log out" button in the header with a relative URL, it opens a new tab. Is there any way currently to prevent it opening the new tab, and just logging out the current tab?

**Comment by yurishkuro** [comment]
I seem to recall there was a PR to add a `target` attribute to the links. Not sure if we added that to the docs.

**Comment by objectiser** [comment]
@yurishkuro Thanks Yuri, that worked (`anchorTarget` set to `_self`).

**Comment by tiffon** [comment]
@yurishkuro Thanks for calling that out. I'll add a ticket to beef up the docs.
