### ISSUE TITLE
The maximum search lookback should be the trace retention period

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#356]
The lookback option in the search form, on the search page, should have the full retention period of traces as the max option. Currently, it is hardcoded to two days, but the retention period is configurable.

@vprithvi, @jaegertracing/elasticsearch is it possible for the query service to know this retention so it can be passed into the UI, dynamically? The alternative is to make a field in the UI config, but it would then need to be maintained as part of a deployment rather than adjusting, automatically.

**Comment by yurishkuro** [comment]
Retention period is usually configured in the storage, query-service often doesn't know about it. I would make it a param in the UI config.

**Comment by everett980** [comment]
How does search interact with archived traces? Are archived traces only accessible via `/trace/${archivedID}` or can they show up in search results as well?

**Comment by yurishkuro** [comment]
@everett980 the handler for `/trace/${archivedID}` automatically falls back to archive storage if it doesn't find the trace in the main storage
