### ISSUE TITLE
 “”find trace”Button is not obvious enough

### ISSUE THREAD

**Issue by wuyupengwoaini** [jaegertracing/jaeger-ui#362]
<img width="232" alt="bbbb" src="https://user-images.githubusercontent.com/5652901/55222108-049b8480-5246-11e9-8733-33d01280c4df.png">

Could add color to the button so that it will be obvious enough  to see it  at a glance

**Comment by rneha725** [comment]
for design antd is followed, there is no direct way to change the colour. But using some other approach it can be.

**Comment by rneha725** [comment]
https://ant.design/docs/react/customize-theme
