### ISSUE TITLE
Remove UNSAFE lifecyle methods from React components

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#374]
### Requirement - what kind of business use case are you trying to solve?

Remain compatible with React upgrades.

### Problem - what in Jaeger blocks you from solving the requirement?

Some code needs to be changed. See the `UNSAFE_*` methods in [The Component Lifecycle](https://reactjs.org/docs/react-component.html#the-component-lifecycle).

### Proposal - what do you suggest to solve the problem or improve the existing situation?

Do not use the unsafe methods.

**Comment by tklever** [comment]
By my check, branch master no longer has any component methods of componentWillMount, componentWillUpdate, or componentWillReceiveProps or with an UNSAFE_ prefix.

I think this issue is safe to close.

**Comment by yurishkuro** [comment]
Thanks @tklever , that's great!
