### ISSUE TITLE
Log js client side errors in our server side logs

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-ui#39]
We don't track errors in the UI, and rely on users to contact us when things break.

Adding such logging would allow for better discovery of js errors.

**Comment by yurishkuro** [comment]
+1. I assume there are existing solutions for that though, rather than us building something custom.

**Comment by vprithvi** [comment]
Yes, tools like [Sentry](https://sentry.io/welcome/), [Usersnap}(https://usersnap.com/), etc allow for this.
Ideally, we'd add an extension point that people can plug some solutions into.

**Comment by yurishkuro** [comment]
Google Analytics may support that

**Comment by tiffon** [comment]
Google analytics does support this:

https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions

The [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) and [`window.onunhandledrejection`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection) (chrome only) can be used for this.

**Comment by Dieterbe** [comment]
do i understand this right that people who have deployed jaeger in their environment will automatically have their jaegers send errors to a GA account owned by the jaeger team?
is there any chance confidential information might leak? e.g. from data in logs or spans. this is a bit concerning to me.

**Comment by yurishkuro** [comment]
it is opt-in, there is no default GA app id in the code.

**Comment by Dieterbe** [comment]
Great thanks Yuri .
