### ISSUE TITLE
String tags are being interpreted as numbers

### ISSUE THREAD

**Issue by panjunDev** [jaegertracing/jaeger-ui#396]
hello,friend
two questions:

1. 

i write a tag like this
![image](https://user-images.githubusercontent.com/16041012/59916036-b36bed00-9450-11e9-9bb9-16c4195b27cc.png)

but jaeger-ui show error,like this
![image](https://user-images.githubusercontent.com/16041012/59916080-caaada80-9450-11e9-80b7-66e2ef38372a.png)

1. 
i write a tag like this
![image](https://user-images.githubusercontent.com/16041012/59916207-1eb5bf00-9451-11e9-9a7c-e45f52f351e4.png)

![image](https://user-images.githubusercontent.com/16041012/59916169-08a7fe80-9451-11e9-99c7-dad265c35169.png)

![image](https://user-images.githubusercontent.com/16041012/59916166-06de3b00-9451-11e9-9985-0c8e99a82093.png)

**Comment by pavolloffay** [comment]
cc @tiffon

**Comment by tiffon** [comment]
We try to JSON parse values so we can format JSON strings. Looks like we missed an edge case. We should probably limit attempting to parse values to when the value starts with either `{` or `[`.

https://github.com/jaegertracing/jaeger-ui/blob/d5078329e2021817c0894b7a453d0b22564406a1/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx#L26-L32

Thanks for filing this!

**Comment by Cekonieczny** [comment]
Hi, I have similiar issue. Is there any workaround maybe?
![jaeger_string_to_number](https://user-images.githubusercontent.com/41113078/62695652-0c7aea80-b9d7-11e9-8452-0572b00d901e.jpg)

**Comment by Cekonieczny** [comment]
Hi, I have a similiar issue. Is there currently any workaround on that?
![jaeger_string_to_number](https://user-images.githubusercontent.com/41113078/62696040-e7d34280-b9d7-11e9-8ca8-ddc8c1dd667d.jpg)
