### ISSUE TITLE
search within a time region, not only a "lookback window"

### ISSUE THREAD

**Issue by Dieterbe** [jaegertracing/jaeger-ui#401]
sometimes you know you're looking for a trace from around a certain time.
so it would be nice to have date-time start/end input fields, similar to a tool like grafana or kibana

**Comment by tiffon** [comment]
If I follow correctly, this functionality is already available by selecting the "Custom Time Range" lookback:

<img width="430" alt="Screen Shot 2019-06-29 at 12 33 01 AM" src="https://user-images.githubusercontent.com/2304337/60379716-b85b0e80-9a05-11e9-990a-d0857ff3a5a7.png">
<img width="436" alt="Screen Shot 2019-06-29 at 12 33 09 AM" src="https://user-images.githubusercontent.com/2304337/60379717-b85b0e80-9a05-11e9-80bf-682638aebf6a.png">

**Comment by Dieterbe** [comment]
Oh my bad. Thanks !
