### ISSUE TITLE
Error span not shown as error

### ISSUE THREAD

**Issue by tschechniker** [jaegertracing/jaeger-ui#413]
Hi,

i'm currently testing jaeger with SpringBoot and i'm unable to get a span marked as error. The http response code is 500 but the span is still not marked as error.

What is the logic behind the error marking? When does jaeger know an error occoured? Do i have to add something to my SpringBoot config?

I'm Using SpringBoot 2.0.9 and the cloud-started 1.0.3 dependency. 

Thansk for your help!

Tobias

**Comment by yurishkuro** [comment]
Jaeger displays errors when spans have a tag `error=true`. If you don't have those tags, it's an issue with the instrumentation you're using, please open a ticket there.

**Comment by RouR** [comment]
Does it have another ui-tags? (like warning)
Please add it to documentation.

**Comment by yurishkuro** [comment]
`error=true` is the official OpenTracing-way to mark error spans.
