### ISSUE TITLE
Following readme does not make UI working

### ISSUE THREAD

**Issue by Tchoupinax** [jaegertracing/jaeger-ui#423]
Hello,

I have a problem while contacting the api. I started jaeger-ui on port 3000 and a jaeger-all-in-one on standard port (16686). Ui works well on browser but requests to API failed. In network inspector, i see that the reached url is `https://localhost/api/services`. However my API is on port 16686 and when i hit `http//localhost:16686/api/services` in my browser i have the expected answer.

I read that it exists a "proxy" but i have no idea what it does.
Is it normal that following readme instructions does not make it working ? 

Thank you for your time :)

**Comment by namit081** [comment]
I am having the same issue. I also want to package the UI using ```yarn build``` and want to specify a custom proxy endpoint in it instead of the default ```localhost:<ui-port>```

**Comment by tiffon** [comment]
How are you running / serving the UI?

To run the UI locally and while using the jaeger-all-in-one as the data source, the UI should be run in dev-mode. Which is to say:

```sh
$ yarn start
```

This serves the UI via a light node server which will proxy requests according to the config in the project, e.g. to `localhost:16686`.

https://github.com/jaegertracing/jaeger-ui/blob/1e26e570cb6daea637c778ff5feac7aac99e13c3/packages/jaeger-ui/src/setupProxy.js#L18-L28

Are you running the UI via `yarn start` or serving the files in some other way?

**Comment by tiffon** [comment]
@Tchoupinax Did you get the UI up and running?

**Comment by Tchoupinax** [comment]
Hello,

Yes it works now. One night i leave my pc without having it working. The next morning i open my pc, launch `yarn`and it works. It was a nightmare... x). But it worked for me, this day and others, so i will close this issue.

Thank you for your support ! :)
