### ISSUE TITLE
Promote @everett980 to admin

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#448]
With @tiffon leaving Uber we would like to promote @everett980 to an admin in the UI repository.

@jaegertracing/jaeger-maintainers

**Comment by jpkrohling** [comment]
+1, more than deserved:

![image](https://user-images.githubusercontent.com/13387/64844848-0943d180-d609-11e9-81df-d9c475baf0e2.png)

**Comment by objectiser** [comment]
+1

**Comment by tiffon** [comment]
+1

**Comment by yurishkuro** [comment]
Done. Congrats @everett980 !

![image](https://user-images.githubusercontent.com/3523016/64869882-419ade00-d610-11e9-84e6-7b73284da539.png)
