### ISSUE TITLE
Dependencies graph not showing when using spans produced by events

### ISSUE THREAD

**Issue by DotSpy** [jaegertracing/jaeger-ui#451]
Hello,
I'm using io.opentracing.contrib:opentracing-rabbitmq-client with opentracing-spring-web and when i'm reporting spans to jaeger i get this picture:
![Screenshot from 2019-09-17 16-34-15](https://user-images.githubusercontent.com/11577813/65046578-95d3f400-d969-11e9-8751-d05338a21f32.png)
but in dependencies nothing shown
![Screenshot from 2019-09-17 16-37-04](https://user-images.githubusercontent.com/11577813/65046647-b439ef80-d969-11e9-8d32-e019a94ff7fe.png)
as i understand it's because events coming via `"refType": "FOLLOWS_FROM"`, is there any ability to draw this dependencies?

**Comment by objectiser** [comment]
I think it might be more about the dependency code looking for `client` and `server` span kinds, rather than `producer` and `consumer`.

Would you be interested in submitting a PR in the https://github.com/jaegertracing/spark-dependencies repo to fix this?

**Comment by DotSpy** [comment]
I will have a look on it on next week

**Comment by DotSpy** [comment]
> I think it might be more about the [dependency code](https://github.com/jaegertracing/spark-dependencies/blob/master/jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/SpansToDependencyLinks.java#L128-L163) looking for `client` and `server` span kinds, rather than `producer` and `consumer`.
> 
> Would you be interested in submitting a PR in the https://github.com/jaegertracing/spark-dependencies repo to fix this?

I will have a look on it, probably at the end of next week

**Comment by DotSpy** [comment]
@objectiser I did some small work for it, would be great if u can review PR and add ur comments
