### ISSUE TITLE
question about DeepDependencyGraph 

### ISSUE THREAD

**Issue by Sasasu** [jaegertracing/jaeger-ui#454]
The question is: 

1. what is DeepDependencyGraph?
2. how to enable DeepDependencyGraph?
3. will jaeger-query provide a new API for DeepDenpendencyGraph (dependency v3)?

**Comment by everett980** [comment]
DeepDependencyGraph is a new dependency visualization that aims to replace the old "Dependencies" view (now called System Architecture).
The old view included all edges present in Jaeger data, which could easily become overwhelming, and did not have any means for visualizing dependencies more than one hop away.
The new DeepDependencyGraph view takes a service and optionally an operation name to filter down this dependency data. It also allows you to view all the hops of dependencies, both up and down stream.

Currently I believe it is only available in the OSS version by clicking the "Deep Dependency Graph" button on the Search Results view:
![image](https://user-images.githubusercontent.com/3471184/72389548-a0737f80-36f6-11ea-943f-426446c5478e.png)
However this will build the dependencies off of _only_ the data present in the current search results.

I'm not sure what the state/timeline is, but we do hope to open source the flink job that generates our full dependency data. @vprithvi do you have any more info on when our solution will be available or if/how others should roll their own endpoint?
