### ISSUE TITLE
Jaeger UI is not opening in IE 11.

### ISSUE THREAD

**Issue by bulataleev** [jaegertracing/jaeger-ui#456]
## Jaeger UI is not supported by IE 11
Steps to reproduce: 
1. Start the jaeger UI 
[https://github.com/jaegertracing/jaeger-ui](https://github.com/jaegertracing/jaeger-ui)
2. After deploy open the url and copy past it to the IE 11 browser
3. In developer mode in Console I see js syntax erros.

**Comment by jkowall** [comment]
IE 11 is end of life in 9 months (June 2022) and Microsoft has moved to Chromium-based Edge. I would suggest we close this out.
