### ISSUE TITLE
Signalize missing spans

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-ui#462]
Jaeger UI should let users know that trace might contain more spans if it is possible to know spans are missing in the trace.

At the moment UI shows missing root span:
![Screenshot of Jaeger UI](https://user-images.githubusercontent.com/5618424/66487850-52266300-eaad-11e9-9967-af1dfac33462.png)

However this information could be better presented in the Gantt chart:
![Screenshot of Jaeger UI (1)](https://user-images.githubusercontent.com/5618424/66487858-55215380-eaad-11e9-8be1-e3af4ee6c430.png)

The UI has also knowledge if there are spans missing in the middle. At the moment it does not show any information about missing spans - there is only warning in spans with missing parent about clock skew. The following screenshots show a trace with a missing middle span.

![Screenshot of Jaeger UI (2)](https://user-images.githubusercontent.com/5618424/66488204-dd9ff400-eaad-11e9-93b3-f36cfc23b607.png)

![Screenshot of Jaeger UI (4)](https://user-images.githubusercontent.com/5618424/66488224-e4c70200-eaad-11e9-840a-f234db494ff7.png)

# Proposals
## Missing root span
* show it also in the Gantt chart
* show a tooltip with explanation

## Missing middle spans(s)
* show it on the trace search screen. The number of spans could be like `2+` and tooltip explaining that spans have been created but didn't reach storage.
* show it in the Gantt chart on the place where spans are missing with an explanation.

**Comment by yurishkuro** [comment]
Showing the count of missing spans seems counterintuitive to me, since there's no way of knowing exactly how many spans are missing from the trace (we could be missing a whole branch).

Another alternative is to show an indicator of the overall trace quality, which could be drilled down for the summary of all issues, not just missing spans. I think Lightstep recently added something like that to their UI (although it may be at the service level, not trace level, but the algorithm actually applies to a single trace and service-level is an aggregation).

One challenge we had with this kind of indication is that the trace quality today is calculated in Java in a [Flink job](https://github.com/jaegertracing/jaeger-analytics/tree/master/tracequality-job). Rather than maintaining both Go and Java versions of the same logic, perhaps we should consider running a Java component for queries - we do this internally where query-service/analytics actually proxies to a Java service.

**Comment by objectiser** [comment]
Sounds like it would complicate the architecture.
We may also want the trace/spans enriched with the quality score so that they can be used in subsequent analysis - so not just on the query side. However realtime analysis without post processing pipeline might be difficult.

**Comment by pavolloffay** [comment]
A trace quality is certainly a better way of doing this, however the UI for sure knows that spans are missing in the middle and it should signalize it. At the moment this information is completely missing.

**Comment by pavolloffay** [comment]
Somehow related is https://github.com/jaegertracing/jaeger/issues/1870. It seems users might not understand what `missing-root-spans` means.

**Comment by yurishkuro** [comment]
We may want to change this to the behavior we used to have where "best root" was selected and used to assign the trace name. It was misleading in the past, but now the span will have a warning that it's missing the parent span, so the information will be preserved.

However, we may still have a case of multiple roots, where the current message is appropriate.

Is there a more intuitive strings than no-root-span? How about "cannot determine trace name" or "trace-name-undefined"?

**Comment by pavolloffay** [comment]
> Is there a more intuitive strings than no-root-span? How about "cannot determine trace name" or "trace-name-undefined"?

All of them are fine. However most importantly users have to realize what is the trace name and from what it is derived. I would add a tooltip explaining it.

**Comment by Stono** [comment]
As an end user - I'd be happy being able to set a time offset.
The missing spans for me are caused by commit latency on my ES index.
So if i was enable to set `--time-offset=1m` which would exclude the latest 1minute - i'd be happy.  We don't need ultra real time traces, but we do only want to show complete ones.

**Comment by pavolloffay** [comment]
> So if i was enable to set --time-offset=1m which would exclude the latest 1minute - i'd be happy.

Do you mean that jaeger query would not return data younger than 1 minute? I don't think we want to do this. I still think it's better to signalize missing spans in UI.

**Comment by Stono** [comment]
Yes, that’s exactly what I’m asking for the ability to control.  As a (very heavy) user of jager I can tell you that getting a trace with spans all over the place is useless, we just sit there refreshing until it is complete - which takes about a minute.

It leads to many support requests from our app teams who think it’s broken etc.  I’d much rather be able to say “traces take X minutes to become available” and I know my users would be fine with that too.

**Comment by yurishkuro** [comment]
Introducing 1min offset is a simple solution to this problem. I don't really know how else we can identify if spans are missing.

**Comment by pavolloffay** [comment]
From gitter

> Hi,
I would like to ask whether it is normal for invalid parent span IDs to appear frequently in Trace? If not, what are the reasons for this phenomenon? (I did not configure the persistent storage of jaeger)

**Comment by liguangcheng** [comment]
> From gitter
> 
> > Hi,
> > I would like to ask whether it is normal for invalid parent span IDs to appear frequently in Trace? If not, what are the reasons for this phenomenon? (I did not configure the persistent storage of jaeger)

I often reproduce the problem that there is no root span here. Is there a conclusion why this is caused?

**Comment by liguangcheng** [comment]
> From gitter
> 
> > Hi,
> > I would like to ask whether it is normal for invalid parent span IDs to appear frequently in Trace? If not, what are the reasons for this phenomenon? (I did not configure the persistent storage of jaeger)

Is this just a UI issue？

**Comment by knightley** [comment]
> > From gitter
> > > Hi,
> > > I would like to ask whether it is normal for invalid parent span IDs to appear frequently in Trace? If not, what are the reasons for this phenomenon? (I did not configure the persistent storage of jaeger)
> 
> I often reproduce the problem that there is no root span here. Is there a conclusion why this is caused?

I fix a no root span issue by sleep 1 second before my program exits
