### ISSUE TITLE
Support trace-scoped external links similar to tag links

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#465]
Currently Jaeger allows to configure custom external links using Link Patterns (https://www.jaegertracing.io/docs/1.14/frontend-ui/#link-patterns).

@rwkarg asked for similar links at the trace level:

> to link out to Kibana to view telemetry events for the current Trace (from the Trace view)

**Comment by yurishkuro** [comment]
@rubenvp8510 could you please create a PR for documentation?

https://www.jaegertracing.io/docs/latest/frontend-ui/

**Comment by rubenvp8510** [comment]
@yurishkuro sorry I forgot it, I'll create one.

**Comment by william-tran** [comment]
I've found a bug: only traceID and traceName are usable as keys. PR coming shortly.
