### ISSUE TITLE
Issue with Jaeger UI visualizing span with multiple parents

### ISSUE THREAD

**Issue by ppatierno** [jaegertracing/jaeger-ui#467]
Hi,
I am working on adding Jaeger tracing support to the [Strimzi](http://strimzi.io) HTTP bridge component which exposes the Kafka cluster through an HTTP RESTful API.
An HTTP client (producer/consumer) can connect to the bridge via HTTP and sending/receiving Kafka messages through HTTP requests on specific endpoints.
I am having a use case where a new span created by the bridge could have multiple parents; let me explain better.

An HTTP consumer sends a GET request to a specific endpoint for getting Kafka messages, so for doing an actual "poll" operation (in Kafka terms).
With just one HTTP GET it's able to get more Kafka messages (in one shot) encoded in JSON format into the HTTP response from the bridge.
Now, if these Kafka messages have already tracing information brought via headers (i.e. uber-tracer-id), the new "poll" span which the bridge creates, after getting messages, should be somehow "follows-from" all of them.
The things become more interesting saying that the Kafka messages could have different uber-tracer-id(s) because they could be sent by different producer applications (or just one producer) in different times or; it's also true the opposite, that one HTTP producer could send more Kafka messages encoded as JSON in the HTTP request body in one shot, so the Kafka messages spans will have the same uber-tracer-id having as parent one "send" operation span.

Coming back at the consumer side, my question is about having a span with multiple parents.
I noticed that using a child-of or a follows-from relationship, puts the "poll" span just under one of the spans related to the received message and not under both.
First use case.

- an HTTP producer sends two messages in one shot (so just one "send" span with two children "To_test") ... which is fine
- the HTTP consumer polls for messages, the bridge reads them from Kafka so the two "From_test" children of related "To_test" which is fine, but the newly created "poll" has as a parent just one of them ... not both.

![scenario_1](https://user-images.githubusercontent.com/5842311/67001736-af886880-f0da-11e9-8553-695b6137d625.png)

Other than the picture, the scenario_1.txt shows that "poll" has actually two references to same trace-id (about the "send") and different "span-id" (related to the two messages read) but it's visualized under just one of them.

Second use case:

- an HTTP producer sends two messages with two different HTTP requests, so two different "send" spans with related "To_test" ... which is fine
- the HTTP consumer polls for messages,  the bridge reads them from Kafka so the two "From_test" children of related "To_test" which is fine (they are part of the two different traces), but the newly created "poll" has as a parent just one of them ... not both.

![scenario_2_01](https://user-images.githubusercontent.com/5842311/67001768-bca55780-f0da-11e9-85be-302a21730310.png)

![scenario_2_02](https://user-images.githubusercontent.com/5842311/67001775-bfa04800-f0da-11e9-9a41-e4260334449a.png)

In the first picture the "poll" span is there and it's actually in the scenario_2_01.txt.
From the file you can see that it has two references (different trace-id) but despite that it's visualized just in one of the pictures and not in the other one (where taking a look at scenario_2_02.txt doesn't have the "poll" span at all).

In both cases the references added to the "poll" span are correct as you can see in the attached JSON, so it sounds to me an issue on the Jaeger UI visualization.

[scenario_1.txt](https://github.com/jaegertracing/jaeger-ui/files/3738788/scenario_1.txt)
[scenario_2_01.txt](https://github.com/jaegertracing/jaeger-ui/files/3738789/scenario_2_01.txt)
[scenario_2_02.txt](https://github.com/jaegertracing/jaeger-ui/files/3738790/scenario_2_02.txt)

**Comment by objectiser** [comment]
Hi @ppatierno, thanks for reporting this.

There are a couple of issues raised by your scenarios.

1) When a span within a trace instance has multiple references, it would be useful to visualise them in some way - i.e. a join pattern.

a) If the references are to spans within the same trace instance, then providing some way to link them or provide a way to highlight the linked span would be useful.
b) If the references are to spans in another trace, then having an anchor in the source span visualisation that could result in navigation to the target trace id (and possibly highlighting the target span) would be nice - although consideration would be required for how to deal with (i) large number of references (as the batch of kafka messages could be quite large), and (ii) how to deal with situations where the target trace id does not exist (i.e. wasn't sampled).

2) I think the scenario highlights an issue with how parents are determined within the clients (possibly just Java client). At the moment, if a set of Follows From references are added to the span on creation, with no ChildOf explicitly defined, it will use the first reference's trace id and span id as its parent.

However in the case where all of the references belong to different trace instances, this new span perhaps should be a root span for a new trace instance, representing a join of the other trace instances. @yurishkuro thoughts?

**Comment by everett980** [comment]
I believe this has been addressed by [PR#477](https://github.com/jaegertracing/jaeger-ui/pull/477). Please reopen if I am mistaken.
