### ISSUE TITLE
Configure max limit result in SearchForm.js

### ISSUE THREAD

**Issue by GabrielDyck** [jaegertracing/jaeger-ui#478]
## Requirement - what kind of business use case are you trying to solve?

Hello!
I want to configure searchform "Limit Results" max property. 

## Problem - what in Jaeger blocks you from solving the requirement?

I navigated the code and saw that is hardcoded 1500 as max limit in SearchForm.js

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I think we can configure like environmet value the max limit, and if isn't configured, we can set 1500 as default value.

What do you think? 

Thank you !

**Comment by everett980** [comment]
@GabrielDyck This definitely seems like a reasonable change.

You can add a field to the [config.search](https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/types/config.tsx#L45) called `maxLimit`, and add the current value as the default in the [default config](https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/constants/default-config.tsx). Then call [`getConfig('search.maxLimit')`](https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/utils/config/get-config.tsx) on [this line](https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js#L446).

**Comment by GabrielDyck** [comment]
Hi @everett980 !
I've just created a pull request with the changes.
Thank you!
