### ISSUE TITLE
Support multiple layers of nodes and edges in plexus

### ISSUE THREAD

**Issue by everett980** [jaegertracing/jaeger-ui#482]
This is a tracking issue to encompass the work done across many PRs to achieve this goal.

Brief overview of functionality covered in first revision:
* Users must specify a single definition for calculating the size of nodes in the graph
* Users can specify one or more other layers of nodes that are sized to fit based on their corresponding measured node.
* Users can specify either HTML or SVG renderers for node layers.
* Users can specify multiple layers of SVG edge layers.
* Users can specify unique or shared edge markers for SVG edge layers.
* Jaeger uses new plexus API.

List of PRs by author:
([@tiffon](https://github.com/tiffon) in [#426](https://github.com/jaegertracing/jaeger-ui/pull/426), [#428](https://github.com/jaegertracing/jaeger-ui/pull/428), [#422](https://github.com/jaegertracing/jaeger-ui/pull/422), [#420](https://github.com/jaegertracing/jaeger-ui/pull/420), [#419](https://github.com/jaegertracing/jaeger-ui/pull/419), [#416](https://github.com/jaegertracing/jaeger-ui/pull/416), and [#414](https://github.com/jaegertracing/jaeger-ui/pull/414))

**Comment by tiffon** [comment]
@everett980 Plexus supports measurable SVG node layers. So, the list item

>Users can specify either HTML or SVG renders for non-measure-able node layers.

Can just be

- Users can specify either HTML or SVG renderers for node layers.

Also, what outstanding work is this ticket related to? Everything you've listed is done.

**Comment by everett980** [comment]
Updated description.

This issue was made as a tracking ticket for the changelog to connect multiple PRs to the effort, as the changelog entry for this work would've otherwise been unwieldy.
