### ISSUE TITLE
Search results DDG looks incorrect for hotrod data

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#485]
@everett980 a bunch of edges in this graph are incorrect

<img width="1680" alt="Screen Shot 2019-11-18 at 5 40 47 PM" src="https://user-images.githubusercontent.com/3523016/69108817-af0d2580-0a2a-11ea-9f04-94218e818fc1.png">

**Comment by everett980** [comment]
@yurishkuro If you hit the "view traces" button on the node interactions popup do the traces show the same issue?
Thanks to recent changes there should only be one focal node if you revisit this now, but the edges themselves I'm not sure about. It's possibly they are reversed.

**Comment by yurishkuro** [comment]
I am seeing this with the latest release 1.15.1. Steps to reproduce:
 
1. Edit `examples/hotrod/docker-compose.yml` by replacing `all-in-one:latest` with `all-in-one:1.15.1`:
```diff
--- a/examples/hotrod/docker-compose.yml
+++ b/examples/hotrod/docker-compose.yml
@@ -1,7 +1,7 @@
 version: '3.7'
 services:
   jaeger:
-    image: jaegertracing/all-in-one:latest
+    image: jaegertracing/all-in-one:1.15.1
     ports:
       - "6831:6831/udp"
       - "16686:16686"
```
2. `docker-compse up`
3. open http://0.0.0.0:8080/, hit buttons 3 times
4. open http://localhost:16686/, select `dispatch` service, search for traces, and hit DDG button.

**Comment by everett980** [comment]
I still haven't had a chance to dig into this further, but one issue could be that we aren't filtering paths to just `span.kind === 'server'` like we do in the flink job.

**Comment by yurishkuro** [comment]
I don't fully agree with how flink job does it anyway, but this doesn't sound like the issue at hand, because the graphs are just wrong, arrows pointing in the wrong directions, etc.

**Comment by cykl** [comment]
I'm still experiencing the same issue with 1.6.0. Most our DDGs look bogus with impossible arrows, mixed upstream / downstream dependencies etc. I might be able to share trace JSON if that might help.

**Comment by cykl** [comment]
Is a patch release planned?

**Comment by yurishkuro** [comment]
1.17 is coming up soon https://github.com/jaegertracing/jaeger/issues/2057
