### ISSUE TITLE
Very slow UI responsiveness when suggest operation from too many operations

### ISSUE THREAD

**Issue by sangda** [jaegertracing/jaeger-ui#505]
When there are too many operations, type in the operation box on the left was very slow: several seconds per character.

Steps to reproduce the issue:

Deploy Jaeger-UI
There are too many options in the operation box on the left
Attempt to type in the operation box
Describe the results you received:

Slow behaviour of the UI

Describe the results you expected:

Fast behaviour: quick match options.

My jaeger-query startup scripts：
nohup ./jaeger-query --span-storage.type=elasticsearch --es.server-urls=http://127.0.0.1:9200/  > query.log 2>&1 &

My browser: 
Chrome

My screenshot about Jaeger-UI:
<img width="685" alt="jaeger-ui-screenshot" src="https://user-images.githubusercontent.com/9910525/71711744-61fbdc00-2e3d-11ea-8d8a-1390a2af76b6.png">

**Comment by yurishkuro** [comment]
Operation names are not supposed to contain IP address and port numbers. Those are deployment details that can be recorded as span tags, but they are not part of the "operation name".

See OpenTracing Specification about the operation name: https://github.com/opentracing/specification/blob/master/specification.md#start-a-new-span

**Comment by sangda** [comment]
> Operation names are not supposed to contain IP address and port numbers. Those are deployment details that can be recorded as span tags, but they are not part of the "operation name".
> 
> See OpenTracing Specification about the operation name: https://github.com/opentracing/specification/blob/master/specification.md#start-a-new-span

The main problem is the operation too many, even not contain IP and port, it will not affect the speed of the search.

**Comment by yurishkuro** [comment]
It is not unusual to have several hundred operations in a service like an API gateway. But your screenshot shows 10,000 endpoints - is that really how many your service has?
