### ISSUE TITLE
Support trace view as a flame graph

### ISSUE THREAD

**Issue by hehe717** [jaegertracing/jaeger-ui#525]
I am implementing jaeger, it really looks nice.
But I got a problem.
I want to collect spans on one line in tracing view, but I cannot find way.

[As-IS]
![image](https://user-images.githubusercontent.com/19582090/74802459-49785000-531d-11ea-9ec7-51e1c30199da.png)

[To-Be]
![image](https://user-images.githubusercontent.com/19582090/74802513-74fb3a80-531d-11ea-8740-4de49b65f546.png)

Maybe I can't find the doc... could you help ?

**Comment by yurishkuro** [comment]
The challenge with this type of view is that sibling spans are not guaranteed to not overlap, so how should they be displayed in that case?
```
|----------------parent---------------|
    |---child1---|
                |---child2---|
```

**Comment by hehe717** [comment]
Yes.. I didn't think that part.

Datadog's tracing view  can be hint for this problem.  (they have implemented flame graph with open tracing )
`https://docs.datadoghq.com/tracing/visualization/trace/?tab=spantags`

**Comment by yurishkuro** [comment]
DD docs don't explain how the they deal with overlapping siblings, unless I missed it

**Comment by hehe717** [comment]
Right , closed this issue because of the challenge of `sibling spans does not guarantee to not overlap`

**Comment by n1ckdm** [comment]
I think this issue should be reopened. Flamegraph support for jaeger would be really useful for some of the systems I'm working with.

This tool takes a JSON dump from jaeger and converts it to be read by FlameGraph:

https://github.com/symbiont-io/jaeger-flamegraph

Might be some clues there for how to handle the overlapping siblings?

I'd be interested in working on a PR for this if there's appetite for it?

**Comment by ColinBradley** [comment]
FWIW, I'd really like this feature too.
Datadog and Raygun both have flame graph esk views and they are incredibly helpful.

The sibling overlapping issue is a small edge case you can handle by just putting them on different rows. It's fine - parallel work is just messy.

Basically the entire logic is that spans should go on a new row if there is no room on a preceding row and never going higher than a parent. I've made and used a basic viewer like this in the past and it worked great.

**Comment by h1z3y3** [comment]
+1

**Comment by jingslunt** [comment]
+2
