### ISSUE TITLE
Unable to make the tracegraph and the configuration from file work

### ISSUE THREAD

**Issue by michaelyefet** [jaegertracing/jaeger-ui#537]
Currently while working with jaeger version 1.16.0 that runs on openshift I encounter two main issues
1) When i go to the tracegraph page wont show me valid info. I mean that i look at the count / error (top left) of specific operation in specific service i see 1 / 0 meaning it occurred only once and was successful that's incorrect and occurred many times. That obviously has an impact on the full and average duration (to be clear it occurred many times).
2) That might be a basic question but when working with the jaeger-query image I haven't been able to configure the ui using a file (things like maxLooback). 

If you could give me any direction on this issues that would be great.

**Comment by jkowall** [comment]
Can you please specify how you are calculating the DAG views? Is this utilizing the all in one Jaeger docker image,  Spark, or something else?
