### ISSUE TITLE
DDG should support messaging scenario

### ISSUE THREAD

**Issue by cykl** [jaegertracing/jaeger-ui#547]
## Requirement - what kind of business use case are you trying to solve?

I want to see asynchronous communications, ie. messaging, on DDGs.

## Problem - what in Jaeger blocks you from solving the requirement?

OpenTracing recommends to instrument messaging using FOLLOW_FROM references, producer / consumer kind and message_bus.destination tags. Unfortunately, DDG doesn't use this information and ignores asynchronous communications. 

## Minimal test case

Following code produces a trace with a producer and a single consumer (root span is here because of #546):

```java
public class Messaging {

    public static void main( String[ ] args ) throws InterruptedException {
        var topic = "topic1";

        try (var producerTracer = createTracer( "producer" )) {
            var rootSpan = producerTracer.buildSpan( "Root" )
                    .withTag( Tags.SPAN_KIND, "server" )
                    .start( );

            var producerSpan = producerTracer.buildSpan( "To" )
                    .asChildOf( rootSpan )
                    .withTag( Tags.SPAN_KIND, "producer" )
                    .withTag( Tags.MESSAGE_BUS_DESTINATION, topic )
                    .start( );

            Thread.sleep( 10 );
            producerSpan.finish( );
            rootSpan.finish( );

            try (var consumerTracer = createTracer( "consumer" )) {
                var consumerSpan = consumerTracer.buildSpan( "From" )
                        .addReference( References.FOLLOWS_FROM, producerSpan.context( ) )
                        .withTag( Tags.SPAN_KIND, "consumer" )
                        .withTag( Tags.MESSAGE_BUS_DESTINATION, topic )
                        .start( );

                Thread.sleep( 50 );
                consumerSpan.finish( );
            }
        }
    }

    static Tracer createTracer( String serviceName ) {
        return new JaegerTracer.Builder( serviceName )
                .withSampler( new ConstSampler( true ) )
                .withReporter( new RemoteReporter.Builder( ).withSender( new UdpSender( ) ).build( ) )
                .build( );
    }
}
```

I had expect to see a DDG with a producer and a consumer node with and edge between the two. A visual difference between RPCs and messaging would be great.

**Comment by yurishkuro** [comment]
to clarify, are you referring to DDG rendering of search results?

**Comment by cykl** [comment]
Yes.

**Comment by cykl** [comment]
Is DDG also used to refer to _System Architecture_ or are there other DDGs ?

**Comment by yurishkuro** [comment]
Internally we have a batch job that generates DDG data from all traces, and allows inspection without any search results. The tension comes from the difference in the batch job logic and the UI-only logic that tries to recreate the same data from search results.

I agree that we need to fix the logic in the UI at least (since it's open source). The transitions between services can be detected via change in the service name, without looking at span.kind tags. However, sometimes services have recursive calls, usually to another service instance, e.g. in sharded systems, but sometimes even recursively to itself. Those can be detected by changes to client_uuid in the process tags, but in case of recursive calls to itself, only through span.kind tags (incidentally, OpenTelemetry has a "remote" flag on the span context that would've been helpful here).

**Comment by cykl** [comment]
Thanks for the clarification. 

Adding support of asynchronous communications to DDGs computed from search results would be great and was my initial request.

That said, we are prototyping a streaming job to discover synchronous & asynchronous communications topologies to circumvent _System Architecture_ limitations. It seems quite similar to a _batch job that generates DDG data from all traces_. Avoiding NIH syndrome and being able to leverage jaeger-ui would be awesome. Where can I learn more about missing bits in OSS version? A description of the data model, query endpoints and entry points in -ui would be of great help. If precomputed DDGs match our needs, we would prefer to integrate with / contribute to Jaeger rather than rolling our one back-end & front-end.

**Comment by yurishkuro** [comment]
The "batch job" that we run internally is not really a batch job, it's an Apache Flink streaming job running on the stream of spans in Kafka. We never had time to properly open source it, instead we just copied the code to https://github.com/jaegertracing/jaeger-analytics-flink. It's semi-usable, but not productionalized in any way. So far nobody stepped up to put some extra effort required to make this production-ready. The repo currently contains the job that generates data for System Architecture graph.

We can easily copy the code that generates DDG to this repo as well, if you're interested in doing the extra work to productionalize it.

**Comment by cykl** [comment]
Dumping the code as it is will surely help us, and likely others Jaeger users, for our internal needs. I don't promise anything, but we will try to contribute back to the community.

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger-analytics-flink/pull/10

**Comment by cykl** [comment]
I just tested latest revision and that #557 solves this issue. Thanks!
