### ISSUE TITLE
Redirect trace/idWithoutLeading0s to trace/fullId

### ISSUE THREAD

**Issue by everett980** [jaegertracing/jaeger-ui#548]
## Requirement - what kind of business use case are you trying to solve?
This has manifested itself in a few ways. Presently, expanding/collapsing a row (but not expand/collapse all/one) is broken when viewing `/trace/ABC` when the response traceID is `00ABC`.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Upon receiving the trace, if its ID matches `/0+urlId/`, redirect to `/traceResponseID`

**Comment by yurishkuro** [comment]
> Upon receiving the trace, if its ID matches /0+urlId/, redirect to /traceResponseID

I think this is incorrect (doesn't match the title either). The rule should be:
  * if received ID len < 16, then redirect to ID left-padded with `0`s to len=16
  * elseif received ID len < 32m then redirect to left-padded with `0`s to len=32

NB: technically, the first check is optional and will be covered by the 2nd check, but will result in longer URLs for sites that are still using 64bit IDs.

**Comment by everett980** [comment]
> I think this is incorrect

For the purpose of making sure the id in the url matches the current trace's ID, this should always work. This is also future proof for larger than 32 character ids, or any existing cases of using other lengths.

> (doesn't match the title either)

By `fullId` I meant the full id that the backend responded with for the trace.

The UI should be flexible enough to handle whatever traceID the backend matched to the request ID.

**Comment by yurishkuro** [comment]
I see your point about redirecting to match the server response, but I think it translates to poor user experience where you need to wait for the whole trace to load into UI, only to be redirected and wait for the second time. Such behavior can be a fallback in case the server, for whatever reason, responds with a different trace ID, but I think the first step should be as I described: if the UI sees the URL with trace ID of different length than 16/32, it should pad it with 0s immediately and redirect, not waiting for the server response.

**Comment by everett980** [comment]
Redirecting should not have any perceptible impact to the user. For instance, the DDG view redirects on all visibility changes, but does not need to refresh or load new data unless the service or operation changes.

**Comment by everett980** [comment]
Ultimately the above approach would introduce other issues, so I simply handled another leading 0 case in the tracking file.
