### ISSUE TITLE
Custom Jaeger UI image integration with jaeger deployment

### ISSUE THREAD

**Issue by nehagupta84** [jaegertracing/jaeger-ui#553]
Hi All,

I have a requirement of modify jaeger ui, and i did made those changes now i want may jaeger ui to be integrated with rest of jaeger deployment components in kubernetes. How can i do that? Any help and suggestion is helpful.

Thanks
Neha

**Comment by yurishkuro** [comment]
The query service has a flag `--query.static-files` that you can provide to point it to a different build of the UI than what's being bundled in the Docker image.

**Comment by nehagupta84** [comment]
where can i find this flag?

**Comment by nehagupta84** [comment]
it means i have to change jaeger-query image also.

**Comment by yurishkuro** [comment]
not "also", that's the only image you need to change since it's where the UI is hosted. But you don't necessary need to _change_ the image, you can just deploy it with this extra flag passed.

**Comment by nehagupta84** [comment]
i am using "jaegertracing/jaeger-query:1.17.0" image of jaeger query, is it some parameter i can pass to point my custom jaeger ui image. Am not sure how can i make this change? Basically trying to remove this call 'https://at.alicdn.com/t/font_148784_v4ggb6wrjmkotj4i.woff'.

**Comment by yurishkuro** [comment]
You just need to pass a parameter when starting the docker image, e.g.
```sh
docker run -p 16686:16686 -e SPAN_STORAGE_TYPE=memory \
    -v path-to-ui-build:/jaeger-ui \.    # mount volume into container
    jaegertracing/jaeger-query:1.17.0 \
    --query.static-files /jaeger-ui      # point to mounted ui files
```

If you found a way to modify jaeger-ui build to bundle the fonts into the build, please open a PR, it's an open issue.

**Comment by nehagupta84** [comment]
how can u=i bundle this in kube deplyment file?
-v path-to-ui-build:/jaeger-ui \.

**Comment by yurishkuro** [comment]
I am not an expert on kube, can't help you there. I think it would be easier to build a custom image (using Docker staged builds, by starting with the existing 1.17 image and adding your files only as another layer), because otherwise you need to find a way to deploy the file bundle to the pods as well.

**Comment by nehagupta84** [comment]
i made a change in  config-overrides-antd-var.less in jaeger-ui for fixing the issue but am not sure how to bundle that change with jaeger-query now???  So basically if i can bring that change in jaeger-query and build a new image for jaeger-query and plug in that image with my kube deployment.

**Comment by nehagupta84** [comment]
Currently there is a restriction to view spans for last 2 days is there a way i can change it?

**Comment by everett980** [comment]
> Currently there is a restriction to view spans for last 2 days is there a way i can change it?

@nehagupta84 do you mean on the search page? If so, you can configure that maximum. See here: https://www.jaegertracing.io/docs/1.17/frontend-ui/#search-input-limit
