### ISSUE TITLE
DDG for search results is still wrong

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#554]
The HotROD graph is missing DB nodes. The redis and mysql services do show in the search results, as well as in the regular DAG graph, but not in DDG:

![image](https://user-images.githubusercontent.com/3523016/78200720-86c41780-745d-11ea-8044-1bf67c6d8652.png)

**Comment by rubenvp8510** [comment]
I'll review this one.

**Comment by rubenvp8510** [comment]
This happens because the transformation function filters spans to process only spans.kind = "server", it doesn't process `client` spans.

Is that the way it should work?

**Comment by yurishkuro** [comment]
I think we discussed it a number of times. No, I don't think it's correct. Any transition (as in parent-child span pair) from service X to Y should result in an edge in the graph. The only value there can be in looking at span.kind is if the service is calling itself recursively, vs. just having a bunch of inner spans, in the former we want X-X edge, in the latter - no edge.
