### ISSUE TITLE
Add display of span flags

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#556]
Currently it's difficult to find out if the trace was sampled with debug flag or not, one needs to look at trace JSON.

**Comment by everett980** [comment]
Could flags just be added as an additional table before/after/between the tags / processes tables?

![Screen Shot 2020-05-14 at 5 03 34 PM](https://user-images.githubusercontent.com/3471184/81985898-e721a980-9604-11ea-8565-d7007c4670df.png)

**Comment by yurishkuro** [comment]
they can be, but I think it would be a much heavier approach as far as UI elements go. Unless the new section is optional and only shows up when there's something there (similar to warnings). Even then it seems it would add a lot of visual bulk vs. one or two extra pills in bleak color in the row where span ID is shown.

**Comment by everett980** [comment]
> Even then it seems it would add a lot of visual bulk vs. one or two extra pills

Then should this be closed in favor of #575 which is specifically for the two pills?

**Comment by yurishkuro** [comment]
Duplicate of #575
