### ISSUE TITLE
Search in the top menu is easy to confuse with a button

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#563]
![image](https://user-images.githubusercontent.com/3523016/80154958-9df2b280-858e-11ea-880a-f3c792ef972b.png)

The Search comes right after the textbox for trace ID and looks like a button, whereas it's actually the currently selected menu item, so clicking on it does nothing. Instead, to search by trace ID one needs to hit Enter, which is not obvious. Some users are confused by that.

A better placement for this text box would be on the right, as shown in this duplicate ticket #670

![image](https://user-images.githubusercontent.com/3523016/102807485-b967c480-438c-11eb-81a1-54f14e88e433.png)

**Comment by everett980** [comment]
Disabling the navigation for the current page would prevent users from essentially refreshing by accident.
Adding a tooltip with the destination url would make it more obvious that it is a link.
And adding an interactive magnifying glass to submit the search would be better than exclusively relying on the user to hit enter.

**Comment by yurishkuro** [comment]
Magnifying glass sgtm, followed by a bit more horizontal space or a vertical line to separate the menu

**Comment by achesin** [comment]
I had this same issue where people have mentioned to me their confusion. We thought of potentially moving the search bar to the right hand side of the TopNav, away from the Search tab to decrease confusion.

**Comment by yoave23** [comment]
@yurishkuro I'll be happy to take it if no one is on it

**Comment by yurishkuro** [comment]
@yoave23 it's yours! Thanks.

**Comment by yoave23** [comment]
@yurishkuro how does this look?
![image](https://user-images.githubusercontent.com/3125539/104195340-2c63d880-542b-11eb-94ff-b55f0dc335e4.png)

**Comment by yurishkuro** [comment]
great!
