### ISSUE TITLE
Unable to get the of "maxLimit": 2000 in the UI das

### ISSUE THREAD

**Issue by narendra0356** [jaegertracing/jaeger-ui#565]
## Problem - what in Jaeger blocks you from solving the requirement?

I Have try to modify the query UI with the help of json file for update the "maxLimit" value.

"search": {
"maxLookback": {
"label": "3 Days",
"value": "3d"
},
"maxLimit": 2000

The "maxLookback" value has updated in UI dashboard but "maxLimit" is not updated. I got popup "value must be less than or equl to 1500".

**Comment by yurishkuro** [comment]
I changes the default config shown in the [documentation][1] to say `maxLimit: 1700` and tried running all-in-one: it seems that the setting was respected:

![image](https://user-images.githubusercontent.com/3523016/80404023-8ff2a980-888e-11ea-9fec-5abccb248318.png)

This may be an issue with your setup, perhaps you're not passing the config to the query service at all.

Feel free to re-open if you think there's still an issue with Jaeger.

[1]: https://www.jaegertracing.io/docs/1.17/frontend-ui/

**Comment by narendra0356** [comment]
Previous i use the jaeger-query:1.17.0  image. The image is not supported for update the maxLimt value in UI. When i use query: 1.17.1, them i am able to update the maxLimit value.   

Thanks yuri
