### ISSUE TITLE
Search returns results in different order every time

### ISSUE THREAD

**Issue by frankgreco** [jaegertracing/jaeger-ui#57]
**Description**
Multiple clicks on *find traces* returns results in different order every time

**Steps to reproduce the issue:**
report a bunch of traces and do multiple searches

**Describe the results you received:**
Multiple clicks on *find traces* returns results in different order every time

**Describe the results you expected:**
Expected some order every time according to the sort options defined

**Additional environment details (Browser, etc.):**
chrome

**Comment by yurishkuro** [comment]
is it the order or the content? Every time you run a search the timestamp is advanced, so the result set would be different.

**Comment by frankgreco** [comment]
It's the order. If I report 10 spans then view them in the ui (perhaps sorted by most recent), if I hit *find traces* 10 times I should expect the results to be in the same order every time.

Instead, what I'm seeing is the first trace is from 1 hour ago and then I'll search again (same criteria) and the first trace will be from 2 hours ago

**Comment by yurishkuro** [comment]
sounds like  bug then - cc @tiffon

**Comment by tiffon** [comment]
@yurishkuro Repeatedly issuing the same search request usually yields different results. This is requests with the same query parameters. Doesn't look like this is in the front-end.

**Comment by yurishkuro** [comment]
@frankgreco are you using Cassandra backend?

**Comment by frankgreco** [comment]
@yurishkuro for not I'm just using the all-in-one deployment

**Comment by yurishkuro** [comment]
I see - the memstore implementation likely doesn't provide stable search, because it uses hash maps internally. It's doable, but doesn't seem too important.

**Comment by tiffon** [comment]
I believe this is outside the scope of the UI. @yurishkuro Should we move this to jaeger core?

**Comment by frankgreco** [comment]
@tiffon couldn't the UI sort the result set by time?

**Comment by tiffon** [comment]
@frankgreco The results are (or should be) sorted by time by default. Is that not what you're observing?

And, by this, I mean the results are sorted by time within the UI. I cannot speak to the sort on the result set, in general.

**Comment by omeid** [comment]
I think having the trace id in the UI would avoid confusions like jaegertracing/jaeger#522.

**Comment by tiffon** [comment]
Going to go ahead and close this as it's not in the domain of the UI and has been deemed "doesn't seem too important" and "not too much of a priority"... e.g. there are no action-items from this.
