### ISSUE TITLE
Ignoring istio time span

### ISSUE THREAD

**Issue by tbiddu** [jaegertracing/jaeger-ui#570]
We are evaluating Jaeger UI to do distributed tracing and istio for service mesh. Ideally it should trace all istio proxy timing as well. But Jaeger does not show the istio proxy tracing span.

I am not finding any settings which will show istio time span as well. Any guidance will do.

**Comment by yurishkuro** [comment]
Istio is the one providing instrumentation and data, Jaeger doesn't have any say in that, it will display whichever data is sent. Please direct your question to the Istio project.
