### ISSUE TITLE
Remove quotes around values

### ISSUE THREAD

**Issue by smanolloff** [jaegertracing/jaeger-ui#571]
Currently, all values are surrounded by double quotes. This is redundant and, more importantly, confusing, when the message itself contains such quotes:

![Screenshot 2020-05-11 at 15 33 10](https://user-images.githubusercontent.com/6965111/81562159-05856c00-939d-11ea-8536-df427b5888ee.png)

**Comment by tiffon** [comment]
Thanks for creating this ticket.

Only string values are surrounded by double-quotes. The double-quotes are meant to indicate the value is a string. For instance, without them, the `"400"` would look like a number when it's actually a string. And, if the underlying value of the `"400"` were instead a number (e.g. `400`) it would not have the quotes.

For the second log message, the value is a string that itself contains double-quotes. Would it be less confusing if the inner quotes were escaped?

**Comment by smanolloff** [comment]
> For the second log message, the value is a string that itself contains double-quotes. Would it be less confusing if the inner quotes were escaped?

Certainly not. Isn't there a way to indicate value types via on-mouse-hover tooltip, or just via the value's text color (eg. blueish for numbers, brown-ish for strings, whatever)? 
Thanks
