### ISSUE TITLE
Graph duration problem

### ISSUE THREAD

**Issue by mohsensamiei** [jaegertracing/jaeger-ui#579]
Hi guys
See this image:

![jaeger-ui graph duration problem](https://img.techpowerup.org/200516/ee.jpg)

What's the matter?

**Comment by yurishkuro** [comment]
if your actual trace durations are something like 1.000001s, 1.000002s, 1.000003s, then the rounding could make them all look like 1s. I wonder how other dashboarding tools, e.g. Grafana, would handle such case. It's possible to implement extra intelligence in the axis to increase rounding precision automatically if identical axis labels are being generated.

**Comment by jkowall** [comment]
Closing due to stale. I don't really see the issue :)
