### ISSUE TITLE
Better naming for operations and grouping by operation type in trace summary

### ISSUE THREAD

**Issue by romilpunetha** [jaegertracing/jaeger-ui#582]
## Requirement - what kind of business use case are you trying to solve?

The operation names for mysql and mongo currently are the entire queries itself. Would be good to have the query as an attribute, with the operation name as `mysql.query`,`mongo.query`, `redis.query`, etc. This would simplify grouping not only by service name but also by operation types, which would also be good to have on the trace summary.

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger groups spans only by service name. It would be good to have if there's another section in the summary that groups by operation type. This would help better visualize the trace. eg. Lets say a particular trace spans across 5 services. The trace summarizes the names of these services, along with info like `15 http calls`, `10 mysql.query calls`, `3 mongo.query calls`... and so on.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

There's already `db.type` getting captured as an attribute. Possibly that could be used for better naming a db operation. Then, the UI could show a grouped version of these operations. This would allow a developer to better identify what the trace exactly contains without having to deep dive in it. Knowing that the trace spans across might not be that useful, but knowing that it does contain a lot of DB calls makes a difference.

**Comment by romil-punetha** [comment]
@annanay25

**Comment by jkowall** [comment]
I know this issue is quite old, and I was trying to replicate the issue here with the operation names. I'm not seeing this on my Jaeger instances across a few different applications. I'm not sure if this is related to the instrumentation we are using Otel, versus what you might have been using. @romilpunetha can you please post a screenshot showing the issue you are describing? 

Thanks
