### ISSUE TITLE
Individual spans in trace view grow in size on hover in Chromium

### ISSUE THREAD

**Issue by lucacasonato** [jaegertracing/jaeger-ui#589]
When hovering over individual spans in the trace view, spans seem to grow in horizontal height when the gray bar on the side is hovered or when a trace is clicked. I could only reproduce this behavior in Google Chrome, not in Firefox. I have attached videos of the issue below:

Does not work in Google Chrome: https://streamable.com/6zgtif
Works in Firefox: https://streamable.com/7nwlal

## System info

OS: Ubuntu 20.04
Google Chrome version: 83.0.4103.61
Firefox version: 76.0.1
Jaeger version: 1.18.0

**Comment by glavoie** [comment]
Same issue appeared recently here as well, only with Chrome (Safari/Firefox are OK).

OS: macOS 10.15.4 (Catalina)
Google Chrome: 83.0.4103.106
Jaeger: 1.18

**Comment by yurishkuro** [comment]
any errors in the console?

**Comment by lucacasonato** [comment]
Nope, I only get this warning: 
![image](https://user-images.githubusercontent.com/7829205/87665736-ad396480-c767-11ea-9c75-31834eda9c71.png)

**Comment by yurishkuro** [comment]
I am going to re-open this until we do a new release, because people keep booking duplicate tickets.

**Comment by xuanaxuan** [comment]
经过测试,发现修改以下css文件样式即可解决bug
packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanTreeOffset.css
.SpanTreeOffset--indentGuide {
  
 /*加了会导致鼠标悬停时单个跨度变大,注释掉就行*/
  /* height: 100%;*/
padding-right: calc(0.5rem + 12px);
  border-left: 1px solid transparent;
  display: inline-flex;
}

**Comment by meenal06** [comment]
Hi @jpkrohling , is this issue still open to work? I can see a PR merged and addressing the following issue.

**Comment by jpkrohling** [comment]
I think this has been fixed. I'm closing this, as I haven't seen any reports of this lately.
