### ISSUE TITLE
how to start jaeger-ui

### ISSUE THREAD

**Issue by yanghong1995220** [jaegertracing/jaeger-ui#593]
I'm going to go into the jaeger-ui folder
I'm dragging my code locally and I don't know how to run it locally, right
Execute the yarn add after the yarn ,but error,
That location item needs to be modified to run locally

**Comment by mckornfield** [comment]
When you say dragging your code locally, how do you mean? You probably need to run `yarn install` and then `yarn start` to get it working as the [readme](https://github.com/jaegertracing/jaeger-ui#running-the-application). I got it working running the all in one locally https://www.jaegertracing.io/docs/1.18/getting-started/#all-in-one + the instructions I linked.
