### ISSUE TITLE
Add the same menu search, but the filter always jumps to the previous search URL

### ISSUE THREAD

**Issue by sunfangGit** [jaegertracing/jaeger-ui#595]
![image](https://user-images.githubusercontent.com/42057618/87278186-6dc80980-c516-11ea-82e9-9b5c33c2e57b.png)

**Comment by yurishkuro** [comment]
Sorry, I don't understand what the ask is here. Also, this is not a standard Jaeger UI.

**Comment by sunfangGit** [comment]
If I copy the same search page, the page does not change, but the filter will still jump to the previous search link, how to change this
