### ISSUE TITLE
[Feature] change the default layout selection for deep dependency graph view (view=ddg)

### ISSUE THREAD

**Issue by christine-gong** [jaegertracing/jaeger-ui#600]
## Requirement - what kind of business use case are you trying to solve?

can we change the default choice of `layout selection` to be `one node per resource` in this section:
<img width="662" alt="Screen Shot 2020-07-16 at 3 32 48 PM" src="https://user-images.githubusercontent.com/38263789/87814637-f3023580-c818-11ea-89a8-d816e1580f4b.png">
Current default is `show paths to focal node`

**Comment by yurishkuro** [comment]
I don't have a strong opinion on the specific default itself, but I think it would be useful to have it configurable per installation in the ui config, so that the change is backwards compatible in case some people really like the current default.

**Comment by christine-gong** [comment]
@yurishkuro yeah it would be nice to be configurable as part of ui deployment.

**Comment by Leena1666** [comment]
can I work on this issue?

**Comment by albertteoh** [comment]
@Leena1666 it's yours!

**Comment by PawBud** [comment]
I am aware that this issue has already been assigned, but I did it nevertheless given that it was assigned almost 6 months ago. Do let me know if I should close my PR.

**Comment by Wise-Wizard** [comment]
@yurishkuro, Is this issue still open? I would like to work on it!

**Comment by yurishkuro** [comment]
It's open

**Comment by yurishkuro** [comment]
It should be configurable by user, but in the absence of such configuration it should behave the same as today.

**Comment by Wise-Wizard** [comment]
Understood! Thanks for clarifying!

**Comment by Wise-Wizard** [comment]
Hi, I thought configurable by user meant that the end user can set any of the option as defualt and was thinking of adding set as default as an additional option and had made the required changes for that, and was about to raise a PR but then I took a look at the below Thread: https://github.com/jaegertracing/jaeger-ui/pull/891                                                                                                               and found out there are some entirely different expectations and I have misunderstood them something to do with the below picture
![Screenshot 2023-12-15 135129](https://github.com/jaegertracing/jaeger-ui/assets/103821431/deb6e73b-326e-43d5-bf3d-1286201c8753)
Can you please clarify the requirements again as to what is expected?

**Comment by yurishkuro** [comment]
> configurable by user meant that the end user can set any of the option as default

I think there's even a simpler solution - store last used option in local storage and apply it on new screens. Changing default via configuration would be next level, very high friction for small benefit.

**Comment by Wise-Wizard** [comment]
Got it thanks a lot! Will implement that itself
