### ISSUE TITLE
How to build on OS windows10

### ISSUE THREAD

**Issue by zmapleshine** [jaegertracing/jaeger-ui#602]
os：win10 1909

node：v12.18.2
npm： v6.14.5

when i execute command yarn install at root directory，the following error occurs:

![image](https://user-images.githubusercontent.com/12667610/87926445-493ed500-cab4-11ea-811f-f871ae3ea962.png)

it seems like unable to resolve variable "$npm_execpath" at plexus/package.json ,try replace it to "yarn" or "npm ", the flowing error occurs again:

![image](https://user-images.githubusercontent.com/12667610/87926707-acc90280-cab4-11ea-8fb2-a8775cfec755.png)

Try to convert the variable definition to something Windows supports：

in packages/plexus/package.json
```json
 "scripts": {
    "_tasks/build/lib/js": "node_modules/.bin/babel src --extensions '.tsx,.js' --out-dir lib",
    "_tasks/build/lib/types": "../../node_modules/.bin/tsc",
    "_tasks/build/umd": "webpack --mode %NODE_ENV% --config webpack.umd.config.js",
    "_tasks/clean/dirs": "rimraf lib dist",
    "_tasks/clean/worker": "rimraf src/LayoutManager/layout.worker*js*",
    "_tasks/bundle-worker": "webpack --mode %NODE_ENV% --config webpack.layout-worker.config.js",
    "_tasks/dev-server": "webpack-dev-server --mode %NODE_ENV% --config webpack.dev.config.js",
    "build": "SET NODE_ENV=production && npm-run-all -ln --serial _tasks/clean/* _tasks/bundle-worker --parallel _tasks/build/**",
    "coverage": "echo 'NO TESTS YET'",
    "prepublishOnly": "yarn build",
    "start": "SET NODE_ENV='development' && npm-run-all -ln --serial _tasks/clean/worker _tasks/bundle-worker --parallel '_tasks/bundle-worker --watch' _tasks/dev-server",
    "test": "echo 'NO TESTS YET'"
  }
```

in packages/jaeger-ui/package.json

```json
"scripts": {
    "analyze": "source-map-explorer build/static/js/main.*",
    "build": "SET REACT_APP_VSN_STATE=$(../../scripts/get-tracking-version.js) && react-app-rewired build",
    "coverage": "yarn run test --coverage",
    "start:ga-debug": "SET REACT_APP_GA_DEBUG=1 && SET REACT_APP_VSN_STATE=$(../../scripts/get-tracking-version.js) && react-app-rewired start",
    "start": "react-app-rewired start",
    "test-dev": "react-app-rewired test --env=jsdom",
    "test": "SET CI=1 && react-app-rewired test --env=jsdom --color"
  },
```

then close linebreak-style ,yarn start success.

**Comment by zmapleshine** [comment]
Although start succeeded, a compilation error occurred

![image](https://user-images.githubusercontent.com/12667610/87951042-ac436280-cada-11ea-8f61-7ced8da65693.png)

**Comment by yurishkuro** [comment]
Disclaimer: we have very limited amount of time that we can afford to allocate to the UI at this time, and our primary build environment is on Linux/MacOS, so you may not receive much support from maintainers on this ticket.

**Comment by zmapleshine** [comment]
@yurishkuro Okay : (
