### ISSUE TITLE
The Span rows keep growing in height, filling up the screen

### ISSUE THREAD

**Issue by SaintDubious** [jaegertracing/jaeger-ui#609]
## Requirement - what kind of business use case are you trying to solve?

Sometimes when I mouse over the little Span expansion arrow the Span row grows. When I mouse around it the rows jump around. Sometimes when the mouse leaves the browser window everything restores, but the problem continues. This only seems to happen in Chrome (Edge and Safari seem okay), and only started a couple of weeks ago. Note that I didn't change jaeger-ui when it started, so I assume that an update to Chrome made it start happening. It started on a version of Jaeger-ui 1.6.0 which I upgraded to 1.9.0 in the hopes it would be solved, but it continues.

Here's a screen shot:
<img width="1152" alt="Capture" src="https://user-images.githubusercontent.com/14866211/89443619-8515a380-d71e-11ea-9952-26a159e49a7f.PNG">

**Comment by yurishkuro** [comment]
This has been fixed recently and will be available in the next release.

**Comment by SaintDubious** [comment]
Thanks Yuri!
