### ISSUE TITLE
more type span tags

### ISSUE THREAD

**Issue by taotao365s** [jaegertracing/jaeger-ui#620]
I want to support more flags , for example warning span,  link span and so more.

**Comment by jkowall** [comment]
@taotao365s Can you please explain the issue? You can search for any tag in the search fields, for example, "express.type	
middleware"

**Comment by taotao365s** [comment]
I am sorry, we just want more distinguish tag， just like Labels in github

**Comment by jkowall** [comment]
> I am sorry, we just want more distinguish tag， just like Labels in github

Sorry I do not understand, you can do the same thing with Jaeger UI already with multiple tags. You want a different "picker" for tags or something else?

**Comment by taotao365s** [comment]
something like 'picker'
