### ISSUE TITLE
[vote] Promote @rubenvp8510 to UI maintainer

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#621]
Ruben (@rubenvp8510) has built a number of new features in the UI and helps reviewing PRs. I propose to make him a full UI maintainer.

@jaegertracing/jaeger-maintainers @everett980

**Comment by vprithvi** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by everett980** [comment]
+1

**Comment by pavolloffay** [comment]
+1

**Comment by jpkrohling** [comment]
+1

**Comment by yurishkuro** [comment]
Done. Congrats, @rubenvp8510 !
