### ISSUE TITLE
Span bar broken on click

### ISSUE THREAD

**Issue by Stono** [jaegertracing/jaeger-ui#628]
Hey, 
I've just excitedly deployed 1.19 (which has ui version 1.10) due to it having a fix for the span hover issue (https://github.com/jaegertracing/jaeger-ui/pull/599).

Whilst that has been fixed, there's another bug now that when we click spans sometimes they load empty:

<img width="1674" alt="Screenshot 2020-08-26 at 17 35 35" src="https://user-images.githubusercontent.com/1486729/91331491-ba179200-e7c2-11ea-8fe6-2b2758537c64.png">

On top of that sometimes multiple spans expand when you click one of them:

<img width="1680" alt="Screenshot 2020-08-26 at 17 37 31" src="https://user-images.githubusercontent.com/1486729/91331598-d9162400-e7c2-11ea-8543-4c043fae2cff.png">

So unfortunately all in all its even worse than 1.18! 

I'm on chrome `84.0.4147.135` however it's the same on safari too.

**Comment by yurishkuro** [comment]
cc @rubenvp8510

**Comment by robinator8** [comment]
Reproduced on Ubuntu 18.04.4 LTS:
* chrome version 84.0.4147.135
* Firefox version 79.0

**Comment by Azim-Palmer** [comment]
Reproduced on Windows

- chrome version 84.0.4147.135

**Comment by objectiser** [comment]
@everett980 @tiffon Any chance you could take a look? @rubenvp8510 is on PTO until Monday.

**Comment by yurishkuro** [comment]
@tklever I suspect it's the React refactoring that caused this issue. I reverted the UI prior to your first change and it seems to work.

**Comment by tklever** [comment]
Oh no! Let me know what you find, maybe I can get some tests around it to ensure it doesn't regress further

**Comment by yurishkuro** [comment]
Sadly we don't have anyone available at the moment to troubleshoot this (people are on vacations). The reported issue is easily reproduced - running all-in-one (which does self-tracing), and then expanding any span shows the blank space. I suspect one of those callback methods isn't being called at the right time, since the renaming wasn't semantically fully equivalent.

**Comment by tklever** [comment]
It's #612 that causes it. I'll keep digging to get more specific / find a fix.

**Comment by tklever** [comment]
Specifically it's the changes in #612 to  `packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.tsx`, reverting just that file gets rid of the emptiness.

Looks like @rubenvp8510 already has a fix.

**Comment by Stono** [comment]
Just tested on 1.19.2 btw and can confirm all is well
