### ISSUE TITLE
Rendering span bars in a LAZY way for performance

### ISSUE THREAD

**Issue by WXM99** [jaegertracing/jaeger-ui#630]
## Requirement - what kind of business use case are you trying to solve?

I found that all spans are shown on the tracing page by default (all expanded), but usually I trace the span one by one, or trace on a certain long one. I don't need to see them all.

When the trace.json becomes a pretty large file containing more than 20,000 spans within a single trace, it would be difficult for the browser to render the tracing page at once, and usually cause the breakdown of the browser. 

## Problem - what in Jaeger blocks you from solving the requirement?

Every span-bar showing on the trace page gives the the browser big pressure to rending them all at once. It makes the large tracing page clunky.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

It would be much appreciated if jaeger UI renders all sub-spans in a lazy way, which means bars are created and rendered only when the expand button is clicked.

Hopefully the lazy way could improve the performance for big trace. Empirically saying, I would usually struggle (because it's really clunky) to click the "collapse all" button once I see the tracing page. And when sub-spans are all collapsed, the page become less clunky even though those sub bars are just hiddened but not destroyed.

## Any open questions to address

What is the life cycle of a span-bar component? 
Is there any hook defined by react to bind the rendering process on the click event?

---
Thanks for your time and work, cheers!

**Comment by yurishkuro** [comment]
Can you not use the expand/collapse buttons to do this?  20k should not be a problem for rendering (time is spent on processing the data rather than rendering), plus we're using virtual viewport.

![image](https://user-images.githubusercontent.com/3523016/91472268-2fd43a00-e865-11ea-922f-4a9a973d8a8f.png)

**Comment by WXM99** [comment]
> Can you not use the expand/collapse buttons to do this?  20k should not be a problem for rendering (time is spent on processing the data rather than rendering), plus we're using virtual viewport.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3523016/91472268-2fd43a00-e865-11ea-922f-4a9a973d8a8f.png)
> 
> 

Thanks for your reply!

I use "collapse-all" button as soon as I enter the tracing page for performance, and only expand several spans that I want to investigate. Because expanding all spans usually causes Chrome's breakdown.

I also tried to import a trace.json file (4MB with 10k spans). Jaeger processed it fast on the search page. But when I clicked the certain trace and want to enter the tracing pace, everything becomes sluggish.

If you want to give it a try on the same json file, I can provide it with pleasure.

Thanks!

**Comment by jpkrohling** [comment]
If you could attach the JSON to this issue, someone could use that when trying to make improvements.

**Comment by WXM99** [comment]
FYI 

[TraceFile.zip](https://github.com/jaegertracing/jaeger-ui/files/5368542/TraceFile.zip)

The new wanted API `fetchSubTrace`, compared with `fetchTrace`, only returns spans in the next level of given (trace or span) id, rather than all the spans of that trace. 
![image](https://user-images.githubusercontent.com/29013941/95807828-af4a9980-0d3d-11eb-9b44-19bb0090b84b.png)

Thanks!

**Comment by rubenvp8510** [comment]
Hi @WXM99 

Thanks for sharing your JSON file. I tried with the latest Jaeger version and I was able to do without causing a Chrome's breakdown, the only issue I see is a minor slowdown on rendering when I scroll too fast. 

I also tested with old Jaeger version and was able to see some performance issues.  What version of Jaeger are you using?

**Comment by WXM99** [comment]
Hi @rubenvp8510 

My deployed version is v1.9.0. Chrome's breakdown is perhaps because of my poor 4GB memory. I'll try the latest version on a better computer. Thanks!
