### ISSUE TITLE
How to set username and password authentication for Jager UI

### ISSUE THREAD

**Issue by chandu9333** [jaegertracing/jaeger-ui#635]
Is there anyway that can I create username and password authentication for Jaeger UI. So that I can log in and check the dashboard and do tracing?

**Comment by yurishkuro** [comment]
We recommend using an auth-proxy in front of Jaeger UI for this purpose, since there's no actual authorization mechanisms in Jaeger, so you're just protecting access to the web app.

Cf. https://medium.com/jaegertracing/protecting-jaeger-ui-with-an-oauth-sidecar-proxy-34205cca4bb1
