### ISSUE TITLE
When a trace exists and is older than 3 days, Jaeger can find the trace as part of a bulk search but cannot find the individual trace via the API

### ISSUE THREAD

**Issue by Azim-Palmer** [jaegertracing/jaeger-ui#636]
**Describe the bug**
When the trace is older than 2-3 days Jaeger will find traces when you search via the Jaeger UI - when you navigate to the individual trace it successfully loads however if you refresh the page you see this : ![Can't find trace](https://i.imgur.com/Z9KDewi.png)

**To Reproduce**
1. Log a trace
2. Wait 3 days
3. Search for traces older than 3 days
4. Click the trace
5. Refresh the page

**Expected behavior**
The trace should be visuable

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: Tested on 1.19.2, 1.17.1 and 1.18.1
 - Deployment: Docker with ES backend

**What troubleshooting steps did you try?**
- Verified that the API call for the specific trace is returning a 404 - http://{removed}/api/traces/697fd7cd823cb845
- Confirmed that the trace works when clicking through via the search UI ![Working Span](https://i.imgur.com/odbksKF.png)
- Confirmed that the trace exists in ElasticSearch ![In ES](https://i.imgur.com/ed8Hbgi.png)

**Comment by jpkrohling** [comment]
A good solution would probably to show a specific page when the trace cannot be found.

**Comment by MirkoRuggiero** [comment]
Hello, is there any update on this issue?
@jpkrohling Do you see showing a specific page to the user as a definitive solution for this? If so, why do you see this 404 as correct behaviour?

Thanks

**Comment by jpkrohling** [comment]
No, sorry, I think I misunderstood the issue when I first read about it. It's certainly not OK to just return a 404 if the trace exists. It's not clear to me why the trace can't be loaded when the URL is called directly, but it can when clicking on the trace search results.

From what I remember, when clicking on a result from the search results, there's no extra call to the backend, as the data is in memory already. This is how the backend gets the results:
https://github.com/jaegertracing/jaeger/blob/761facc2d381e15b3d23dc18f21ef833c868cc52/plugin/storage/es/spanstore/reader.go#L285-L295

When loading the URL directly, there's a call to the backend, which lands here:
https://github.com/jaegertracing/jaeger/blob/761facc2d381e15b3d23dc18f21ef833c868cc52/plugin/storage/es/spanstore/reader.go#L194-L207

Perhaps @pavolloffay knows what might be going on here?

**Comment by johanneswuerbach** [comment]
It seems that the default is too only look back for 72h https://github.com/jaegertracing/jaeger/blob/45acfd85d4d8dc0851d51bed28aa682664a15a14/plugin/storage/es/options.go#L90, https://github.com/jaegertracing/jaeger/blob/761facc2d381e15b3d23dc18f21ef833c868cc52/plugin/storage/es/spanstore/reader.go#L199, while the query searches back to the specified timeframe. 

Is there are specific reason not to search the entire available dataset?

**Comment by mehta-ankit** [comment]
Would the solution be to overwrite this max-span-age value with this flag:
`--es.max-span-age`
![image](https://user-images.githubusercontent.com/22157398/107274832-f2342980-6a1e-11eb-8804-4e21c974ea3c.png)

**Comment by mehta-ankit** [comment]
Also i think i found a similar issue, which was reported earlier: https://github.com/jaegertracing/jaeger-ui/issues/400
and Yuri made the same comment
https://github.com/jaegertracing/jaeger-ui/issues/400#issuecomment-522615780

**Comment by mehta-ankit** [comment]
Can confirm that this solves the problem: https://github.com/jaegertracing/jaeger-ui/issues/636#issuecomment-775409363

Setting it equal to the retention period of our spans it did work for us. (for us retention period is 7 days, and hence we set max-span-age to 168 hours)

**Comment by sbulic** [comment]
I can also confirm that introducing the flag **--es.max-span-age** and setting it to be equal to the retention period of the span indexes (on the ES side) has solved the issue for us as well.
