### ISSUE TITLE
How to modify the root directory of the URL in jaeger-ui

### ISSUE THREAD

**Issue by virgosnail** [jaegertracing/jaeger-ui#643]
Hello there. I want to change the http://127.0.0.1:32765/jaeger/search in jaeger-ui to http://127.0.0.1:32765/xxx/jaeger/search

I think /jaeger may be a root directory. In this case, I should modify this root directory so that all urls can be changed to /xxx/jaeger

**Comment by objectiser** [comment]
See `--query.base-path` option in https://www.jaegertracing.io/docs/1.19/cli/#jaeger-query.

**Comment by virgosnail** [comment]
thanks
