### ISSUE TITLE
generic analytics tracking (in addition to GA)

### ISSUE THREAD

**Issue by yoave23** [jaegertracing/jaeger-ui#652]
## Requirement - what kind of business use case are you trying to solve?

We would like to be able to track events in a generic way (i.e with a non GA solution) when running jaeger-UI inside an iframe 
## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger-UI tracking is tightly coupled to GA
## Proposal - what do you suggest to solve the problem or improve the existing situation?

We were thinking about adding a [post message](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to the tracking flow so it would be possible to register for events invoked by the UI.
the new flow will be configurable via the UI-config file

**Comment by yurishkuro** [comment]
Is it really tightly coupled to GA? My impression was that there is a thin abstraction in the code used to report events, and that abstraction is bound to the GA by default. If that's the case, then extending it to be bound to another function / library seems reasonable.

The only issue is that the UI config is currently a JSON file, whereas we discussed (#123) that it would be better to make it a JS file to allow defining functions, not just const values.

**Comment by yoave23** [comment]
@yurishkuro maybe tightly coupled isn't the correct term, but GA is currently the only way to report the tracked UI events, and this issue (feature suggestion) does aim to extend it.

Regarding #123, I believe that changing the UI config to a js file would mean a breaking change.
Also, could you please elaborate a little on the actual benefit of having a js file for configuring the UI (besides the ability to add comments)?

**Comment by yurishkuro** [comment]
> this issue (feature suggestion) does aim to extend it.

+1

> changing the UI config to a js file would mean a breaking change

No, we can still support JSON file as well and make the change backward compatible.

> could you please elaborate a little on the actual benefit of having a js file for configuring the UI

A JS file allows you to customize UI with functions. For example, in case of tracking, assume we have an API like `RecordEvent(...)`. By default it is implemented via GA lib, but in the config file you could provide a different implementation, either fully embedded into the config file, or by referencing additional JS modules.

**Comment by th3M1ke** [comment]
@yurishkuro can I take this one?

**Comment by yurishkuro** [comment]
sure
