### ISSUE TITLE
Add explanation about "Self Time" in "Trace Graph" view

### ISSUE THREAD

**Issue by quaff** [jaegertracing/jaeger-ui#653]
## Requirement - what kind of business use case are you trying to solve?
I don't understand what `Self Time` means.

## Problem - what in Jaeger blocks you from solving the requirement?
It seems jaeger not documented about `Self Time`.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Add explanation in `Help` tip.
![trace_graph](https://user-images.githubusercontent.com/143040/95726537-a4472900-0cab-11eb-820d-a6b6e11917ca.jpg)

**Comment by yurishkuro** [comment]
Self-time is the total time spent in the span when it was not waiting on children. For example, a 10ms span that had two 4ms non-overlapping children will have `self-time = 10ms - 2 x 4ms = 2ms`.

**Comment by quaff** [comment]
I understand now, a hovercard should be there, other people may have the same question.
