### ISSUE TITLE
Empty screen when click on a trace loaded from JSON

### ISSUE THREAD

**Issue by rubenvp8510** [jaegertracing/jaeger-ui#657]
## Requirement - what kind of business use case are you trying to solve?
Loading a JSON file and see the trace details of some selected trace.

## Problem - what in Jaeger blocks you from solving the requirement?

There is an issue when traces are loaded from JSON files, the result page shows all load traces, but when click on a trace appears a blank page. (and error in browser console).

Steps to reproduce:
1) On search page, select JSON File
2) Load json file traces
3) Click on a trace

Attached screenshot with the error.
![Screenshot from 2020-11-05 11-55-16](https://user-images.githubusercontent.com/3799716/98278155-d0c62c00-1f5d-11eb-96e4-b08fdce06e0f.png)

**Comment by GoingMyWay** [comment]
See this answer: https://stackoverflow.com/a/43922390/5046896
