### ISSUE TITLE
Display uninstrumented service from "producer" spans

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#660]
Follow-up to #659, the same logic should apply to "producer" span kinds.

**Comment by jpkrohling** [comment]
I'm marking this as a good first issue given that we have a related issue serving as guide, but feel free to remove the label if you think it's not the case.

**Comment by ampaire** [comment]
Hello @jpkrohling, I would like to work on this

**Comment by jpkrohling** [comment]
Sure, go ahead!
