### ISSUE TITLE
Is there a health endpoint for the UI?

### ISSUE THREAD

**Issue by sharkymcdongles** [jaegertracing/jaeger-ui#671]
I use statuscake to monitor my ingresses however Jaeger doesn't seem to implement a healthcheck via the UI only for the query pod on the admin port. I don't much want to expose that via the ingress, so is there a way to add a /health or similar that returns a json response 200 if it is up and working for such a use case or does it already exist?

**Comment by yurishkuro** [comment]
```sh
$ curl http://127.0.0.1:16687/
{"status":"Server available","upSince":"2020-12-25T12:03:39.684362-05:00","uptime":"15.778842883s"}%
```

**Comment by sharkymcdongles** [comment]
Yes I am aware of that, but the web ui is on 80 so this means I will have
to expose that port via the nginx ingress in addition to the standard
ingress for the ui which is bad practice. It makes much more sense to
include a call on 80.

**Comment by yurishkuro** [comment]
The health check was intentionally put on the admin port instead of the main port. 

cc @objectiser @jpkrohling

**Comment by sharkymcdongles** [comment]
I see the merit in having it on the admin port, but if you compare to other
similar monitoring tools like Kibana or Prometheus, they have the call from
the same server and port as the WebUI to allow it to be easily accessible
from an ingress. I can get around it being on the admin port, but it is
probably cleaner to have it via a webui endpoint for the end user. I am
also happy to submit a PR to implement this if it is wanted. Thanks! And
Merry Christmas! :)

**Comment by jpkrohling** [comment]
Is the audience for the Jaeger UI the same for the admin port in your case? Typically, the admin port is used by other tools (Prometheus, Kubernetes, ...) and as such, there's no reason to expose it to wider audiences.

**Comment by sharkymcdongles** [comment]
> Is the audience for the Jaeger UI the same for the admin port in your case? Typically, the admin port is used by other tools (Prometheus, Kubernetes, ...) and as such, there's no reason to expose it to wider audiences.

Well if someone wants to run a jaeger query they need the UI to be up and running, so having an external health check watch it is a nice option. I could redo the monitoring to be all alertmanager, but then that means all my monitoring is in cluster which means if there is ever a cluster issue I won't know things are down which is why we have external statuscake checks as a secondary alert for all endpoints.

I could easily add a second path for this in the ingress via the helm chart, but the ingress template doesn't support this either:

https://github.com/jaegertracing/helm-charts/blob/master/charts/jaeger/templates/query-ing.yaml

I think having the same setup as Prometheus, Alertmanager, Kibana, etc. would be useful to more than just me.

**Comment by yurishkuro** [comment]
I have no objections to mounting /health handler on the main query port as well.

**Comment by sharkymcdongles** [comment]
I went ahead and added a PR to the chart repo for now as a quick solution as this seems the path of least resistance and doesn't involve as much work or any functional changes to any binaries.

https://github.com/jaegertracing/helm-charts/pull/195

**Comment by jpkrohling** [comment]
Sorry, but I do have objections on having a health check to be exposed to the public internet by default. I understand your case, but I think having it supported under some customization via helm is indeed the appropriate way to go.

**Comment by sharkymcdongles** [comment]
> Sorry, but I do have objections on having a health check to be exposed to the public internet by default. Its not the case today, but a health check might involve doing some blocking operations, like checking if the state of the backing storage, making it a good target for a DoS attack. I understand your case, but I think having it supported under some customization via helm is indeed the appropriate way to go.

That's fine and dandy. Please review my merge request or have someone review it on the helm chart then that does exactly that per my last comment.

**Comment by yurishkuro** [comment]
> Sorry, but I do have objections on having a health check to be exposed to the public internet by default.

@jpkrohling can you elaborate on reasons? There's no confidential info returned from the health check endpoint, and any bad things that can be done to the endpoint can also be done to the UI itself just the same.

**Comment by jpkrohling** [comment]
For Jaeger itself, and for this moment, there aren't concrete downsides but conceptually, public endpoints shouldn't expose more information than necessary, and the health check isn't inherently a public endpoint meant to be viewed by the general audience of the UI.

**Comment by jkowall** [comment]
It seems like this was completed, @yurishkuro can you close?
