### ISSUE TITLE
yarn build and yarn start not working as expected in Windows

### ISSUE THREAD

**Issue by ssharifdev** [jaegertracing/jaeger-ui#682]
### I have attached the screenshots, let me know if am doing anything wrong here, Thanks
<img width="1038" alt="yarn1" src="https://user-images.githubusercontent.com/63889986/105628562-a3ee2a80-5e63-11eb-9a3c-45b3b7a62359.PNG">
<img width="652" alt="yarn2" src="https://user-images.githubusercontent.com/63889986/105628563-a5b7ee00-5e63-11eb-9be8-c19367400e0e.PNG">

**Comment by yurishkuro** [comment]
Sorry, we do not aim to support the development process on Windows. If you have a fix for the problem feel free to propose a PR.
