### ISSUE TITLE
Improve Search box UI and UX 

### ISSUE THREAD

**Issue by Danafrid** [jaegertracing/jaeger-ui#683]
## Requirement - what kind of business use case are you trying to solve?
Improving the usability of the search in Jaeger, by unifying between the two tabs - saving the user an extra click and updating the UI.

## Problem - what in Jaeger blocks you from solving the requirement?
Currently, there are several issues in the Search box UI:
- The search button is not prominent enough
- In order to upload a JSON file, the user has to navigate to a different tab inside the search
- The search fields can be grouped better (see min duration, max duration)
- Ui-wise the search can look lighter and not take as much vertical space, which is helpful when there are many results on the screen

## Proposal - what do you suggest to solve the problem or improve the existing situation?

See attached proposal for the redesign - unifying between the search and upload functionalities, whilst keeping the drag and drop functionality - all in the same view. Also, a cleaner UI and a more prominent search button.

**Before:**
<img width="449" alt="Screen Shot 2021-01-24 at 17 05 06" src="https://user-images.githubusercontent.com/75564311/105634556-3643fd80-5e67-11eb-826b-f3351dccc849.png">

**Suggested:**

https://user-images.githubusercontent.com/75564311/105634579-4e1b8180-5e67-11eb-8284-392ebaea6420.mov

Would appreciate your thoughts on the proposal.

**Comment by jpkrohling** [comment]
Its yours!

**Comment by Danafrid** [comment]
Hi @meenal06, here is the file with the detailed UI design for this issue -
https://www.figma.com/file/GHuXn2IYWdSjYvYnFLkPeh/Jaeger-UI-Search?node-id=0%3A1

**Comment by meenal06** [comment]
Hi @jpkrohling , I have edited the layout according to the sigma designs however there are several complication with using dragNdrop inscribed under the SearchForm of which one major is that with every click in the search form antd would perform two tasks one of taking input and other of opening the file-upload which is the default method added into the dragger widget.
However the following can work if we may remove the dragger altogether and replace it with just a upload widget on which user can click to upload. 

Let me know what do you think on this!

**Comment by jpkrohling** [comment]
Click to upload sounds fine to me, but perhaps @rubenvp8510 has a different idea?

**Comment by rubenvp8510** [comment]
Due the limitations I see, I think click to upload sounds like a good approach, or may be delimit the area of dragNdrop to no overlap with the form could work for this case?

**Comment by meenal06** [comment]
> Due the limitations I see, I think click to upload sounds like a good approach, or may be delimit the area of dragNdrop to no overlap with the form could work for this case?

Yes the later is achievable I hope so!

**Comment by rubenvp8510** [comment]
> > Due the limitations I see, I think click to upload sounds like a good approach, or may be delimit the area of dragNdrop to no overlap with the form could work for this case?
> 
> Yes the later is achievable I hope so!

For now it's ok with the click approach, we might want to think about the dragNdrop region later :)
