### ISSUE TITLE
Trace Statistics : ST total :: More intuitive explanation for user

### ISSUE THREAD

**Issue by vvvprabhakar** [jaegertracing/jaeger-ui#689]
In the latest versions, you have given a description of what is self-time in the trace graph view.
Can you provide the same info in trace statistics also? 
Or else can we have a sticky bar across the different views of traces whatever we have in the trace graph?
And, **sometimes in the trace statistics we are seeing ST in duration for some groups it's more than 100% can I know why ??**

A sticky bar across the different views
![save](https://user-images.githubusercontent.com/20414336/108166132-bfbeb680-7119-11eb-9dad-65b632787ce0.png)

**Comment by vvvprabhakar** [comment]
@yurishkuro  can you clarify sometimes in the trace statistics we are seeing ST in duration for some groups it's more than 100%?

**Comment by yurishkuro** [comment]
If that view aggregates by service and a given service occurs in the leaves and there are concurrent requests to that service, then the cumulative self time can be larger that the total trace duration, thus > 100%
