### ISSUE TITLE
[bug] Flaky test coverage for SpanBarRow.tsx

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#704]
The following lines intermittently show up as not covered in codecov:

https://github.com/jaegertracing/jaeger-ui/blob/dac69134eed5fbf9087e1fc6e0aab514c5fd95e2/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanBarRow.tsx#L117-L120

**Comment by jkowall** [comment]
I think you can close this out @yurishkuro
