### ISSUE TITLE
How to integrate jaeger ui with angular1.x?

### ISSUE THREAD

**Issue by vijayvishnu** [jaegertracing/jaeger-ui#717]

**Comment by adithyaakrishna** [comment]
@vijayvishnu Could you provide a description regarding the same?

**Comment by vijayvishnu** [comment]
I am using angular 1.x web application, which I need to integrate this jaeger UI component alone and show the traces page within my client.

**Comment by jkowall** [comment]
Grafana has embedded Jaeger UI into their UI. I couldn't find the specific PRs which accomplished this but @joe-elliott might be able to shed more light on how they embedded the Jaeger views into Grafana.

**Comment by joe-elliott** [comment]
Docs have some info about embedding: https://www.jaegertracing.io/docs/1.26/frontend-ui/#embedded-mode

As to how it was done in Grafana. I have no idea :). Check the code!

**Comment by yurishkuro** [comment]
I don't think grafana is embedding Jaeger, I think they forked it. In the demos I've seen the ui looked very similar to Jaeger but with a very distinct color scheme that you cannot get just by embedding.
