### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by zhangcan12138** [jaegertracing/jaeger-ui#718]
[_tasks/build/lib/types] src/DirectedGraph/DirectedGraph.tsx(155,15): error TS2339: Property 'graph' does not exist on type 'TCancelled | TPositionsDone<Record<string, unknown>>'.
[_tasks/build/lib/types] src/DirectedGraph/DirectedGraph.tsx(155,35): error TS2339: Property 'vertices' does not exist on type 'TCancelled | TPositionsDone<Record<string, unknown>>'.
[_tasks/build/lib/types] src/DirectedGraph/DirectedGraph.tsx(165,13): error TS2339: Property 'edges' does not exist on type 'TCancelled | TLayoutDone<Record<string, unknown>, Record<string, unknown>>'.
[_tasks/build/lib/types] src/DirectedGraph/DirectedGraph.tsx(165,33): error TS2339: Property 'graph' does not exist on type 'TCancelled | TLayoutDone<Record<string, unknown>, Record<string, unknown>>'.
[_tasks/build/lib/types] src/DirectedGraph/DirectedGraph.tsx(165,53): error TS2339: Property 'vertices' does not exist on type 'TCancelled | TLayoutDone<Record<string, unknown>, Record<string, unknown>>'.
[_tasks/build/lib/types] src/zoom/ZoomManager.tsx(57,10): error TS2742: The inferred type of 'getZoomStyle' cannot be named without a reference to 'react-dom/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
[_tasks/build/lib/types] src/zoom/utils.tsx(79,17): error TS2742: The inferred type of 'getZoomStyle' cannot be named without a reference to 'react-dom/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
[_tasks/build/lib/types] src/zoom/utils.tsx(83,11): error TS2339: Property 'x' does not exist on type 'void | ZoomTransform'.
[_tasks/build/lib/types] src/zoom/utils.tsx(83,14): error TS2339: Property 'y' does not exist on type 'void | ZoomTransform'.
[_tasks/build/lib/types] src/zoom/utils.tsx(83,17): error TS2339: Property 'k' does not exist on type 'void | ZoomTransform'.
[_tasks/build/lib/types] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
[_tasks/build/lib/js   ] [BABEL] Note: The code generator has deoptimised the styling of /home/zhangcan/桌面/sm-portal-versions/sm-portal/packages/jaeger-ui-1.6.0/packages/plexus/src/LayoutManager/layout.worker.bundled.js as it exceeds the max of 500KB.
[_tasks/build/lib/types] error Command failed with exit code 1.
ERROR: "_tasks/build/lib/types" exited with 1.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@jaegertracing/plexus'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zhangcan12138** [comment]
![jaeger-ui-error](https://user-images.githubusercontent.com/46553454/111753803-3c3be500-88d2-11eb-9338-4f925a2a0e5c.png)

**Comment by adithyaakrishna** [comment]
@zhangcan12138 I didn't face any error while running the app, could you please check , also do pull the recent changes and run the app

**Comment by yurishkuro** [comment]
I am closing this as there's not enough details what OS, versions, commands, etc. are being run. Since we have CI running successfully, this is most likely an environment issue.
