### ISSUE TITLE
Check what's needed to update react-router-dom from 4.3.1 to 5.2.0

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-ui#725]
dependabot opened the PR #694 bumping react-router-dom from 4.3.1 to 5.2.0 but looks like the update requires some manual changes and testing. This issue is about doing the update to the latest react-router-dom version, including all the necessary changes in the consuming code.

**Comment by meenal06** [comment]
Hi @jpkrohling , can I work on this?

**Comment by yurishkuro** [comment]
@meenal06 go ahead
