### ISSUE TITLE
Setting aliases for jaeger DDD objects

### ISSUE THREAD

**Issue by orihomie** [jaegertracing/jaeger-ui#756]
Hi, I'd like to know is there any option to set aliases for objects in that diagram or group them somehow into one object, since on my own diagram I see my service duplicated with 2 names
Company.MuchUsed.Service - service's original name
company-muchused-service - service's kubernetes name

This complicates things when you want to know true sight of your company's services map.

**Comment by yurishkuro** [comment]
There's no functionality like that right now. 

What is preventing you from converging on a single name in your infra?

**Comment by orihomie** [comment]
Requirements for naming of .net services and requirements on service naming in k8s charts differ.

**Comment by yurishkuro** [comment]
Whose requirements? You're in control of the name passed to Jaeger SDK. I assume k8s name is available as env var, you can pass it to the SDK.

**Comment by jkowall** [comment]
Seems stale since your explanation was accurate @yurishkuro 

Alternately autoinstrumentation should be passing these into the trace tags.
