### ISSUE TITLE
Jaeger-ui dependency graph

### ISSUE THREAD

**Issue by mikheyrojo** [jaegertracing/jaeger-ui#757]
Hi, I wanted to ask a question, and suggested chat link doesn't let me in https://cloud-native.slack.com/archives/CGG7NFUJ3

So my question -> does Jaeger have anything similar to Zipkin dependency graph? Like this:
![zipkin deps](https://pbs.twimg.com/media/EIP4NiqWoAELIp0?format=jpg&name=large "Zipkin deps")

**Comment by yurishkuro** [comment]
> suggested chat link doesn't let me in https://cloud-native.slack.com/archives/CGG7NFUJ3

Where is it suggested?

**Comment by mikheyrojo** [comment]
when you open an issue - this is like a draft for it

**Comment by mikheyrojo** [comment]
so, is there any similar graphs? or is it in plans?

**Comment by yurishkuro** [comment]
Jaeger supports two types of topology graphs https://www.jaegertracing.io/docs/1.22/features/#topology-graphs

If you're interested in specific features, please describe them. The screenshot from zipkin doesn't tell me anything about what you're after.

**Comment by mikheyrojo** [comment]
Yuri hi, can I know how can I switch on SystemArchitecture tab? do I need `spark-dependencies` for that? currently my setup doesn't have it

**Comment by yurishkuro** [comment]
You can play with all-in-one which stores traces in memory and can render graph directly. For real prod installation with remote storage you will need the spark job.
