### ISSUE TITLE
customWebAnalytics:: Trying to Implement :: Sending Analytics to my local elasticsearch

### ISSUE THREAD

**Issue by vvvprabhakar** [jaegertracing/jaeger-ui#806]
Enabled ```customWebAnalytics: true```

What are the other changes I should do to send analytics to any of minedatasource? 

Do I need any functions to be added??
I have an API to send, can I define API somewhere and it will send analytics to that API directly ??

**Comment by vvvprabhakar** [comment]
Add a `customWebAnalytics` func in default-config file

**Comment by yurishkuro** [comment]
Was the documentation missing? If so, where we can add it for best impact?
