### ISSUE TITLE
Typescript version is outdated

### ISSUE THREAD

**Issue by yoave23** [jaegertracing/jaeger-ui#818]
## Requirement - what kind of business use case are you trying to solve?

We'd like to upgrade the typescript version from 3.5.3 to the latest one (4.4)

## Problem - what in Jaeger blocks you from solving the requirement?

the current version is missing key features

Related: #998

**Comment by yurishkuro** [comment]
If you have cycles & expertise, go for it.

**Comment by yoave23** [comment]
@yurishkuro sure, we'll take it
