### ISSUE TITLE
Tabular view trace link not respecting base URL

### ISSUE THREAD

**Issue by caizixian** [jaegertracing/jaeger-ui#847]
**Describe the bug**
When running `jaeger-query` with a non-empty `QUERY_BASE_PATH`, the links in the ID column of Trace Tabular View is not respecting the base URL set.

**To Reproduce**
1. Run `jaeger-query` with a non-empty `QUERY_BASE_PATH`
2. Click on a trace
3. Choose Trace Spans Table in the drop down menu of the stop bar
4. Click on one of the link in the ID column

**Expected behavior**
The link takes me to the corresponding Trace Timeline view.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: `jaegertracing/jaeger-query:1.27`
 - Deployment: Docker

**What troubleshooting steps did you try?**
See below for suspected problematic code block.

**Additional context**
It seems to be caused by the hardcoded URL here https://github.com/jaegertracing/jaeger-ui/blob/ad60380c8b1e7ccfed2523538303b2bd42dbeae8/packages/jaeger-ui/src/components/TracePage/TraceSpanView/index.tsx#L146

**Comment by vvvprabhakar** [comment]
@caizixian  Taking this

**Comment by caizixian** [comment]
@vvvprabhakar just wondering whether you were meant to tag someone else?

**Comment by caizixian** [comment]
I created a PR
