### ISSUE TITLE
Configure Google Analytics from the /api/config

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#85]
Currently, the Google Analytics key is a bundle-time env-var, which means to use Google Analytics a custom UI bundle must be generated.

Change to use the `/api/config` data, instead.

Also, consider switching `/api/config` data to be injected into the HTML when the page is served from the query-service.

**Comment by tiffon** [comment]
The approach taken for this ticket is the last item mentioned in the description, where the config is embedded into the HTML when it is served instead of loaded via HTTP from `/api/config`.

**Comment by pavolloffay** [comment]
Is the readme accurate https://github.com/jaegertracing/jaeger-ui#enable-google-analytics?

**Comment by tiffon** [comment]
>Is the readme accurate https://github.com/jaegertracing/jaeger-ui#enable-google-analytics?

It is inaccurate. Thanks for pointing this out. Will change the README to refer to the [deployment guide](http://jaeger.readthedocs.io/en/latest/deployment/#ui-configuration)

**Comment by tiffon** [comment]
>Is the readme accurate https://github.com/jaegertracing/jaeger-ui#enable-google-analytics?

@pavolloffay Created #125 to address this.
