### ISSUE TITLE
Date input is clipped in custom time selection

### ISSUE THREAD

**Issue by bobrik** [jaegertracing/jaeger-ui#864]
**Describe the bug**

Date input is not fully visible (Macbook Pro 13", maximized window):

![image](https://user-images.githubusercontent.com/89186/148595365-6928f8ca-4998-4e42-acb7-905109b18186.png)

**To Reproduce**

1. Set date format to ISO8601:

![image](https://user-images.githubusercontent.com/89186/148595433-0b5e9462-da9d-44d1-b9e5-4da88270c91a.png)

2. Open Jaeger UI
3. Pick custom time range 

**Expected behavior**

Date can be entered without issues.

**Version (please complete the following information):**
 - Jaeger version: 1.29, jaeger-ui build from the tip

**Additional context**

I think we can use `input` with `type="datetime-local"` rather than separate inputs for date and time. This also gives a nice picker, at least in Chrome:

![image](https://user-images.githubusercontent.com/89186/148595956-269c3162-8180-4350-ac88-dfdb6608ccab.png)

I'm happy to open a PR if you agree.

**Comment by albertteoh** [comment]
Thanks for the proposal @bobrik. I like the fact that date and time are together in one input to save real estate and remove the need to fill out another input just for time. 

However, it looks like it's [not supported in IE](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#browser_compatibility), and perhaps why it was designed that way in Jaeger UI, because the workarounds I've read are to provide separate date and time inputs.

**Comment by bobrik** [comment]
Do we need to care about IE? Microsoft replaced it with Chromium based Edge 7 years ago and new feature development for IE stopped 6 years ago.

**Comment by yurishkuro** [comment]
I don't have strong opinion on Chromium/IE, but with the current implementation it looks like there is enough space to fit the ISO date, but something is slightly off with the style sheet. So the minimal fix would be to just fix the stylesheet.

**Comment by yurishkuro** [comment]
btw, I am not digging the s/s of the chromium date picker, it looks very unintuitive - wth are the two right columns?

**Comment by yurishkuro** [comment]
> Should I open a PR to do this instead of full datetime-local picker?

yes, let's try that first

**Comment by bobrik** [comment]
#867 takes care of this.
