### ISSUE TITLE
Monitor Tab: Numbers in the Legend

### ISSUE THREAD

**Issue by nofar9792** [jaegertracing/jaeger-ui#871]
**Describe the bug**
Cannot see the whole number in the legend when the number is greather than 1000

**Expected behavior**
See the while number

**Screenshots**
![Screen Shot 2022-01-25 at 16 01 10](https://user-images.githubusercontent.com/11076023/151014788-0d3b465b-1e15-4da1-ba1c-bad5fbc8a085.png)

and i would like to fix it

**Comment by esnible** [comment]
I don't recall seeing this view in Jaeger UI.  How do I navigate to it?

**Comment by yurishkuro** [comment]
@esnible I assume it's the Monitoring tab introduced here #2954. I don't think the documentation part of this was finished.
