### ISSUE TITLE
Monitor Tab - The x-axis timeframe should be according to the selected timeframe

### ISSUE THREAD

**Issue by nofar9792** [jaegertracing/jaeger-ui#882]
**Describe the bug**
When the user doesn't have data for all the selected timeframe, the a-axis domain doesn't show the whole timeframe points.
react-vis automatically interpolates across the relevant domains of the data 

**Expected behavior**
show all the timeframe

**Screenshots**

https://user-images.githubusercontent.com/11076023/154097286-1d39fea1-140a-462d-a55f-be048ffa6233.mov

I would like to fix this bug

**Comment by nofar9792** [comment]
Can I open a PR for this bug?

**Comment by yurishkuro** [comment]
+1
