### ISSUE TITLE
New look for monitor tab empty state + make page configurable

### ISSUE THREAD

**Issue by nofar9792** [jaegertracing/jaeger-ui#907]
## Requirement - what kind of business use case are you trying to solve?
We want to make the page configurable, so we will be able to deliver different messaging.
For example, in our use case, we want to navigate to our custom documentation and also show different messaging to different user roles.

We wanted to create a flexible framework that will allow us as well as other users to customize their own instructions on how to start using this functionality

Using the monitor functionality needs more than the very basic text that exists today so we wanted to enrich this experience for users and explain what are the requirements and what's the value

What exists now in Jaeger:
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/11076023/157659881-427cff60-14e5-4c86-8ef0-9670aecbca15.png">

Our new suggestion for this page:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/11076023/157659984-d4bbdccb-eb9b-467c-b1d2-345f2e7d6838.png">

In addtion, we want to add bar when the user doesn't have any metrics yet:
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/11076023/157660849-d81f92e2-e0af-485a-83cf-1c48aae8b93b.png">

the link will be also confgurable.

We thought to add the config to 
jaeger-ui/packages/jaeger-ui/src/types/config.tsx
and
jaeger-ui/packages/jaeger-ui/src/constants/default-config.tsx

and then use in
jaeger-ui/packages/jaeger-ui/src/components/Monitor/EmptyState/index.tsx

**Comment by nofar9792** [comment]
@yurishkuro @albertteoh WDYT?

**Comment by yurishkuro** [comment]
+1

**Comment by albertteoh** [comment]
+1 Looks great!

FWIW, I'm working on documentation now: https://github.com/jaegertracing/documentation/pull/556. 

Your comments/feedback would be welcome to ensure we're on the same page, especially around terminology.
