### ISSUE TITLE
browser prompt error

### ISSUE THREAD

**Issue by Luncher** [jaegertracing/jaeger-ui#92]
**Description**

**Steps to reproduce the issue:**
1. open http://localhost:16686/search
2. open terminal
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (Browser, etc.):**
![1507875956028](https://user-images.githubusercontent.com/5138977/31532898-87b18430-afb5-11e7-8899-ce3f8c3f6e59.jpg)

**Comment by tiffon** [comment]
This looks like the UI is not handling the scenario when there are no known services. That's probably the case when there aren't any traces. 

Has this persisted after adding traces?

Thanks for reporting.
