### ISSUE TITLE
Highlight services that has error in trace list view

### ISSUE THREAD

**Issue by Jaskerv** [jaegertracing/jaeger-ui#925]
## Requirement - what kind of business use case are you trying to solve?

Highlight the service tag that has an error in the trace list view.

## Problem - what in Jaeger blocks you from solving the requirement?

![image](https://user-images.githubusercontent.com/26532014/162875522-60c861de-d57a-42f8-af7b-8f554a045c6c.png)

When in the trace list view, it currently shows how many errors exist in the trace, but it does not tell the user which service has an error.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

![image](https://user-images.githubusercontent.com/26532014/162875447-cbf884f8-5339-4139-9ce8-c68016c2b4bd.png)
Add an error icon to the service if error tag exists.

If this is acceptable, I have the code written already :)

**Comment by yurishkuro** [comment]
Good idea
