### ISSUE TITLE
instructions notify in Monitor Tab is undefined

### ISSUE THREAD

**Issue by FingerLiu** [jaegertracing/jaeger-ui#928]
**Describe the bug**
Link in "No data yet! Please see these[ instructions ](http://undefined/)on how to set up your span metrics." is undefined.

**To Reproduce**
1. upgrade ui to 1.22
2. switch to monitor tab
3. click instructions on the top

**Expected behavior**
A link to instructions to setup otel

**Screenshots**
![image](https://user-images.githubusercontent.com/3981064/163131714-cdce224e-effd-4b84-a31e-9014af3a1ff9.png)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.23
 - Deployment:Kubernetes

**Comment by FloydJohn** [comment]
On my deployment the link targets `https//www.jaegertracing.io/docs/latest/spm/` (notice the lack of `:` between `https` and `//`).

The issue is related to react router treating this link as an internal one, I just opened a PR to fix this behaviour.
