### ISSUE TITLE
null metricdata in request  monitor graph

### ISSUE THREAD

**Issue by zdyj3170101136** [jaegertracing/jaeger-ui#933]
**Describe the bug**
only service request rate graph not have data in monitor page.

**To Reproduce**
1. run jaeger/docker-compose/monitor/docker-compose.yml

**Expected behavior**
service request graph show data in monitor page.
just like other graph.

**Screenshots**
<img width="334" alt="截屏2022-04-19 下午4 12 52" src="https://user-images.githubusercontent.com/52686065/163956806-f0393211-ff25-46fa-b53f-7e5bdc5d9267.png">

**Version (please complete the following information):**
 - OS: linux
 - Jaeger ui version: v1.22.0
 - Deployment:  Docker

**Additional context**
i think the problem is the null metricdata in https://github.com/jaegertracing/jaeger-ui/blob/main/packages/jaeger-ui/src/components/Monitor/ServicesView/index.tsx#L351.

after change it from
 ```null``` 
to
``` 
metrics.serviceMetrics ? metrics.serviceMetrics.service_call_rate : null
```
everything is well.

**Comment by nofar9792** [comment]
Hi,
i'm going to fix it
