### ISSUE TITLE
Create Trace Statistics Tooltips / Help Documentation

### ISSUE THREAD

**Issue by bforbis** [jaegertracing/jaeger-ui#962]
## Requirement - what kind of business use case are you trying to solve?

The UI should be user friendly to new users of Jaeger and describe all the details of what's shown on the page. Particularly, the trace statistics breakdown view has lots of info on it, but not a lot of details which describe what each column means.
![image](https://user-images.githubusercontent.com/16994570/174908645-698af526-074b-4dbf-86b9-1a3bed4bc50b.png)

An acronym "ST" is used in many places, but no place is it the acronym defined.

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger distinguishes "Total" from "ST Total" stats in the stats breakdown table, but it is very hard to find any documentation that explains the difference. I'm sure it is simple to explain, but finding that info as a beginner has been difficult.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
A few approaches:

- Attach hover-over tooltips / helpers to the columns in trace statistics which explain what each column is for
- Provide a web page in documentation that explains in detail each of the trace stat columns and link to that with a help button on the stats breakdown page

**Comment by bforbis** [comment]
I do now see that there has been confusion of these reported in the past in #689, and now I know that ST means "Self Time" from the help page on the trace graph view. Looks like it would be good to include this explanation across both views, as suggested in that closed ticket.

**Comment by yurishkuro** [comment]
+1 to have tooltips
